
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Agenda` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Agenda
 * 
 */
export type AgendaModel = runtime.Types.Result.DefaultSelection<Prisma.$AgendaPayload>

export type AggregateAgenda = {
  _count: AgendaCountAggregateOutputType | null
  _min: AgendaMinAggregateOutputType | null
  _max: AgendaMaxAggregateOutputType | null
}

export type AgendaMinAggregateOutputType = {
  id: string | null
  profissionalId: string | null
  diaSemana: $Enums.DiaSemana | null
  horaInicio: string | null
  horaFim: string | null
  ativo: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AgendaMaxAggregateOutputType = {
  id: string | null
  profissionalId: string | null
  diaSemana: $Enums.DiaSemana | null
  horaInicio: string | null
  horaFim: string | null
  ativo: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AgendaCountAggregateOutputType = {
  id: number
  profissionalId: number
  diaSemana: number
  horaInicio: number
  horaFim: number
  ativo: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type AgendaMinAggregateInputType = {
  id?: true
  profissionalId?: true
  diaSemana?: true
  horaInicio?: true
  horaFim?: true
  ativo?: true
  createdAt?: true
  updatedAt?: true
}

export type AgendaMaxAggregateInputType = {
  id?: true
  profissionalId?: true
  diaSemana?: true
  horaInicio?: true
  horaFim?: true
  ativo?: true
  createdAt?: true
  updatedAt?: true
}

export type AgendaCountAggregateInputType = {
  id?: true
  profissionalId?: true
  diaSemana?: true
  horaInicio?: true
  horaFim?: true
  ativo?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type AgendaAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Agenda to aggregate.
   */
  where?: Prisma.AgendaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Agenda to fetch.
   */
  orderBy?: Prisma.AgendaOrderByWithRelationInput | Prisma.AgendaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AgendaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Agenda from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Agenda.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Agenda
  **/
  _count?: true | AgendaCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AgendaMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AgendaMaxAggregateInputType
}

export type GetAgendaAggregateType<T extends AgendaAggregateArgs> = {
      [P in keyof T & keyof AggregateAgenda]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAgenda[P]>
    : Prisma.GetScalarType<T[P], AggregateAgenda[P]>
}




export type AgendaGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AgendaWhereInput
  orderBy?: Prisma.AgendaOrderByWithAggregationInput | Prisma.AgendaOrderByWithAggregationInput[]
  by: Prisma.AgendaScalarFieldEnum[] | Prisma.AgendaScalarFieldEnum
  having?: Prisma.AgendaScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AgendaCountAggregateInputType | true
  _min?: AgendaMinAggregateInputType
  _max?: AgendaMaxAggregateInputType
}

export type AgendaGroupByOutputType = {
  id: string
  profissionalId: string
  diaSemana: $Enums.DiaSemana
  horaInicio: string
  horaFim: string
  ativo: boolean
  createdAt: Date
  updatedAt: Date
  _count: AgendaCountAggregateOutputType | null
  _min: AgendaMinAggregateOutputType | null
  _max: AgendaMaxAggregateOutputType | null
}

type GetAgendaGroupByPayload<T extends AgendaGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AgendaGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AgendaGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AgendaGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AgendaGroupByOutputType[P]>
      }
    >
  >



export type AgendaWhereInput = {
  AND?: Prisma.AgendaWhereInput | Prisma.AgendaWhereInput[]
  OR?: Prisma.AgendaWhereInput[]
  NOT?: Prisma.AgendaWhereInput | Prisma.AgendaWhereInput[]
  id?: Prisma.StringFilter<"Agenda"> | string
  profissionalId?: Prisma.StringFilter<"Agenda"> | string
  diaSemana?: Prisma.EnumDiaSemanaFilter<"Agenda"> | $Enums.DiaSemana
  horaInicio?: Prisma.StringFilter<"Agenda"> | string
  horaFim?: Prisma.StringFilter<"Agenda"> | string
  ativo?: Prisma.BoolFilter<"Agenda"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Agenda"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Agenda"> | Date | string
  profissional?: Prisma.XOR<Prisma.ProfissionalScalarRelationFilter, Prisma.ProfissionalWhereInput>
}

export type AgendaOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  profissionalId?: Prisma.SortOrder
  diaSemana?: Prisma.SortOrder
  horaInicio?: Prisma.SortOrder
  horaFim?: Prisma.SortOrder
  ativo?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  profissional?: Prisma.ProfissionalOrderByWithRelationInput
}

export type AgendaWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.AgendaWhereInput | Prisma.AgendaWhereInput[]
  OR?: Prisma.AgendaWhereInput[]
  NOT?: Prisma.AgendaWhereInput | Prisma.AgendaWhereInput[]
  profissionalId?: Prisma.StringFilter<"Agenda"> | string
  diaSemana?: Prisma.EnumDiaSemanaFilter<"Agenda"> | $Enums.DiaSemana
  horaInicio?: Prisma.StringFilter<"Agenda"> | string
  horaFim?: Prisma.StringFilter<"Agenda"> | string
  ativo?: Prisma.BoolFilter<"Agenda"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Agenda"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Agenda"> | Date | string
  profissional?: Prisma.XOR<Prisma.ProfissionalScalarRelationFilter, Prisma.ProfissionalWhereInput>
}, "id">

export type AgendaOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  profissionalId?: Prisma.SortOrder
  diaSemana?: Prisma.SortOrder
  horaInicio?: Prisma.SortOrder
  horaFim?: Prisma.SortOrder
  ativo?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.AgendaCountOrderByAggregateInput
  _max?: Prisma.AgendaMaxOrderByAggregateInput
  _min?: Prisma.AgendaMinOrderByAggregateInput
}

export type AgendaScalarWhereWithAggregatesInput = {
  AND?: Prisma.AgendaScalarWhereWithAggregatesInput | Prisma.AgendaScalarWhereWithAggregatesInput[]
  OR?: Prisma.AgendaScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AgendaScalarWhereWithAggregatesInput | Prisma.AgendaScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Agenda"> | string
  profissionalId?: Prisma.StringWithAggregatesFilter<"Agenda"> | string
  diaSemana?: Prisma.EnumDiaSemanaWithAggregatesFilter<"Agenda"> | $Enums.DiaSemana
  horaInicio?: Prisma.StringWithAggregatesFilter<"Agenda"> | string
  horaFim?: Prisma.StringWithAggregatesFilter<"Agenda"> | string
  ativo?: Prisma.BoolWithAggregatesFilter<"Agenda"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Agenda"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Agenda"> | Date | string
}

export type AgendaCreateInput = {
  id?: string
  diaSemana: $Enums.DiaSemana
  horaInicio: string
  horaFim: string
  ativo?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  profissional: Prisma.ProfissionalCreateNestedOneWithoutAgendasInput
}

export type AgendaUncheckedCreateInput = {
  id?: string
  profissionalId: string
  diaSemana: $Enums.DiaSemana
  horaInicio: string
  horaFim: string
  ativo?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AgendaUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  diaSemana?: Prisma.EnumDiaSemanaFieldUpdateOperationsInput | $Enums.DiaSemana
  horaInicio?: Prisma.StringFieldUpdateOperationsInput | string
  horaFim?: Prisma.StringFieldUpdateOperationsInput | string
  ativo?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  profissional?: Prisma.ProfissionalUpdateOneRequiredWithoutAgendasNestedInput
}

export type AgendaUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  profissionalId?: Prisma.StringFieldUpdateOperationsInput | string
  diaSemana?: Prisma.EnumDiaSemanaFieldUpdateOperationsInput | $Enums.DiaSemana
  horaInicio?: Prisma.StringFieldUpdateOperationsInput | string
  horaFim?: Prisma.StringFieldUpdateOperationsInput | string
  ativo?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgendaCreateManyInput = {
  id?: string
  profissionalId: string
  diaSemana: $Enums.DiaSemana
  horaInicio: string
  horaFim: string
  ativo?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AgendaUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  diaSemana?: Prisma.EnumDiaSemanaFieldUpdateOperationsInput | $Enums.DiaSemana
  horaInicio?: Prisma.StringFieldUpdateOperationsInput | string
  horaFim?: Prisma.StringFieldUpdateOperationsInput | string
  ativo?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgendaUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  profissionalId?: Prisma.StringFieldUpdateOperationsInput | string
  diaSemana?: Prisma.EnumDiaSemanaFieldUpdateOperationsInput | $Enums.DiaSemana
  horaInicio?: Prisma.StringFieldUpdateOperationsInput | string
  horaFim?: Prisma.StringFieldUpdateOperationsInput | string
  ativo?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgendaListRelationFilter = {
  every?: Prisma.AgendaWhereInput
  some?: Prisma.AgendaWhereInput
  none?: Prisma.AgendaWhereInput
}

export type AgendaOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AgendaCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  profissionalId?: Prisma.SortOrder
  diaSemana?: Prisma.SortOrder
  horaInicio?: Prisma.SortOrder
  horaFim?: Prisma.SortOrder
  ativo?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AgendaMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  profissionalId?: Prisma.SortOrder
  diaSemana?: Prisma.SortOrder
  horaInicio?: Prisma.SortOrder
  horaFim?: Prisma.SortOrder
  ativo?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AgendaMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  profissionalId?: Prisma.SortOrder
  diaSemana?: Prisma.SortOrder
  horaInicio?: Prisma.SortOrder
  horaFim?: Prisma.SortOrder
  ativo?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AgendaCreateNestedManyWithoutProfissionalInput = {
  create?: Prisma.XOR<Prisma.AgendaCreateWithoutProfissionalInput, Prisma.AgendaUncheckedCreateWithoutProfissionalInput> | Prisma.AgendaCreateWithoutProfissionalInput[] | Prisma.AgendaUncheckedCreateWithoutProfissionalInput[]
  connectOrCreate?: Prisma.AgendaCreateOrConnectWithoutProfissionalInput | Prisma.AgendaCreateOrConnectWithoutProfissionalInput[]
  createMany?: Prisma.AgendaCreateManyProfissionalInputEnvelope
  connect?: Prisma.AgendaWhereUniqueInput | Prisma.AgendaWhereUniqueInput[]
}

export type AgendaUncheckedCreateNestedManyWithoutProfissionalInput = {
  create?: Prisma.XOR<Prisma.AgendaCreateWithoutProfissionalInput, Prisma.AgendaUncheckedCreateWithoutProfissionalInput> | Prisma.AgendaCreateWithoutProfissionalInput[] | Prisma.AgendaUncheckedCreateWithoutProfissionalInput[]
  connectOrCreate?: Prisma.AgendaCreateOrConnectWithoutProfissionalInput | Prisma.AgendaCreateOrConnectWithoutProfissionalInput[]
  createMany?: Prisma.AgendaCreateManyProfissionalInputEnvelope
  connect?: Prisma.AgendaWhereUniqueInput | Prisma.AgendaWhereUniqueInput[]
}

export type AgendaUpdateManyWithoutProfissionalNestedInput = {
  create?: Prisma.XOR<Prisma.AgendaCreateWithoutProfissionalInput, Prisma.AgendaUncheckedCreateWithoutProfissionalInput> | Prisma.AgendaCreateWithoutProfissionalInput[] | Prisma.AgendaUncheckedCreateWithoutProfissionalInput[]
  connectOrCreate?: Prisma.AgendaCreateOrConnectWithoutProfissionalInput | Prisma.AgendaCreateOrConnectWithoutProfissionalInput[]
  upsert?: Prisma.AgendaUpsertWithWhereUniqueWithoutProfissionalInput | Prisma.AgendaUpsertWithWhereUniqueWithoutProfissionalInput[]
  createMany?: Prisma.AgendaCreateManyProfissionalInputEnvelope
  set?: Prisma.AgendaWhereUniqueInput | Prisma.AgendaWhereUniqueInput[]
  disconnect?: Prisma.AgendaWhereUniqueInput | Prisma.AgendaWhereUniqueInput[]
  delete?: Prisma.AgendaWhereUniqueInput | Prisma.AgendaWhereUniqueInput[]
  connect?: Prisma.AgendaWhereUniqueInput | Prisma.AgendaWhereUniqueInput[]
  update?: Prisma.AgendaUpdateWithWhereUniqueWithoutProfissionalInput | Prisma.AgendaUpdateWithWhereUniqueWithoutProfissionalInput[]
  updateMany?: Prisma.AgendaUpdateManyWithWhereWithoutProfissionalInput | Prisma.AgendaUpdateManyWithWhereWithoutProfissionalInput[]
  deleteMany?: Prisma.AgendaScalarWhereInput | Prisma.AgendaScalarWhereInput[]
}

export type AgendaUncheckedUpdateManyWithoutProfissionalNestedInput = {
  create?: Prisma.XOR<Prisma.AgendaCreateWithoutProfissionalInput, Prisma.AgendaUncheckedCreateWithoutProfissionalInput> | Prisma.AgendaCreateWithoutProfissionalInput[] | Prisma.AgendaUncheckedCreateWithoutProfissionalInput[]
  connectOrCreate?: Prisma.AgendaCreateOrConnectWithoutProfissionalInput | Prisma.AgendaCreateOrConnectWithoutProfissionalInput[]
  upsert?: Prisma.AgendaUpsertWithWhereUniqueWithoutProfissionalInput | Prisma.AgendaUpsertWithWhereUniqueWithoutProfissionalInput[]
  createMany?: Prisma.AgendaCreateManyProfissionalInputEnvelope
  set?: Prisma.AgendaWhereUniqueInput | Prisma.AgendaWhereUniqueInput[]
  disconnect?: Prisma.AgendaWhereUniqueInput | Prisma.AgendaWhereUniqueInput[]
  delete?: Prisma.AgendaWhereUniqueInput | Prisma.AgendaWhereUniqueInput[]
  connect?: Prisma.AgendaWhereUniqueInput | Prisma.AgendaWhereUniqueInput[]
  update?: Prisma.AgendaUpdateWithWhereUniqueWithoutProfissionalInput | Prisma.AgendaUpdateWithWhereUniqueWithoutProfissionalInput[]
  updateMany?: Prisma.AgendaUpdateManyWithWhereWithoutProfissionalInput | Prisma.AgendaUpdateManyWithWhereWithoutProfissionalInput[]
  deleteMany?: Prisma.AgendaScalarWhereInput | Prisma.AgendaScalarWhereInput[]
}

export type EnumDiaSemanaFieldUpdateOperationsInput = {
  set?: $Enums.DiaSemana
}

export type AgendaCreateWithoutProfissionalInput = {
  id?: string
  diaSemana: $Enums.DiaSemana
  horaInicio: string
  horaFim: string
  ativo?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AgendaUncheckedCreateWithoutProfissionalInput = {
  id?: string
  diaSemana: $Enums.DiaSemana
  horaInicio: string
  horaFim: string
  ativo?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AgendaCreateOrConnectWithoutProfissionalInput = {
  where: Prisma.AgendaWhereUniqueInput
  create: Prisma.XOR<Prisma.AgendaCreateWithoutProfissionalInput, Prisma.AgendaUncheckedCreateWithoutProfissionalInput>
}

export type AgendaCreateManyProfissionalInputEnvelope = {
  data: Prisma.AgendaCreateManyProfissionalInput | Prisma.AgendaCreateManyProfissionalInput[]
  skipDuplicates?: boolean
}

export type AgendaUpsertWithWhereUniqueWithoutProfissionalInput = {
  where: Prisma.AgendaWhereUniqueInput
  update: Prisma.XOR<Prisma.AgendaUpdateWithoutProfissionalInput, Prisma.AgendaUncheckedUpdateWithoutProfissionalInput>
  create: Prisma.XOR<Prisma.AgendaCreateWithoutProfissionalInput, Prisma.AgendaUncheckedCreateWithoutProfissionalInput>
}

export type AgendaUpdateWithWhereUniqueWithoutProfissionalInput = {
  where: Prisma.AgendaWhereUniqueInput
  data: Prisma.XOR<Prisma.AgendaUpdateWithoutProfissionalInput, Prisma.AgendaUncheckedUpdateWithoutProfissionalInput>
}

export type AgendaUpdateManyWithWhereWithoutProfissionalInput = {
  where: Prisma.AgendaScalarWhereInput
  data: Prisma.XOR<Prisma.AgendaUpdateManyMutationInput, Prisma.AgendaUncheckedUpdateManyWithoutProfissionalInput>
}

export type AgendaScalarWhereInput = {
  AND?: Prisma.AgendaScalarWhereInput | Prisma.AgendaScalarWhereInput[]
  OR?: Prisma.AgendaScalarWhereInput[]
  NOT?: Prisma.AgendaScalarWhereInput | Prisma.AgendaScalarWhereInput[]
  id?: Prisma.StringFilter<"Agenda"> | string
  profissionalId?: Prisma.StringFilter<"Agenda"> | string
  diaSemana?: Prisma.EnumDiaSemanaFilter<"Agenda"> | $Enums.DiaSemana
  horaInicio?: Prisma.StringFilter<"Agenda"> | string
  horaFim?: Prisma.StringFilter<"Agenda"> | string
  ativo?: Prisma.BoolFilter<"Agenda"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Agenda"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Agenda"> | Date | string
}

export type AgendaCreateManyProfissionalInput = {
  id?: string
  diaSemana: $Enums.DiaSemana
  horaInicio: string
  horaFim: string
  ativo?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AgendaUpdateWithoutProfissionalInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  diaSemana?: Prisma.EnumDiaSemanaFieldUpdateOperationsInput | $Enums.DiaSemana
  horaInicio?: Prisma.StringFieldUpdateOperationsInput | string
  horaFim?: Prisma.StringFieldUpdateOperationsInput | string
  ativo?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgendaUncheckedUpdateWithoutProfissionalInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  diaSemana?: Prisma.EnumDiaSemanaFieldUpdateOperationsInput | $Enums.DiaSemana
  horaInicio?: Prisma.StringFieldUpdateOperationsInput | string
  horaFim?: Prisma.StringFieldUpdateOperationsInput | string
  ativo?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgendaUncheckedUpdateManyWithoutProfissionalInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  diaSemana?: Prisma.EnumDiaSemanaFieldUpdateOperationsInput | $Enums.DiaSemana
  horaInicio?: Prisma.StringFieldUpdateOperationsInput | string
  horaFim?: Prisma.StringFieldUpdateOperationsInput | string
  ativo?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type AgendaSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  profissionalId?: boolean
  diaSemana?: boolean
  horaInicio?: boolean
  horaFim?: boolean
  ativo?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  profissional?: boolean | Prisma.ProfissionalDefaultArgs<ExtArgs>
}, ExtArgs["result"]["agenda"]>

export type AgendaSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  profissionalId?: boolean
  diaSemana?: boolean
  horaInicio?: boolean
  horaFim?: boolean
  ativo?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  profissional?: boolean | Prisma.ProfissionalDefaultArgs<ExtArgs>
}, ExtArgs["result"]["agenda"]>

export type AgendaSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  profissionalId?: boolean
  diaSemana?: boolean
  horaInicio?: boolean
  horaFim?: boolean
  ativo?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  profissional?: boolean | Prisma.ProfissionalDefaultArgs<ExtArgs>
}, ExtArgs["result"]["agenda"]>

export type AgendaSelectScalar = {
  id?: boolean
  profissionalId?: boolean
  diaSemana?: boolean
  horaInicio?: boolean
  horaFim?: boolean
  ativo?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type AgendaOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "profissionalId" | "diaSemana" | "horaInicio" | "horaFim" | "ativo" | "createdAt" | "updatedAt", ExtArgs["result"]["agenda"]>
export type AgendaInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  profissional?: boolean | Prisma.ProfissionalDefaultArgs<ExtArgs>
}
export type AgendaIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  profissional?: boolean | Prisma.ProfissionalDefaultArgs<ExtArgs>
}
export type AgendaIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  profissional?: boolean | Prisma.ProfissionalDefaultArgs<ExtArgs>
}

export type $AgendaPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Agenda"
  objects: {
    profissional: Prisma.$ProfissionalPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    profissionalId: string
    diaSemana: $Enums.DiaSemana
    horaInicio: string
    horaFim: string
    ativo: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["agenda"]>
  composites: {}
}

export type AgendaGetPayload<S extends boolean | null | undefined | AgendaDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AgendaPayload, S>

export type AgendaCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AgendaFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AgendaCountAggregateInputType | true
  }

export interface AgendaDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Agenda'], meta: { name: 'Agenda' } }
  /**
   * Find zero or one Agenda that matches the filter.
   * @param {AgendaFindUniqueArgs} args - Arguments to find a Agenda
   * @example
   * // Get one Agenda
   * const agenda = await prisma.agenda.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AgendaFindUniqueArgs>(args: Prisma.SelectSubset<T, AgendaFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AgendaClient<runtime.Types.Result.GetResult<Prisma.$AgendaPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Agenda that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AgendaFindUniqueOrThrowArgs} args - Arguments to find a Agenda
   * @example
   * // Get one Agenda
   * const agenda = await prisma.agenda.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AgendaFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AgendaFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AgendaClient<runtime.Types.Result.GetResult<Prisma.$AgendaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Agenda that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgendaFindFirstArgs} args - Arguments to find a Agenda
   * @example
   * // Get one Agenda
   * const agenda = await prisma.agenda.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AgendaFindFirstArgs>(args?: Prisma.SelectSubset<T, AgendaFindFirstArgs<ExtArgs>>): Prisma.Prisma__AgendaClient<runtime.Types.Result.GetResult<Prisma.$AgendaPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Agenda that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgendaFindFirstOrThrowArgs} args - Arguments to find a Agenda
   * @example
   * // Get one Agenda
   * const agenda = await prisma.agenda.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AgendaFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AgendaFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AgendaClient<runtime.Types.Result.GetResult<Prisma.$AgendaPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Agenda that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgendaFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Agenda
   * const agenda = await prisma.agenda.findMany()
   * 
   * // Get first 10 Agenda
   * const agenda = await prisma.agenda.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const agendaWithIdOnly = await prisma.agenda.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AgendaFindManyArgs>(args?: Prisma.SelectSubset<T, AgendaFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgendaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Agenda.
   * @param {AgendaCreateArgs} args - Arguments to create a Agenda.
   * @example
   * // Create one Agenda
   * const Agenda = await prisma.agenda.create({
   *   data: {
   *     // ... data to create a Agenda
   *   }
   * })
   * 
   */
  create<T extends AgendaCreateArgs>(args: Prisma.SelectSubset<T, AgendaCreateArgs<ExtArgs>>): Prisma.Prisma__AgendaClient<runtime.Types.Result.GetResult<Prisma.$AgendaPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Agenda.
   * @param {AgendaCreateManyArgs} args - Arguments to create many Agenda.
   * @example
   * // Create many Agenda
   * const agenda = await prisma.agenda.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AgendaCreateManyArgs>(args?: Prisma.SelectSubset<T, AgendaCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Agenda and returns the data saved in the database.
   * @param {AgendaCreateManyAndReturnArgs} args - Arguments to create many Agenda.
   * @example
   * // Create many Agenda
   * const agenda = await prisma.agenda.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Agenda and only return the `id`
   * const agendaWithIdOnly = await prisma.agenda.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AgendaCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AgendaCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgendaPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Agenda.
   * @param {AgendaDeleteArgs} args - Arguments to delete one Agenda.
   * @example
   * // Delete one Agenda
   * const Agenda = await prisma.agenda.delete({
   *   where: {
   *     // ... filter to delete one Agenda
   *   }
   * })
   * 
   */
  delete<T extends AgendaDeleteArgs>(args: Prisma.SelectSubset<T, AgendaDeleteArgs<ExtArgs>>): Prisma.Prisma__AgendaClient<runtime.Types.Result.GetResult<Prisma.$AgendaPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Agenda.
   * @param {AgendaUpdateArgs} args - Arguments to update one Agenda.
   * @example
   * // Update one Agenda
   * const agenda = await prisma.agenda.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AgendaUpdateArgs>(args: Prisma.SelectSubset<T, AgendaUpdateArgs<ExtArgs>>): Prisma.Prisma__AgendaClient<runtime.Types.Result.GetResult<Prisma.$AgendaPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Agenda.
   * @param {AgendaDeleteManyArgs} args - Arguments to filter Agenda to delete.
   * @example
   * // Delete a few Agenda
   * const { count } = await prisma.agenda.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AgendaDeleteManyArgs>(args?: Prisma.SelectSubset<T, AgendaDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Agenda.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgendaUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Agenda
   * const agenda = await prisma.agenda.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AgendaUpdateManyArgs>(args: Prisma.SelectSubset<T, AgendaUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Agenda and returns the data updated in the database.
   * @param {AgendaUpdateManyAndReturnArgs} args - Arguments to update many Agenda.
   * @example
   * // Update many Agenda
   * const agenda = await prisma.agenda.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Agenda and only return the `id`
   * const agendaWithIdOnly = await prisma.agenda.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AgendaUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AgendaUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgendaPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Agenda.
   * @param {AgendaUpsertArgs} args - Arguments to update or create a Agenda.
   * @example
   * // Update or create a Agenda
   * const agenda = await prisma.agenda.upsert({
   *   create: {
   *     // ... data to create a Agenda
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Agenda we want to update
   *   }
   * })
   */
  upsert<T extends AgendaUpsertArgs>(args: Prisma.SelectSubset<T, AgendaUpsertArgs<ExtArgs>>): Prisma.Prisma__AgendaClient<runtime.Types.Result.GetResult<Prisma.$AgendaPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Agenda.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgendaCountArgs} args - Arguments to filter Agenda to count.
   * @example
   * // Count the number of Agenda
   * const count = await prisma.agenda.count({
   *   where: {
   *     // ... the filter for the Agenda we want to count
   *   }
   * })
  **/
  count<T extends AgendaCountArgs>(
    args?: Prisma.Subset<T, AgendaCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AgendaCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Agenda.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgendaAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AgendaAggregateArgs>(args: Prisma.Subset<T, AgendaAggregateArgs>): Prisma.PrismaPromise<GetAgendaAggregateType<T>>

  /**
   * Group by Agenda.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgendaGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AgendaGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AgendaGroupByArgs['orderBy'] }
      : { orderBy?: AgendaGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AgendaGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAgendaGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Agenda model
 */
readonly fields: AgendaFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Agenda.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AgendaClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  profissional<T extends Prisma.ProfissionalDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProfissionalDefaultArgs<ExtArgs>>): Prisma.Prisma__ProfissionalClient<runtime.Types.Result.GetResult<Prisma.$ProfissionalPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Agenda model
 */
export interface AgendaFieldRefs {
  readonly id: Prisma.FieldRef<"Agenda", 'String'>
  readonly profissionalId: Prisma.FieldRef<"Agenda", 'String'>
  readonly diaSemana: Prisma.FieldRef<"Agenda", 'DiaSemana'>
  readonly horaInicio: Prisma.FieldRef<"Agenda", 'String'>
  readonly horaFim: Prisma.FieldRef<"Agenda", 'String'>
  readonly ativo: Prisma.FieldRef<"Agenda", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"Agenda", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Agenda", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Agenda findUnique
 */
export type AgendaFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agenda
   */
  select?: Prisma.AgendaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Agenda
   */
  omit?: Prisma.AgendaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgendaInclude<ExtArgs> | null
  /**
   * Filter, which Agenda to fetch.
   */
  where: Prisma.AgendaWhereUniqueInput
}

/**
 * Agenda findUniqueOrThrow
 */
export type AgendaFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agenda
   */
  select?: Prisma.AgendaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Agenda
   */
  omit?: Prisma.AgendaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgendaInclude<ExtArgs> | null
  /**
   * Filter, which Agenda to fetch.
   */
  where: Prisma.AgendaWhereUniqueInput
}

/**
 * Agenda findFirst
 */
export type AgendaFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agenda
   */
  select?: Prisma.AgendaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Agenda
   */
  omit?: Prisma.AgendaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgendaInclude<ExtArgs> | null
  /**
   * Filter, which Agenda to fetch.
   */
  where?: Prisma.AgendaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Agenda to fetch.
   */
  orderBy?: Prisma.AgendaOrderByWithRelationInput | Prisma.AgendaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Agenda.
   */
  cursor?: Prisma.AgendaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Agenda from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Agenda.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Agenda.
   */
  distinct?: Prisma.AgendaScalarFieldEnum | Prisma.AgendaScalarFieldEnum[]
}

/**
 * Agenda findFirstOrThrow
 */
export type AgendaFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agenda
   */
  select?: Prisma.AgendaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Agenda
   */
  omit?: Prisma.AgendaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgendaInclude<ExtArgs> | null
  /**
   * Filter, which Agenda to fetch.
   */
  where?: Prisma.AgendaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Agenda to fetch.
   */
  orderBy?: Prisma.AgendaOrderByWithRelationInput | Prisma.AgendaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Agenda.
   */
  cursor?: Prisma.AgendaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Agenda from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Agenda.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Agenda.
   */
  distinct?: Prisma.AgendaScalarFieldEnum | Prisma.AgendaScalarFieldEnum[]
}

/**
 * Agenda findMany
 */
export type AgendaFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agenda
   */
  select?: Prisma.AgendaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Agenda
   */
  omit?: Prisma.AgendaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgendaInclude<ExtArgs> | null
  /**
   * Filter, which Agenda to fetch.
   */
  where?: Prisma.AgendaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Agenda to fetch.
   */
  orderBy?: Prisma.AgendaOrderByWithRelationInput | Prisma.AgendaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Agenda.
   */
  cursor?: Prisma.AgendaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Agenda from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Agenda.
   */
  skip?: number
  distinct?: Prisma.AgendaScalarFieldEnum | Prisma.AgendaScalarFieldEnum[]
}

/**
 * Agenda create
 */
export type AgendaCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agenda
   */
  select?: Prisma.AgendaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Agenda
   */
  omit?: Prisma.AgendaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgendaInclude<ExtArgs> | null
  /**
   * The data needed to create a Agenda.
   */
  data: Prisma.XOR<Prisma.AgendaCreateInput, Prisma.AgendaUncheckedCreateInput>
}

/**
 * Agenda createMany
 */
export type AgendaCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Agenda.
   */
  data: Prisma.AgendaCreateManyInput | Prisma.AgendaCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Agenda createManyAndReturn
 */
export type AgendaCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agenda
   */
  select?: Prisma.AgendaSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Agenda
   */
  omit?: Prisma.AgendaOmit<ExtArgs> | null
  /**
   * The data used to create many Agenda.
   */
  data: Prisma.AgendaCreateManyInput | Prisma.AgendaCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgendaIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Agenda update
 */
export type AgendaUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agenda
   */
  select?: Prisma.AgendaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Agenda
   */
  omit?: Prisma.AgendaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgendaInclude<ExtArgs> | null
  /**
   * The data needed to update a Agenda.
   */
  data: Prisma.XOR<Prisma.AgendaUpdateInput, Prisma.AgendaUncheckedUpdateInput>
  /**
   * Choose, which Agenda to update.
   */
  where: Prisma.AgendaWhereUniqueInput
}

/**
 * Agenda updateMany
 */
export type AgendaUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Agenda.
   */
  data: Prisma.XOR<Prisma.AgendaUpdateManyMutationInput, Prisma.AgendaUncheckedUpdateManyInput>
  /**
   * Filter which Agenda to update
   */
  where?: Prisma.AgendaWhereInput
  /**
   * Limit how many Agenda to update.
   */
  limit?: number
}

/**
 * Agenda updateManyAndReturn
 */
export type AgendaUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agenda
   */
  select?: Prisma.AgendaSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Agenda
   */
  omit?: Prisma.AgendaOmit<ExtArgs> | null
  /**
   * The data used to update Agenda.
   */
  data: Prisma.XOR<Prisma.AgendaUpdateManyMutationInput, Prisma.AgendaUncheckedUpdateManyInput>
  /**
   * Filter which Agenda to update
   */
  where?: Prisma.AgendaWhereInput
  /**
   * Limit how many Agenda to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgendaIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Agenda upsert
 */
export type AgendaUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agenda
   */
  select?: Prisma.AgendaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Agenda
   */
  omit?: Prisma.AgendaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgendaInclude<ExtArgs> | null
  /**
   * The filter to search for the Agenda to update in case it exists.
   */
  where: Prisma.AgendaWhereUniqueInput
  /**
   * In case the Agenda found by the `where` argument doesn't exist, create a new Agenda with this data.
   */
  create: Prisma.XOR<Prisma.AgendaCreateInput, Prisma.AgendaUncheckedCreateInput>
  /**
   * In case the Agenda was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AgendaUpdateInput, Prisma.AgendaUncheckedUpdateInput>
}

/**
 * Agenda delete
 */
export type AgendaDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agenda
   */
  select?: Prisma.AgendaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Agenda
   */
  omit?: Prisma.AgendaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgendaInclude<ExtArgs> | null
  /**
   * Filter which Agenda to delete.
   */
  where: Prisma.AgendaWhereUniqueInput
}

/**
 * Agenda deleteMany
 */
export type AgendaDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Agenda to delete
   */
  where?: Prisma.AgendaWhereInput
  /**
   * Limit how many Agenda to delete.
   */
  limit?: number
}

/**
 * Agenda without action
 */
export type AgendaDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agenda
   */
  select?: Prisma.AgendaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Agenda
   */
  omit?: Prisma.AgendaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgendaInclude<ExtArgs> | null
}
