
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Leito` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Leito
 * 
 */
export type LeitoModel = runtime.Types.Result.DefaultSelection<Prisma.$LeitoPayload>

export type AggregateLeito = {
  _count: LeitoCountAggregateOutputType | null
  _min: LeitoMinAggregateOutputType | null
  _max: LeitoMaxAggregateOutputType | null
}

export type LeitoMinAggregateOutputType = {
  id: string | null
  unidadeId: string | null
  numero: string | null
  tipo: string | null
  status: $Enums.StatusLeito | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type LeitoMaxAggregateOutputType = {
  id: string | null
  unidadeId: string | null
  numero: string | null
  tipo: string | null
  status: $Enums.StatusLeito | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type LeitoCountAggregateOutputType = {
  id: number
  unidadeId: number
  numero: number
  tipo: number
  status: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type LeitoMinAggregateInputType = {
  id?: true
  unidadeId?: true
  numero?: true
  tipo?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type LeitoMaxAggregateInputType = {
  id?: true
  unidadeId?: true
  numero?: true
  tipo?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type LeitoCountAggregateInputType = {
  id?: true
  unidadeId?: true
  numero?: true
  tipo?: true
  status?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type LeitoAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Leito to aggregate.
   */
  where?: Prisma.LeitoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Leitos to fetch.
   */
  orderBy?: Prisma.LeitoOrderByWithRelationInput | Prisma.LeitoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.LeitoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Leitos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Leitos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Leitos
  **/
  _count?: true | LeitoCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: LeitoMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: LeitoMaxAggregateInputType
}

export type GetLeitoAggregateType<T extends LeitoAggregateArgs> = {
      [P in keyof T & keyof AggregateLeito]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateLeito[P]>
    : Prisma.GetScalarType<T[P], AggregateLeito[P]>
}




export type LeitoGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LeitoWhereInput
  orderBy?: Prisma.LeitoOrderByWithAggregationInput | Prisma.LeitoOrderByWithAggregationInput[]
  by: Prisma.LeitoScalarFieldEnum[] | Prisma.LeitoScalarFieldEnum
  having?: Prisma.LeitoScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: LeitoCountAggregateInputType | true
  _min?: LeitoMinAggregateInputType
  _max?: LeitoMaxAggregateInputType
}

export type LeitoGroupByOutputType = {
  id: string
  unidadeId: string
  numero: string
  tipo: string
  status: $Enums.StatusLeito
  createdAt: Date
  updatedAt: Date
  _count: LeitoCountAggregateOutputType | null
  _min: LeitoMinAggregateOutputType | null
  _max: LeitoMaxAggregateOutputType | null
}

type GetLeitoGroupByPayload<T extends LeitoGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<LeitoGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof LeitoGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], LeitoGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], LeitoGroupByOutputType[P]>
      }
    >
  >



export type LeitoWhereInput = {
  AND?: Prisma.LeitoWhereInput | Prisma.LeitoWhereInput[]
  OR?: Prisma.LeitoWhereInput[]
  NOT?: Prisma.LeitoWhereInput | Prisma.LeitoWhereInput[]
  id?: Prisma.StringFilter<"Leito"> | string
  unidadeId?: Prisma.StringFilter<"Leito"> | string
  numero?: Prisma.StringFilter<"Leito"> | string
  tipo?: Prisma.StringFilter<"Leito"> | string
  status?: Prisma.EnumStatusLeitoFilter<"Leito"> | $Enums.StatusLeito
  createdAt?: Prisma.DateTimeFilter<"Leito"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Leito"> | Date | string
  unidade?: Prisma.XOR<Prisma.UnidadeHospitalarScalarRelationFilter, Prisma.UnidadeHospitalarWhereInput>
}

export type LeitoOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  unidadeId?: Prisma.SortOrder
  numero?: Prisma.SortOrder
  tipo?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  unidade?: Prisma.UnidadeHospitalarOrderByWithRelationInput
}

export type LeitoWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.LeitoWhereInput | Prisma.LeitoWhereInput[]
  OR?: Prisma.LeitoWhereInput[]
  NOT?: Prisma.LeitoWhereInput | Prisma.LeitoWhereInput[]
  unidadeId?: Prisma.StringFilter<"Leito"> | string
  numero?: Prisma.StringFilter<"Leito"> | string
  tipo?: Prisma.StringFilter<"Leito"> | string
  status?: Prisma.EnumStatusLeitoFilter<"Leito"> | $Enums.StatusLeito
  createdAt?: Prisma.DateTimeFilter<"Leito"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Leito"> | Date | string
  unidade?: Prisma.XOR<Prisma.UnidadeHospitalarScalarRelationFilter, Prisma.UnidadeHospitalarWhereInput>
}, "id">

export type LeitoOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  unidadeId?: Prisma.SortOrder
  numero?: Prisma.SortOrder
  tipo?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.LeitoCountOrderByAggregateInput
  _max?: Prisma.LeitoMaxOrderByAggregateInput
  _min?: Prisma.LeitoMinOrderByAggregateInput
}

export type LeitoScalarWhereWithAggregatesInput = {
  AND?: Prisma.LeitoScalarWhereWithAggregatesInput | Prisma.LeitoScalarWhereWithAggregatesInput[]
  OR?: Prisma.LeitoScalarWhereWithAggregatesInput[]
  NOT?: Prisma.LeitoScalarWhereWithAggregatesInput | Prisma.LeitoScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Leito"> | string
  unidadeId?: Prisma.StringWithAggregatesFilter<"Leito"> | string
  numero?: Prisma.StringWithAggregatesFilter<"Leito"> | string
  tipo?: Prisma.StringWithAggregatesFilter<"Leito"> | string
  status?: Prisma.EnumStatusLeitoWithAggregatesFilter<"Leito"> | $Enums.StatusLeito
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Leito"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Leito"> | Date | string
}

export type LeitoCreateInput = {
  id?: string
  numero: string
  tipo: string
  status?: $Enums.StatusLeito
  createdAt?: Date | string
  updatedAt?: Date | string
  unidade: Prisma.UnidadeHospitalarCreateNestedOneWithoutLeitosInput
}

export type LeitoUncheckedCreateInput = {
  id?: string
  unidadeId: string
  numero: string
  tipo: string
  status?: $Enums.StatusLeito
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LeitoUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  numero?: Prisma.StringFieldUpdateOperationsInput | string
  tipo?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumStatusLeitoFieldUpdateOperationsInput | $Enums.StatusLeito
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  unidade?: Prisma.UnidadeHospitalarUpdateOneRequiredWithoutLeitosNestedInput
}

export type LeitoUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unidadeId?: Prisma.StringFieldUpdateOperationsInput | string
  numero?: Prisma.StringFieldUpdateOperationsInput | string
  tipo?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumStatusLeitoFieldUpdateOperationsInput | $Enums.StatusLeito
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LeitoCreateManyInput = {
  id?: string
  unidadeId: string
  numero: string
  tipo: string
  status?: $Enums.StatusLeito
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LeitoUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  numero?: Prisma.StringFieldUpdateOperationsInput | string
  tipo?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumStatusLeitoFieldUpdateOperationsInput | $Enums.StatusLeito
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LeitoUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unidadeId?: Prisma.StringFieldUpdateOperationsInput | string
  numero?: Prisma.StringFieldUpdateOperationsInput | string
  tipo?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumStatusLeitoFieldUpdateOperationsInput | $Enums.StatusLeito
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LeitoListRelationFilter = {
  every?: Prisma.LeitoWhereInput
  some?: Prisma.LeitoWhereInput
  none?: Prisma.LeitoWhereInput
}

export type LeitoOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type LeitoCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  unidadeId?: Prisma.SortOrder
  numero?: Prisma.SortOrder
  tipo?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LeitoMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  unidadeId?: Prisma.SortOrder
  numero?: Prisma.SortOrder
  tipo?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LeitoMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  unidadeId?: Prisma.SortOrder
  numero?: Prisma.SortOrder
  tipo?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LeitoCreateNestedManyWithoutUnidadeInput = {
  create?: Prisma.XOR<Prisma.LeitoCreateWithoutUnidadeInput, Prisma.LeitoUncheckedCreateWithoutUnidadeInput> | Prisma.LeitoCreateWithoutUnidadeInput[] | Prisma.LeitoUncheckedCreateWithoutUnidadeInput[]
  connectOrCreate?: Prisma.LeitoCreateOrConnectWithoutUnidadeInput | Prisma.LeitoCreateOrConnectWithoutUnidadeInput[]
  createMany?: Prisma.LeitoCreateManyUnidadeInputEnvelope
  connect?: Prisma.LeitoWhereUniqueInput | Prisma.LeitoWhereUniqueInput[]
}

export type LeitoUncheckedCreateNestedManyWithoutUnidadeInput = {
  create?: Prisma.XOR<Prisma.LeitoCreateWithoutUnidadeInput, Prisma.LeitoUncheckedCreateWithoutUnidadeInput> | Prisma.LeitoCreateWithoutUnidadeInput[] | Prisma.LeitoUncheckedCreateWithoutUnidadeInput[]
  connectOrCreate?: Prisma.LeitoCreateOrConnectWithoutUnidadeInput | Prisma.LeitoCreateOrConnectWithoutUnidadeInput[]
  createMany?: Prisma.LeitoCreateManyUnidadeInputEnvelope
  connect?: Prisma.LeitoWhereUniqueInput | Prisma.LeitoWhereUniqueInput[]
}

export type LeitoUpdateManyWithoutUnidadeNestedInput = {
  create?: Prisma.XOR<Prisma.LeitoCreateWithoutUnidadeInput, Prisma.LeitoUncheckedCreateWithoutUnidadeInput> | Prisma.LeitoCreateWithoutUnidadeInput[] | Prisma.LeitoUncheckedCreateWithoutUnidadeInput[]
  connectOrCreate?: Prisma.LeitoCreateOrConnectWithoutUnidadeInput | Prisma.LeitoCreateOrConnectWithoutUnidadeInput[]
  upsert?: Prisma.LeitoUpsertWithWhereUniqueWithoutUnidadeInput | Prisma.LeitoUpsertWithWhereUniqueWithoutUnidadeInput[]
  createMany?: Prisma.LeitoCreateManyUnidadeInputEnvelope
  set?: Prisma.LeitoWhereUniqueInput | Prisma.LeitoWhereUniqueInput[]
  disconnect?: Prisma.LeitoWhereUniqueInput | Prisma.LeitoWhereUniqueInput[]
  delete?: Prisma.LeitoWhereUniqueInput | Prisma.LeitoWhereUniqueInput[]
  connect?: Prisma.LeitoWhereUniqueInput | Prisma.LeitoWhereUniqueInput[]
  update?: Prisma.LeitoUpdateWithWhereUniqueWithoutUnidadeInput | Prisma.LeitoUpdateWithWhereUniqueWithoutUnidadeInput[]
  updateMany?: Prisma.LeitoUpdateManyWithWhereWithoutUnidadeInput | Prisma.LeitoUpdateManyWithWhereWithoutUnidadeInput[]
  deleteMany?: Prisma.LeitoScalarWhereInput | Prisma.LeitoScalarWhereInput[]
}

export type LeitoUncheckedUpdateManyWithoutUnidadeNestedInput = {
  create?: Prisma.XOR<Prisma.LeitoCreateWithoutUnidadeInput, Prisma.LeitoUncheckedCreateWithoutUnidadeInput> | Prisma.LeitoCreateWithoutUnidadeInput[] | Prisma.LeitoUncheckedCreateWithoutUnidadeInput[]
  connectOrCreate?: Prisma.LeitoCreateOrConnectWithoutUnidadeInput | Prisma.LeitoCreateOrConnectWithoutUnidadeInput[]
  upsert?: Prisma.LeitoUpsertWithWhereUniqueWithoutUnidadeInput | Prisma.LeitoUpsertWithWhereUniqueWithoutUnidadeInput[]
  createMany?: Prisma.LeitoCreateManyUnidadeInputEnvelope
  set?: Prisma.LeitoWhereUniqueInput | Prisma.LeitoWhereUniqueInput[]
  disconnect?: Prisma.LeitoWhereUniqueInput | Prisma.LeitoWhereUniqueInput[]
  delete?: Prisma.LeitoWhereUniqueInput | Prisma.LeitoWhereUniqueInput[]
  connect?: Prisma.LeitoWhereUniqueInput | Prisma.LeitoWhereUniqueInput[]
  update?: Prisma.LeitoUpdateWithWhereUniqueWithoutUnidadeInput | Prisma.LeitoUpdateWithWhereUniqueWithoutUnidadeInput[]
  updateMany?: Prisma.LeitoUpdateManyWithWhereWithoutUnidadeInput | Prisma.LeitoUpdateManyWithWhereWithoutUnidadeInput[]
  deleteMany?: Prisma.LeitoScalarWhereInput | Prisma.LeitoScalarWhereInput[]
}

export type EnumStatusLeitoFieldUpdateOperationsInput = {
  set?: $Enums.StatusLeito
}

export type LeitoCreateWithoutUnidadeInput = {
  id?: string
  numero: string
  tipo: string
  status?: $Enums.StatusLeito
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LeitoUncheckedCreateWithoutUnidadeInput = {
  id?: string
  numero: string
  tipo: string
  status?: $Enums.StatusLeito
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LeitoCreateOrConnectWithoutUnidadeInput = {
  where: Prisma.LeitoWhereUniqueInput
  create: Prisma.XOR<Prisma.LeitoCreateWithoutUnidadeInput, Prisma.LeitoUncheckedCreateWithoutUnidadeInput>
}

export type LeitoCreateManyUnidadeInputEnvelope = {
  data: Prisma.LeitoCreateManyUnidadeInput | Prisma.LeitoCreateManyUnidadeInput[]
  skipDuplicates?: boolean
}

export type LeitoUpsertWithWhereUniqueWithoutUnidadeInput = {
  where: Prisma.LeitoWhereUniqueInput
  update: Prisma.XOR<Prisma.LeitoUpdateWithoutUnidadeInput, Prisma.LeitoUncheckedUpdateWithoutUnidadeInput>
  create: Prisma.XOR<Prisma.LeitoCreateWithoutUnidadeInput, Prisma.LeitoUncheckedCreateWithoutUnidadeInput>
}

export type LeitoUpdateWithWhereUniqueWithoutUnidadeInput = {
  where: Prisma.LeitoWhereUniqueInput
  data: Prisma.XOR<Prisma.LeitoUpdateWithoutUnidadeInput, Prisma.LeitoUncheckedUpdateWithoutUnidadeInput>
}

export type LeitoUpdateManyWithWhereWithoutUnidadeInput = {
  where: Prisma.LeitoScalarWhereInput
  data: Prisma.XOR<Prisma.LeitoUpdateManyMutationInput, Prisma.LeitoUncheckedUpdateManyWithoutUnidadeInput>
}

export type LeitoScalarWhereInput = {
  AND?: Prisma.LeitoScalarWhereInput | Prisma.LeitoScalarWhereInput[]
  OR?: Prisma.LeitoScalarWhereInput[]
  NOT?: Prisma.LeitoScalarWhereInput | Prisma.LeitoScalarWhereInput[]
  id?: Prisma.StringFilter<"Leito"> | string
  unidadeId?: Prisma.StringFilter<"Leito"> | string
  numero?: Prisma.StringFilter<"Leito"> | string
  tipo?: Prisma.StringFilter<"Leito"> | string
  status?: Prisma.EnumStatusLeitoFilter<"Leito"> | $Enums.StatusLeito
  createdAt?: Prisma.DateTimeFilter<"Leito"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Leito"> | Date | string
}

export type LeitoCreateManyUnidadeInput = {
  id?: string
  numero: string
  tipo: string
  status?: $Enums.StatusLeito
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LeitoUpdateWithoutUnidadeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  numero?: Prisma.StringFieldUpdateOperationsInput | string
  tipo?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumStatusLeitoFieldUpdateOperationsInput | $Enums.StatusLeito
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LeitoUncheckedUpdateWithoutUnidadeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  numero?: Prisma.StringFieldUpdateOperationsInput | string
  tipo?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumStatusLeitoFieldUpdateOperationsInput | $Enums.StatusLeito
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LeitoUncheckedUpdateManyWithoutUnidadeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  numero?: Prisma.StringFieldUpdateOperationsInput | string
  tipo?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumStatusLeitoFieldUpdateOperationsInput | $Enums.StatusLeito
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type LeitoSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  unidadeId?: boolean
  numero?: boolean
  tipo?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  unidade?: boolean | Prisma.UnidadeHospitalarDefaultArgs<ExtArgs>
}, ExtArgs["result"]["leito"]>

export type LeitoSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  unidadeId?: boolean
  numero?: boolean
  tipo?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  unidade?: boolean | Prisma.UnidadeHospitalarDefaultArgs<ExtArgs>
}, ExtArgs["result"]["leito"]>

export type LeitoSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  unidadeId?: boolean
  numero?: boolean
  tipo?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  unidade?: boolean | Prisma.UnidadeHospitalarDefaultArgs<ExtArgs>
}, ExtArgs["result"]["leito"]>

export type LeitoSelectScalar = {
  id?: boolean
  unidadeId?: boolean
  numero?: boolean
  tipo?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type LeitoOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "unidadeId" | "numero" | "tipo" | "status" | "createdAt" | "updatedAt", ExtArgs["result"]["leito"]>
export type LeitoInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  unidade?: boolean | Prisma.UnidadeHospitalarDefaultArgs<ExtArgs>
}
export type LeitoIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  unidade?: boolean | Prisma.UnidadeHospitalarDefaultArgs<ExtArgs>
}
export type LeitoIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  unidade?: boolean | Prisma.UnidadeHospitalarDefaultArgs<ExtArgs>
}

export type $LeitoPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Leito"
  objects: {
    unidade: Prisma.$UnidadeHospitalarPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    unidadeId: string
    numero: string
    tipo: string
    status: $Enums.StatusLeito
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["leito"]>
  composites: {}
}

export type LeitoGetPayload<S extends boolean | null | undefined | LeitoDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$LeitoPayload, S>

export type LeitoCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<LeitoFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: LeitoCountAggregateInputType | true
  }

export interface LeitoDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Leito'], meta: { name: 'Leito' } }
  /**
   * Find zero or one Leito that matches the filter.
   * @param {LeitoFindUniqueArgs} args - Arguments to find a Leito
   * @example
   * // Get one Leito
   * const leito = await prisma.leito.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends LeitoFindUniqueArgs>(args: Prisma.SelectSubset<T, LeitoFindUniqueArgs<ExtArgs>>): Prisma.Prisma__LeitoClient<runtime.Types.Result.GetResult<Prisma.$LeitoPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Leito that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {LeitoFindUniqueOrThrowArgs} args - Arguments to find a Leito
   * @example
   * // Get one Leito
   * const leito = await prisma.leito.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends LeitoFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, LeitoFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__LeitoClient<runtime.Types.Result.GetResult<Prisma.$LeitoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Leito that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeitoFindFirstArgs} args - Arguments to find a Leito
   * @example
   * // Get one Leito
   * const leito = await prisma.leito.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends LeitoFindFirstArgs>(args?: Prisma.SelectSubset<T, LeitoFindFirstArgs<ExtArgs>>): Prisma.Prisma__LeitoClient<runtime.Types.Result.GetResult<Prisma.$LeitoPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Leito that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeitoFindFirstOrThrowArgs} args - Arguments to find a Leito
   * @example
   * // Get one Leito
   * const leito = await prisma.leito.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends LeitoFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, LeitoFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__LeitoClient<runtime.Types.Result.GetResult<Prisma.$LeitoPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Leitos that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeitoFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Leitos
   * const leitos = await prisma.leito.findMany()
   * 
   * // Get first 10 Leitos
   * const leitos = await prisma.leito.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const leitoWithIdOnly = await prisma.leito.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends LeitoFindManyArgs>(args?: Prisma.SelectSubset<T, LeitoFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LeitoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Leito.
   * @param {LeitoCreateArgs} args - Arguments to create a Leito.
   * @example
   * // Create one Leito
   * const Leito = await prisma.leito.create({
   *   data: {
   *     // ... data to create a Leito
   *   }
   * })
   * 
   */
  create<T extends LeitoCreateArgs>(args: Prisma.SelectSubset<T, LeitoCreateArgs<ExtArgs>>): Prisma.Prisma__LeitoClient<runtime.Types.Result.GetResult<Prisma.$LeitoPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Leitos.
   * @param {LeitoCreateManyArgs} args - Arguments to create many Leitos.
   * @example
   * // Create many Leitos
   * const leito = await prisma.leito.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends LeitoCreateManyArgs>(args?: Prisma.SelectSubset<T, LeitoCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Leitos and returns the data saved in the database.
   * @param {LeitoCreateManyAndReturnArgs} args - Arguments to create many Leitos.
   * @example
   * // Create many Leitos
   * const leito = await prisma.leito.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Leitos and only return the `id`
   * const leitoWithIdOnly = await prisma.leito.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends LeitoCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, LeitoCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LeitoPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Leito.
   * @param {LeitoDeleteArgs} args - Arguments to delete one Leito.
   * @example
   * // Delete one Leito
   * const Leito = await prisma.leito.delete({
   *   where: {
   *     // ... filter to delete one Leito
   *   }
   * })
   * 
   */
  delete<T extends LeitoDeleteArgs>(args: Prisma.SelectSubset<T, LeitoDeleteArgs<ExtArgs>>): Prisma.Prisma__LeitoClient<runtime.Types.Result.GetResult<Prisma.$LeitoPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Leito.
   * @param {LeitoUpdateArgs} args - Arguments to update one Leito.
   * @example
   * // Update one Leito
   * const leito = await prisma.leito.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends LeitoUpdateArgs>(args: Prisma.SelectSubset<T, LeitoUpdateArgs<ExtArgs>>): Prisma.Prisma__LeitoClient<runtime.Types.Result.GetResult<Prisma.$LeitoPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Leitos.
   * @param {LeitoDeleteManyArgs} args - Arguments to filter Leitos to delete.
   * @example
   * // Delete a few Leitos
   * const { count } = await prisma.leito.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends LeitoDeleteManyArgs>(args?: Prisma.SelectSubset<T, LeitoDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Leitos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeitoUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Leitos
   * const leito = await prisma.leito.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends LeitoUpdateManyArgs>(args: Prisma.SelectSubset<T, LeitoUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Leitos and returns the data updated in the database.
   * @param {LeitoUpdateManyAndReturnArgs} args - Arguments to update many Leitos.
   * @example
   * // Update many Leitos
   * const leito = await prisma.leito.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Leitos and only return the `id`
   * const leitoWithIdOnly = await prisma.leito.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends LeitoUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, LeitoUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LeitoPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Leito.
   * @param {LeitoUpsertArgs} args - Arguments to update or create a Leito.
   * @example
   * // Update or create a Leito
   * const leito = await prisma.leito.upsert({
   *   create: {
   *     // ... data to create a Leito
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Leito we want to update
   *   }
   * })
   */
  upsert<T extends LeitoUpsertArgs>(args: Prisma.SelectSubset<T, LeitoUpsertArgs<ExtArgs>>): Prisma.Prisma__LeitoClient<runtime.Types.Result.GetResult<Prisma.$LeitoPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Leitos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeitoCountArgs} args - Arguments to filter Leitos to count.
   * @example
   * // Count the number of Leitos
   * const count = await prisma.leito.count({
   *   where: {
   *     // ... the filter for the Leitos we want to count
   *   }
   * })
  **/
  count<T extends LeitoCountArgs>(
    args?: Prisma.Subset<T, LeitoCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], LeitoCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Leito.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeitoAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends LeitoAggregateArgs>(args: Prisma.Subset<T, LeitoAggregateArgs>): Prisma.PrismaPromise<GetLeitoAggregateType<T>>

  /**
   * Group by Leito.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeitoGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends LeitoGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: LeitoGroupByArgs['orderBy'] }
      : { orderBy?: LeitoGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, LeitoGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetLeitoGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Leito model
 */
readonly fields: LeitoFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Leito.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__LeitoClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  unidade<T extends Prisma.UnidadeHospitalarDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UnidadeHospitalarDefaultArgs<ExtArgs>>): Prisma.Prisma__UnidadeHospitalarClient<runtime.Types.Result.GetResult<Prisma.$UnidadeHospitalarPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Leito model
 */
export interface LeitoFieldRefs {
  readonly id: Prisma.FieldRef<"Leito", 'String'>
  readonly unidadeId: Prisma.FieldRef<"Leito", 'String'>
  readonly numero: Prisma.FieldRef<"Leito", 'String'>
  readonly tipo: Prisma.FieldRef<"Leito", 'String'>
  readonly status: Prisma.FieldRef<"Leito", 'StatusLeito'>
  readonly createdAt: Prisma.FieldRef<"Leito", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Leito", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Leito findUnique
 */
export type LeitoFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Leito
   */
  select?: Prisma.LeitoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Leito
   */
  omit?: Prisma.LeitoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeitoInclude<ExtArgs> | null
  /**
   * Filter, which Leito to fetch.
   */
  where: Prisma.LeitoWhereUniqueInput
}

/**
 * Leito findUniqueOrThrow
 */
export type LeitoFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Leito
   */
  select?: Prisma.LeitoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Leito
   */
  omit?: Prisma.LeitoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeitoInclude<ExtArgs> | null
  /**
   * Filter, which Leito to fetch.
   */
  where: Prisma.LeitoWhereUniqueInput
}

/**
 * Leito findFirst
 */
export type LeitoFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Leito
   */
  select?: Prisma.LeitoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Leito
   */
  omit?: Prisma.LeitoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeitoInclude<ExtArgs> | null
  /**
   * Filter, which Leito to fetch.
   */
  where?: Prisma.LeitoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Leitos to fetch.
   */
  orderBy?: Prisma.LeitoOrderByWithRelationInput | Prisma.LeitoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Leitos.
   */
  cursor?: Prisma.LeitoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Leitos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Leitos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Leitos.
   */
  distinct?: Prisma.LeitoScalarFieldEnum | Prisma.LeitoScalarFieldEnum[]
}

/**
 * Leito findFirstOrThrow
 */
export type LeitoFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Leito
   */
  select?: Prisma.LeitoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Leito
   */
  omit?: Prisma.LeitoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeitoInclude<ExtArgs> | null
  /**
   * Filter, which Leito to fetch.
   */
  where?: Prisma.LeitoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Leitos to fetch.
   */
  orderBy?: Prisma.LeitoOrderByWithRelationInput | Prisma.LeitoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Leitos.
   */
  cursor?: Prisma.LeitoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Leitos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Leitos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Leitos.
   */
  distinct?: Prisma.LeitoScalarFieldEnum | Prisma.LeitoScalarFieldEnum[]
}

/**
 * Leito findMany
 */
export type LeitoFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Leito
   */
  select?: Prisma.LeitoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Leito
   */
  omit?: Prisma.LeitoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeitoInclude<ExtArgs> | null
  /**
   * Filter, which Leitos to fetch.
   */
  where?: Prisma.LeitoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Leitos to fetch.
   */
  orderBy?: Prisma.LeitoOrderByWithRelationInput | Prisma.LeitoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Leitos.
   */
  cursor?: Prisma.LeitoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Leitos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Leitos.
   */
  skip?: number
  distinct?: Prisma.LeitoScalarFieldEnum | Prisma.LeitoScalarFieldEnum[]
}

/**
 * Leito create
 */
export type LeitoCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Leito
   */
  select?: Prisma.LeitoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Leito
   */
  omit?: Prisma.LeitoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeitoInclude<ExtArgs> | null
  /**
   * The data needed to create a Leito.
   */
  data: Prisma.XOR<Prisma.LeitoCreateInput, Prisma.LeitoUncheckedCreateInput>
}

/**
 * Leito createMany
 */
export type LeitoCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Leitos.
   */
  data: Prisma.LeitoCreateManyInput | Prisma.LeitoCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Leito createManyAndReturn
 */
export type LeitoCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Leito
   */
  select?: Prisma.LeitoSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Leito
   */
  omit?: Prisma.LeitoOmit<ExtArgs> | null
  /**
   * The data used to create many Leitos.
   */
  data: Prisma.LeitoCreateManyInput | Prisma.LeitoCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeitoIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Leito update
 */
export type LeitoUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Leito
   */
  select?: Prisma.LeitoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Leito
   */
  omit?: Prisma.LeitoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeitoInclude<ExtArgs> | null
  /**
   * The data needed to update a Leito.
   */
  data: Prisma.XOR<Prisma.LeitoUpdateInput, Prisma.LeitoUncheckedUpdateInput>
  /**
   * Choose, which Leito to update.
   */
  where: Prisma.LeitoWhereUniqueInput
}

/**
 * Leito updateMany
 */
export type LeitoUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Leitos.
   */
  data: Prisma.XOR<Prisma.LeitoUpdateManyMutationInput, Prisma.LeitoUncheckedUpdateManyInput>
  /**
   * Filter which Leitos to update
   */
  where?: Prisma.LeitoWhereInput
  /**
   * Limit how many Leitos to update.
   */
  limit?: number
}

/**
 * Leito updateManyAndReturn
 */
export type LeitoUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Leito
   */
  select?: Prisma.LeitoSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Leito
   */
  omit?: Prisma.LeitoOmit<ExtArgs> | null
  /**
   * The data used to update Leitos.
   */
  data: Prisma.XOR<Prisma.LeitoUpdateManyMutationInput, Prisma.LeitoUncheckedUpdateManyInput>
  /**
   * Filter which Leitos to update
   */
  where?: Prisma.LeitoWhereInput
  /**
   * Limit how many Leitos to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeitoIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Leito upsert
 */
export type LeitoUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Leito
   */
  select?: Prisma.LeitoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Leito
   */
  omit?: Prisma.LeitoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeitoInclude<ExtArgs> | null
  /**
   * The filter to search for the Leito to update in case it exists.
   */
  where: Prisma.LeitoWhereUniqueInput
  /**
   * In case the Leito found by the `where` argument doesn't exist, create a new Leito with this data.
   */
  create: Prisma.XOR<Prisma.LeitoCreateInput, Prisma.LeitoUncheckedCreateInput>
  /**
   * In case the Leito was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.LeitoUpdateInput, Prisma.LeitoUncheckedUpdateInput>
}

/**
 * Leito delete
 */
export type LeitoDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Leito
   */
  select?: Prisma.LeitoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Leito
   */
  omit?: Prisma.LeitoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeitoInclude<ExtArgs> | null
  /**
   * Filter which Leito to delete.
   */
  where: Prisma.LeitoWhereUniqueInput
}

/**
 * Leito deleteMany
 */
export type LeitoDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Leitos to delete
   */
  where?: Prisma.LeitoWhereInput
  /**
   * Limit how many Leitos to delete.
   */
  limit?: number
}

/**
 * Leito without action
 */
export type LeitoDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Leito
   */
  select?: Prisma.LeitoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Leito
   */
  omit?: Prisma.LeitoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeitoInclude<ExtArgs> | null
}
