
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Paciente` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Paciente
 * 
 */
export type PacienteModel = runtime.Types.Result.DefaultSelection<Prisma.$PacientePayload>

export type AggregatePaciente = {
  _count: PacienteCountAggregateOutputType | null
  _min: PacienteMinAggregateOutputType | null
  _max: PacienteMaxAggregateOutputType | null
}

export type PacienteMinAggregateOutputType = {
  id: string | null
  usuarioId: string | null
  nome: string | null
  cpf: string | null
  dataNasc: Date | null
  telefone: string | null
  endereco: string | null
  sexo: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PacienteMaxAggregateOutputType = {
  id: string | null
  usuarioId: string | null
  nome: string | null
  cpf: string | null
  dataNasc: Date | null
  telefone: string | null
  endereco: string | null
  sexo: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PacienteCountAggregateOutputType = {
  id: number
  usuarioId: number
  nome: number
  cpf: number
  dataNasc: number
  telefone: number
  endereco: number
  sexo: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type PacienteMinAggregateInputType = {
  id?: true
  usuarioId?: true
  nome?: true
  cpf?: true
  dataNasc?: true
  telefone?: true
  endereco?: true
  sexo?: true
  createdAt?: true
  updatedAt?: true
}

export type PacienteMaxAggregateInputType = {
  id?: true
  usuarioId?: true
  nome?: true
  cpf?: true
  dataNasc?: true
  telefone?: true
  endereco?: true
  sexo?: true
  createdAt?: true
  updatedAt?: true
}

export type PacienteCountAggregateInputType = {
  id?: true
  usuarioId?: true
  nome?: true
  cpf?: true
  dataNasc?: true
  telefone?: true
  endereco?: true
  sexo?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type PacienteAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Paciente to aggregate.
   */
  where?: Prisma.PacienteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Pacientes to fetch.
   */
  orderBy?: Prisma.PacienteOrderByWithRelationInput | Prisma.PacienteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PacienteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Pacientes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Pacientes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Pacientes
  **/
  _count?: true | PacienteCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PacienteMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PacienteMaxAggregateInputType
}

export type GetPacienteAggregateType<T extends PacienteAggregateArgs> = {
      [P in keyof T & keyof AggregatePaciente]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePaciente[P]>
    : Prisma.GetScalarType<T[P], AggregatePaciente[P]>
}




export type PacienteGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PacienteWhereInput
  orderBy?: Prisma.PacienteOrderByWithAggregationInput | Prisma.PacienteOrderByWithAggregationInput[]
  by: Prisma.PacienteScalarFieldEnum[] | Prisma.PacienteScalarFieldEnum
  having?: Prisma.PacienteScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PacienteCountAggregateInputType | true
  _min?: PacienteMinAggregateInputType
  _max?: PacienteMaxAggregateInputType
}

export type PacienteGroupByOutputType = {
  id: string
  usuarioId: string
  nome: string
  cpf: string
  dataNasc: Date
  telefone: string
  endereco: string
  sexo: string | null
  createdAt: Date
  updatedAt: Date
  _count: PacienteCountAggregateOutputType | null
  _min: PacienteMinAggregateOutputType | null
  _max: PacienteMaxAggregateOutputType | null
}

type GetPacienteGroupByPayload<T extends PacienteGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PacienteGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PacienteGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PacienteGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PacienteGroupByOutputType[P]>
      }
    >
  >



export type PacienteWhereInput = {
  AND?: Prisma.PacienteWhereInput | Prisma.PacienteWhereInput[]
  OR?: Prisma.PacienteWhereInput[]
  NOT?: Prisma.PacienteWhereInput | Prisma.PacienteWhereInput[]
  id?: Prisma.StringFilter<"Paciente"> | string
  usuarioId?: Prisma.StringFilter<"Paciente"> | string
  nome?: Prisma.StringFilter<"Paciente"> | string
  cpf?: Prisma.StringFilter<"Paciente"> | string
  dataNasc?: Prisma.DateTimeFilter<"Paciente"> | Date | string
  telefone?: Prisma.StringFilter<"Paciente"> | string
  endereco?: Prisma.StringFilter<"Paciente"> | string
  sexo?: Prisma.StringNullableFilter<"Paciente"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Paciente"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Paciente"> | Date | string
  usuario?: Prisma.XOR<Prisma.UsuarioScalarRelationFilter, Prisma.UsuarioWhereInput>
  consultas?: Prisma.ConsultaListRelationFilter
  prontuarios?: Prisma.ProntuarioListRelationFilter
  notificacoes?: Prisma.NotificacaoListRelationFilter
}

export type PacienteOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  usuarioId?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  cpf?: Prisma.SortOrder
  dataNasc?: Prisma.SortOrder
  telefone?: Prisma.SortOrder
  endereco?: Prisma.SortOrder
  sexo?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  usuario?: Prisma.UsuarioOrderByWithRelationInput
  consultas?: Prisma.ConsultaOrderByRelationAggregateInput
  prontuarios?: Prisma.ProntuarioOrderByRelationAggregateInput
  notificacoes?: Prisma.NotificacaoOrderByRelationAggregateInput
}

export type PacienteWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  usuarioId?: string
  cpf?: string
  AND?: Prisma.PacienteWhereInput | Prisma.PacienteWhereInput[]
  OR?: Prisma.PacienteWhereInput[]
  NOT?: Prisma.PacienteWhereInput | Prisma.PacienteWhereInput[]
  nome?: Prisma.StringFilter<"Paciente"> | string
  dataNasc?: Prisma.DateTimeFilter<"Paciente"> | Date | string
  telefone?: Prisma.StringFilter<"Paciente"> | string
  endereco?: Prisma.StringFilter<"Paciente"> | string
  sexo?: Prisma.StringNullableFilter<"Paciente"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Paciente"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Paciente"> | Date | string
  usuario?: Prisma.XOR<Prisma.UsuarioScalarRelationFilter, Prisma.UsuarioWhereInput>
  consultas?: Prisma.ConsultaListRelationFilter
  prontuarios?: Prisma.ProntuarioListRelationFilter
  notificacoes?: Prisma.NotificacaoListRelationFilter
}, "id" | "usuarioId" | "cpf">

export type PacienteOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  usuarioId?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  cpf?: Prisma.SortOrder
  dataNasc?: Prisma.SortOrder
  telefone?: Prisma.SortOrder
  endereco?: Prisma.SortOrder
  sexo?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PacienteCountOrderByAggregateInput
  _max?: Prisma.PacienteMaxOrderByAggregateInput
  _min?: Prisma.PacienteMinOrderByAggregateInput
}

export type PacienteScalarWhereWithAggregatesInput = {
  AND?: Prisma.PacienteScalarWhereWithAggregatesInput | Prisma.PacienteScalarWhereWithAggregatesInput[]
  OR?: Prisma.PacienteScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PacienteScalarWhereWithAggregatesInput | Prisma.PacienteScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Paciente"> | string
  usuarioId?: Prisma.StringWithAggregatesFilter<"Paciente"> | string
  nome?: Prisma.StringWithAggregatesFilter<"Paciente"> | string
  cpf?: Prisma.StringWithAggregatesFilter<"Paciente"> | string
  dataNasc?: Prisma.DateTimeWithAggregatesFilter<"Paciente"> | Date | string
  telefone?: Prisma.StringWithAggregatesFilter<"Paciente"> | string
  endereco?: Prisma.StringWithAggregatesFilter<"Paciente"> | string
  sexo?: Prisma.StringNullableWithAggregatesFilter<"Paciente"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Paciente"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Paciente"> | Date | string
}

export type PacienteCreateInput = {
  id?: string
  nome: string
  cpf: string
  dataNasc: Date | string
  telefone: string
  endereco: string
  sexo?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  usuario: Prisma.UsuarioCreateNestedOneWithoutPacienteInput
  consultas?: Prisma.ConsultaCreateNestedManyWithoutPacienteInput
  prontuarios?: Prisma.ProntuarioCreateNestedManyWithoutPacienteInput
  notificacoes?: Prisma.NotificacaoCreateNestedManyWithoutPacienteInput
}

export type PacienteUncheckedCreateInput = {
  id?: string
  usuarioId: string
  nome: string
  cpf: string
  dataNasc: Date | string
  telefone: string
  endereco: string
  sexo?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  consultas?: Prisma.ConsultaUncheckedCreateNestedManyWithoutPacienteInput
  prontuarios?: Prisma.ProntuarioUncheckedCreateNestedManyWithoutPacienteInput
  notificacoes?: Prisma.NotificacaoUncheckedCreateNestedManyWithoutPacienteInput
}

export type PacienteUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  cpf?: Prisma.StringFieldUpdateOperationsInput | string
  dataNasc?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  telefone?: Prisma.StringFieldUpdateOperationsInput | string
  endereco?: Prisma.StringFieldUpdateOperationsInput | string
  sexo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usuario?: Prisma.UsuarioUpdateOneRequiredWithoutPacienteNestedInput
  consultas?: Prisma.ConsultaUpdateManyWithoutPacienteNestedInput
  prontuarios?: Prisma.ProntuarioUpdateManyWithoutPacienteNestedInput
  notificacoes?: Prisma.NotificacaoUpdateManyWithoutPacienteNestedInput
}

export type PacienteUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  usuarioId?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  cpf?: Prisma.StringFieldUpdateOperationsInput | string
  dataNasc?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  telefone?: Prisma.StringFieldUpdateOperationsInput | string
  endereco?: Prisma.StringFieldUpdateOperationsInput | string
  sexo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  consultas?: Prisma.ConsultaUncheckedUpdateManyWithoutPacienteNestedInput
  prontuarios?: Prisma.ProntuarioUncheckedUpdateManyWithoutPacienteNestedInput
  notificacoes?: Prisma.NotificacaoUncheckedUpdateManyWithoutPacienteNestedInput
}

export type PacienteCreateManyInput = {
  id?: string
  usuarioId: string
  nome: string
  cpf: string
  dataNasc: Date | string
  telefone: string
  endereco: string
  sexo?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PacienteUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  cpf?: Prisma.StringFieldUpdateOperationsInput | string
  dataNasc?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  telefone?: Prisma.StringFieldUpdateOperationsInput | string
  endereco?: Prisma.StringFieldUpdateOperationsInput | string
  sexo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PacienteUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  usuarioId?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  cpf?: Prisma.StringFieldUpdateOperationsInput | string
  dataNasc?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  telefone?: Prisma.StringFieldUpdateOperationsInput | string
  endereco?: Prisma.StringFieldUpdateOperationsInput | string
  sexo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PacienteNullableScalarRelationFilter = {
  is?: Prisma.PacienteWhereInput | null
  isNot?: Prisma.PacienteWhereInput | null
}

export type PacienteCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  usuarioId?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  cpf?: Prisma.SortOrder
  dataNasc?: Prisma.SortOrder
  telefone?: Prisma.SortOrder
  endereco?: Prisma.SortOrder
  sexo?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PacienteMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  usuarioId?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  cpf?: Prisma.SortOrder
  dataNasc?: Prisma.SortOrder
  telefone?: Prisma.SortOrder
  endereco?: Prisma.SortOrder
  sexo?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PacienteMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  usuarioId?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  cpf?: Prisma.SortOrder
  dataNasc?: Prisma.SortOrder
  telefone?: Prisma.SortOrder
  endereco?: Prisma.SortOrder
  sexo?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PacienteScalarRelationFilter = {
  is?: Prisma.PacienteWhereInput
  isNot?: Prisma.PacienteWhereInput
}

export type PacienteCreateNestedOneWithoutUsuarioInput = {
  create?: Prisma.XOR<Prisma.PacienteCreateWithoutUsuarioInput, Prisma.PacienteUncheckedCreateWithoutUsuarioInput>
  connectOrCreate?: Prisma.PacienteCreateOrConnectWithoutUsuarioInput
  connect?: Prisma.PacienteWhereUniqueInput
}

export type PacienteUncheckedCreateNestedOneWithoutUsuarioInput = {
  create?: Prisma.XOR<Prisma.PacienteCreateWithoutUsuarioInput, Prisma.PacienteUncheckedCreateWithoutUsuarioInput>
  connectOrCreate?: Prisma.PacienteCreateOrConnectWithoutUsuarioInput
  connect?: Prisma.PacienteWhereUniqueInput
}

export type PacienteUpdateOneWithoutUsuarioNestedInput = {
  create?: Prisma.XOR<Prisma.PacienteCreateWithoutUsuarioInput, Prisma.PacienteUncheckedCreateWithoutUsuarioInput>
  connectOrCreate?: Prisma.PacienteCreateOrConnectWithoutUsuarioInput
  upsert?: Prisma.PacienteUpsertWithoutUsuarioInput
  disconnect?: Prisma.PacienteWhereInput | boolean
  delete?: Prisma.PacienteWhereInput | boolean
  connect?: Prisma.PacienteWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PacienteUpdateToOneWithWhereWithoutUsuarioInput, Prisma.PacienteUpdateWithoutUsuarioInput>, Prisma.PacienteUncheckedUpdateWithoutUsuarioInput>
}

export type PacienteUncheckedUpdateOneWithoutUsuarioNestedInput = {
  create?: Prisma.XOR<Prisma.PacienteCreateWithoutUsuarioInput, Prisma.PacienteUncheckedCreateWithoutUsuarioInput>
  connectOrCreate?: Prisma.PacienteCreateOrConnectWithoutUsuarioInput
  upsert?: Prisma.PacienteUpsertWithoutUsuarioInput
  disconnect?: Prisma.PacienteWhereInput | boolean
  delete?: Prisma.PacienteWhereInput | boolean
  connect?: Prisma.PacienteWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PacienteUpdateToOneWithWhereWithoutUsuarioInput, Prisma.PacienteUpdateWithoutUsuarioInput>, Prisma.PacienteUncheckedUpdateWithoutUsuarioInput>
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type PacienteCreateNestedOneWithoutConsultasInput = {
  create?: Prisma.XOR<Prisma.PacienteCreateWithoutConsultasInput, Prisma.PacienteUncheckedCreateWithoutConsultasInput>
  connectOrCreate?: Prisma.PacienteCreateOrConnectWithoutConsultasInput
  connect?: Prisma.PacienteWhereUniqueInput
}

export type PacienteUpdateOneRequiredWithoutConsultasNestedInput = {
  create?: Prisma.XOR<Prisma.PacienteCreateWithoutConsultasInput, Prisma.PacienteUncheckedCreateWithoutConsultasInput>
  connectOrCreate?: Prisma.PacienteCreateOrConnectWithoutConsultasInput
  upsert?: Prisma.PacienteUpsertWithoutConsultasInput
  connect?: Prisma.PacienteWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PacienteUpdateToOneWithWhereWithoutConsultasInput, Prisma.PacienteUpdateWithoutConsultasInput>, Prisma.PacienteUncheckedUpdateWithoutConsultasInput>
}

export type PacienteCreateNestedOneWithoutProntuariosInput = {
  create?: Prisma.XOR<Prisma.PacienteCreateWithoutProntuariosInput, Prisma.PacienteUncheckedCreateWithoutProntuariosInput>
  connectOrCreate?: Prisma.PacienteCreateOrConnectWithoutProntuariosInput
  connect?: Prisma.PacienteWhereUniqueInput
}

export type PacienteUpdateOneRequiredWithoutProntuariosNestedInput = {
  create?: Prisma.XOR<Prisma.PacienteCreateWithoutProntuariosInput, Prisma.PacienteUncheckedCreateWithoutProntuariosInput>
  connectOrCreate?: Prisma.PacienteCreateOrConnectWithoutProntuariosInput
  upsert?: Prisma.PacienteUpsertWithoutProntuariosInput
  connect?: Prisma.PacienteWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PacienteUpdateToOneWithWhereWithoutProntuariosInput, Prisma.PacienteUpdateWithoutProntuariosInput>, Prisma.PacienteUncheckedUpdateWithoutProntuariosInput>
}

export type PacienteCreateNestedOneWithoutNotificacoesInput = {
  create?: Prisma.XOR<Prisma.PacienteCreateWithoutNotificacoesInput, Prisma.PacienteUncheckedCreateWithoutNotificacoesInput>
  connectOrCreate?: Prisma.PacienteCreateOrConnectWithoutNotificacoesInput
  connect?: Prisma.PacienteWhereUniqueInput
}

export type PacienteUpdateOneRequiredWithoutNotificacoesNestedInput = {
  create?: Prisma.XOR<Prisma.PacienteCreateWithoutNotificacoesInput, Prisma.PacienteUncheckedCreateWithoutNotificacoesInput>
  connectOrCreate?: Prisma.PacienteCreateOrConnectWithoutNotificacoesInput
  upsert?: Prisma.PacienteUpsertWithoutNotificacoesInput
  connect?: Prisma.PacienteWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PacienteUpdateToOneWithWhereWithoutNotificacoesInput, Prisma.PacienteUpdateWithoutNotificacoesInput>, Prisma.PacienteUncheckedUpdateWithoutNotificacoesInput>
}

export type PacienteCreateWithoutUsuarioInput = {
  id?: string
  nome: string
  cpf: string
  dataNasc: Date | string
  telefone: string
  endereco: string
  sexo?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  consultas?: Prisma.ConsultaCreateNestedManyWithoutPacienteInput
  prontuarios?: Prisma.ProntuarioCreateNestedManyWithoutPacienteInput
  notificacoes?: Prisma.NotificacaoCreateNestedManyWithoutPacienteInput
}

export type PacienteUncheckedCreateWithoutUsuarioInput = {
  id?: string
  nome: string
  cpf: string
  dataNasc: Date | string
  telefone: string
  endereco: string
  sexo?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  consultas?: Prisma.ConsultaUncheckedCreateNestedManyWithoutPacienteInput
  prontuarios?: Prisma.ProntuarioUncheckedCreateNestedManyWithoutPacienteInput
  notificacoes?: Prisma.NotificacaoUncheckedCreateNestedManyWithoutPacienteInput
}

export type PacienteCreateOrConnectWithoutUsuarioInput = {
  where: Prisma.PacienteWhereUniqueInput
  create: Prisma.XOR<Prisma.PacienteCreateWithoutUsuarioInput, Prisma.PacienteUncheckedCreateWithoutUsuarioInput>
}

export type PacienteUpsertWithoutUsuarioInput = {
  update: Prisma.XOR<Prisma.PacienteUpdateWithoutUsuarioInput, Prisma.PacienteUncheckedUpdateWithoutUsuarioInput>
  create: Prisma.XOR<Prisma.PacienteCreateWithoutUsuarioInput, Prisma.PacienteUncheckedCreateWithoutUsuarioInput>
  where?: Prisma.PacienteWhereInput
}

export type PacienteUpdateToOneWithWhereWithoutUsuarioInput = {
  where?: Prisma.PacienteWhereInput
  data: Prisma.XOR<Prisma.PacienteUpdateWithoutUsuarioInput, Prisma.PacienteUncheckedUpdateWithoutUsuarioInput>
}

export type PacienteUpdateWithoutUsuarioInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  cpf?: Prisma.StringFieldUpdateOperationsInput | string
  dataNasc?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  telefone?: Prisma.StringFieldUpdateOperationsInput | string
  endereco?: Prisma.StringFieldUpdateOperationsInput | string
  sexo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  consultas?: Prisma.ConsultaUpdateManyWithoutPacienteNestedInput
  prontuarios?: Prisma.ProntuarioUpdateManyWithoutPacienteNestedInput
  notificacoes?: Prisma.NotificacaoUpdateManyWithoutPacienteNestedInput
}

export type PacienteUncheckedUpdateWithoutUsuarioInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  cpf?: Prisma.StringFieldUpdateOperationsInput | string
  dataNasc?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  telefone?: Prisma.StringFieldUpdateOperationsInput | string
  endereco?: Prisma.StringFieldUpdateOperationsInput | string
  sexo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  consultas?: Prisma.ConsultaUncheckedUpdateManyWithoutPacienteNestedInput
  prontuarios?: Prisma.ProntuarioUncheckedUpdateManyWithoutPacienteNestedInput
  notificacoes?: Prisma.NotificacaoUncheckedUpdateManyWithoutPacienteNestedInput
}

export type PacienteCreateWithoutConsultasInput = {
  id?: string
  nome: string
  cpf: string
  dataNasc: Date | string
  telefone: string
  endereco: string
  sexo?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  usuario: Prisma.UsuarioCreateNestedOneWithoutPacienteInput
  prontuarios?: Prisma.ProntuarioCreateNestedManyWithoutPacienteInput
  notificacoes?: Prisma.NotificacaoCreateNestedManyWithoutPacienteInput
}

export type PacienteUncheckedCreateWithoutConsultasInput = {
  id?: string
  usuarioId: string
  nome: string
  cpf: string
  dataNasc: Date | string
  telefone: string
  endereco: string
  sexo?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  prontuarios?: Prisma.ProntuarioUncheckedCreateNestedManyWithoutPacienteInput
  notificacoes?: Prisma.NotificacaoUncheckedCreateNestedManyWithoutPacienteInput
}

export type PacienteCreateOrConnectWithoutConsultasInput = {
  where: Prisma.PacienteWhereUniqueInput
  create: Prisma.XOR<Prisma.PacienteCreateWithoutConsultasInput, Prisma.PacienteUncheckedCreateWithoutConsultasInput>
}

export type PacienteUpsertWithoutConsultasInput = {
  update: Prisma.XOR<Prisma.PacienteUpdateWithoutConsultasInput, Prisma.PacienteUncheckedUpdateWithoutConsultasInput>
  create: Prisma.XOR<Prisma.PacienteCreateWithoutConsultasInput, Prisma.PacienteUncheckedCreateWithoutConsultasInput>
  where?: Prisma.PacienteWhereInput
}

export type PacienteUpdateToOneWithWhereWithoutConsultasInput = {
  where?: Prisma.PacienteWhereInput
  data: Prisma.XOR<Prisma.PacienteUpdateWithoutConsultasInput, Prisma.PacienteUncheckedUpdateWithoutConsultasInput>
}

export type PacienteUpdateWithoutConsultasInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  cpf?: Prisma.StringFieldUpdateOperationsInput | string
  dataNasc?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  telefone?: Prisma.StringFieldUpdateOperationsInput | string
  endereco?: Prisma.StringFieldUpdateOperationsInput | string
  sexo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usuario?: Prisma.UsuarioUpdateOneRequiredWithoutPacienteNestedInput
  prontuarios?: Prisma.ProntuarioUpdateManyWithoutPacienteNestedInput
  notificacoes?: Prisma.NotificacaoUpdateManyWithoutPacienteNestedInput
}

export type PacienteUncheckedUpdateWithoutConsultasInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  usuarioId?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  cpf?: Prisma.StringFieldUpdateOperationsInput | string
  dataNasc?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  telefone?: Prisma.StringFieldUpdateOperationsInput | string
  endereco?: Prisma.StringFieldUpdateOperationsInput | string
  sexo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  prontuarios?: Prisma.ProntuarioUncheckedUpdateManyWithoutPacienteNestedInput
  notificacoes?: Prisma.NotificacaoUncheckedUpdateManyWithoutPacienteNestedInput
}

export type PacienteCreateWithoutProntuariosInput = {
  id?: string
  nome: string
  cpf: string
  dataNasc: Date | string
  telefone: string
  endereco: string
  sexo?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  usuario: Prisma.UsuarioCreateNestedOneWithoutPacienteInput
  consultas?: Prisma.ConsultaCreateNestedManyWithoutPacienteInput
  notificacoes?: Prisma.NotificacaoCreateNestedManyWithoutPacienteInput
}

export type PacienteUncheckedCreateWithoutProntuariosInput = {
  id?: string
  usuarioId: string
  nome: string
  cpf: string
  dataNasc: Date | string
  telefone: string
  endereco: string
  sexo?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  consultas?: Prisma.ConsultaUncheckedCreateNestedManyWithoutPacienteInput
  notificacoes?: Prisma.NotificacaoUncheckedCreateNestedManyWithoutPacienteInput
}

export type PacienteCreateOrConnectWithoutProntuariosInput = {
  where: Prisma.PacienteWhereUniqueInput
  create: Prisma.XOR<Prisma.PacienteCreateWithoutProntuariosInput, Prisma.PacienteUncheckedCreateWithoutProntuariosInput>
}

export type PacienteUpsertWithoutProntuariosInput = {
  update: Prisma.XOR<Prisma.PacienteUpdateWithoutProntuariosInput, Prisma.PacienteUncheckedUpdateWithoutProntuariosInput>
  create: Prisma.XOR<Prisma.PacienteCreateWithoutProntuariosInput, Prisma.PacienteUncheckedCreateWithoutProntuariosInput>
  where?: Prisma.PacienteWhereInput
}

export type PacienteUpdateToOneWithWhereWithoutProntuariosInput = {
  where?: Prisma.PacienteWhereInput
  data: Prisma.XOR<Prisma.PacienteUpdateWithoutProntuariosInput, Prisma.PacienteUncheckedUpdateWithoutProntuariosInput>
}

export type PacienteUpdateWithoutProntuariosInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  cpf?: Prisma.StringFieldUpdateOperationsInput | string
  dataNasc?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  telefone?: Prisma.StringFieldUpdateOperationsInput | string
  endereco?: Prisma.StringFieldUpdateOperationsInput | string
  sexo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usuario?: Prisma.UsuarioUpdateOneRequiredWithoutPacienteNestedInput
  consultas?: Prisma.ConsultaUpdateManyWithoutPacienteNestedInput
  notificacoes?: Prisma.NotificacaoUpdateManyWithoutPacienteNestedInput
}

export type PacienteUncheckedUpdateWithoutProntuariosInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  usuarioId?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  cpf?: Prisma.StringFieldUpdateOperationsInput | string
  dataNasc?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  telefone?: Prisma.StringFieldUpdateOperationsInput | string
  endereco?: Prisma.StringFieldUpdateOperationsInput | string
  sexo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  consultas?: Prisma.ConsultaUncheckedUpdateManyWithoutPacienteNestedInput
  notificacoes?: Prisma.NotificacaoUncheckedUpdateManyWithoutPacienteNestedInput
}

export type PacienteCreateWithoutNotificacoesInput = {
  id?: string
  nome: string
  cpf: string
  dataNasc: Date | string
  telefone: string
  endereco: string
  sexo?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  usuario: Prisma.UsuarioCreateNestedOneWithoutPacienteInput
  consultas?: Prisma.ConsultaCreateNestedManyWithoutPacienteInput
  prontuarios?: Prisma.ProntuarioCreateNestedManyWithoutPacienteInput
}

export type PacienteUncheckedCreateWithoutNotificacoesInput = {
  id?: string
  usuarioId: string
  nome: string
  cpf: string
  dataNasc: Date | string
  telefone: string
  endereco: string
  sexo?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  consultas?: Prisma.ConsultaUncheckedCreateNestedManyWithoutPacienteInput
  prontuarios?: Prisma.ProntuarioUncheckedCreateNestedManyWithoutPacienteInput
}

export type PacienteCreateOrConnectWithoutNotificacoesInput = {
  where: Prisma.PacienteWhereUniqueInput
  create: Prisma.XOR<Prisma.PacienteCreateWithoutNotificacoesInput, Prisma.PacienteUncheckedCreateWithoutNotificacoesInput>
}

export type PacienteUpsertWithoutNotificacoesInput = {
  update: Prisma.XOR<Prisma.PacienteUpdateWithoutNotificacoesInput, Prisma.PacienteUncheckedUpdateWithoutNotificacoesInput>
  create: Prisma.XOR<Prisma.PacienteCreateWithoutNotificacoesInput, Prisma.PacienteUncheckedCreateWithoutNotificacoesInput>
  where?: Prisma.PacienteWhereInput
}

export type PacienteUpdateToOneWithWhereWithoutNotificacoesInput = {
  where?: Prisma.PacienteWhereInput
  data: Prisma.XOR<Prisma.PacienteUpdateWithoutNotificacoesInput, Prisma.PacienteUncheckedUpdateWithoutNotificacoesInput>
}

export type PacienteUpdateWithoutNotificacoesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  cpf?: Prisma.StringFieldUpdateOperationsInput | string
  dataNasc?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  telefone?: Prisma.StringFieldUpdateOperationsInput | string
  endereco?: Prisma.StringFieldUpdateOperationsInput | string
  sexo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usuario?: Prisma.UsuarioUpdateOneRequiredWithoutPacienteNestedInput
  consultas?: Prisma.ConsultaUpdateManyWithoutPacienteNestedInput
  prontuarios?: Prisma.ProntuarioUpdateManyWithoutPacienteNestedInput
}

export type PacienteUncheckedUpdateWithoutNotificacoesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  usuarioId?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  cpf?: Prisma.StringFieldUpdateOperationsInput | string
  dataNasc?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  telefone?: Prisma.StringFieldUpdateOperationsInput | string
  endereco?: Prisma.StringFieldUpdateOperationsInput | string
  sexo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  consultas?: Prisma.ConsultaUncheckedUpdateManyWithoutPacienteNestedInput
  prontuarios?: Prisma.ProntuarioUncheckedUpdateManyWithoutPacienteNestedInput
}


/**
 * Count Type PacienteCountOutputType
 */

export type PacienteCountOutputType = {
  consultas: number
  prontuarios: number
  notificacoes: number
}

export type PacienteCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  consultas?: boolean | PacienteCountOutputTypeCountConsultasArgs
  prontuarios?: boolean | PacienteCountOutputTypeCountProntuariosArgs
  notificacoes?: boolean | PacienteCountOutputTypeCountNotificacoesArgs
}

/**
 * PacienteCountOutputType without action
 */
export type PacienteCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PacienteCountOutputType
   */
  select?: Prisma.PacienteCountOutputTypeSelect<ExtArgs> | null
}

/**
 * PacienteCountOutputType without action
 */
export type PacienteCountOutputTypeCountConsultasArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ConsultaWhereInput
}

/**
 * PacienteCountOutputType without action
 */
export type PacienteCountOutputTypeCountProntuariosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProntuarioWhereInput
}

/**
 * PacienteCountOutputType without action
 */
export type PacienteCountOutputTypeCountNotificacoesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.NotificacaoWhereInput
}


export type PacienteSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  usuarioId?: boolean
  nome?: boolean
  cpf?: boolean
  dataNasc?: boolean
  telefone?: boolean
  endereco?: boolean
  sexo?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  usuario?: boolean | Prisma.UsuarioDefaultArgs<ExtArgs>
  consultas?: boolean | Prisma.Paciente$consultasArgs<ExtArgs>
  prontuarios?: boolean | Prisma.Paciente$prontuariosArgs<ExtArgs>
  notificacoes?: boolean | Prisma.Paciente$notificacoesArgs<ExtArgs>
  _count?: boolean | Prisma.PacienteCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["paciente"]>

export type PacienteSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  usuarioId?: boolean
  nome?: boolean
  cpf?: boolean
  dataNasc?: boolean
  telefone?: boolean
  endereco?: boolean
  sexo?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  usuario?: boolean | Prisma.UsuarioDefaultArgs<ExtArgs>
}, ExtArgs["result"]["paciente"]>

export type PacienteSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  usuarioId?: boolean
  nome?: boolean
  cpf?: boolean
  dataNasc?: boolean
  telefone?: boolean
  endereco?: boolean
  sexo?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  usuario?: boolean | Prisma.UsuarioDefaultArgs<ExtArgs>
}, ExtArgs["result"]["paciente"]>

export type PacienteSelectScalar = {
  id?: boolean
  usuarioId?: boolean
  nome?: boolean
  cpf?: boolean
  dataNasc?: boolean
  telefone?: boolean
  endereco?: boolean
  sexo?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type PacienteOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "usuarioId" | "nome" | "cpf" | "dataNasc" | "telefone" | "endereco" | "sexo" | "createdAt" | "updatedAt", ExtArgs["result"]["paciente"]>
export type PacienteInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  usuario?: boolean | Prisma.UsuarioDefaultArgs<ExtArgs>
  consultas?: boolean | Prisma.Paciente$consultasArgs<ExtArgs>
  prontuarios?: boolean | Prisma.Paciente$prontuariosArgs<ExtArgs>
  notificacoes?: boolean | Prisma.Paciente$notificacoesArgs<ExtArgs>
  _count?: boolean | Prisma.PacienteCountOutputTypeDefaultArgs<ExtArgs>
}
export type PacienteIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  usuario?: boolean | Prisma.UsuarioDefaultArgs<ExtArgs>
}
export type PacienteIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  usuario?: boolean | Prisma.UsuarioDefaultArgs<ExtArgs>
}

export type $PacientePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Paciente"
  objects: {
    usuario: Prisma.$UsuarioPayload<ExtArgs>
    consultas: Prisma.$ConsultaPayload<ExtArgs>[]
    prontuarios: Prisma.$ProntuarioPayload<ExtArgs>[]
    notificacoes: Prisma.$NotificacaoPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    usuarioId: string
    nome: string
    cpf: string
    dataNasc: Date
    telefone: string
    endereco: string
    sexo: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["paciente"]>
  composites: {}
}

export type PacienteGetPayload<S extends boolean | null | undefined | PacienteDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PacientePayload, S>

export type PacienteCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PacienteFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PacienteCountAggregateInputType | true
  }

export interface PacienteDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Paciente'], meta: { name: 'Paciente' } }
  /**
   * Find zero or one Paciente that matches the filter.
   * @param {PacienteFindUniqueArgs} args - Arguments to find a Paciente
   * @example
   * // Get one Paciente
   * const paciente = await prisma.paciente.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PacienteFindUniqueArgs>(args: Prisma.SelectSubset<T, PacienteFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PacienteClient<runtime.Types.Result.GetResult<Prisma.$PacientePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Paciente that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PacienteFindUniqueOrThrowArgs} args - Arguments to find a Paciente
   * @example
   * // Get one Paciente
   * const paciente = await prisma.paciente.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PacienteFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PacienteFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PacienteClient<runtime.Types.Result.GetResult<Prisma.$PacientePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Paciente that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PacienteFindFirstArgs} args - Arguments to find a Paciente
   * @example
   * // Get one Paciente
   * const paciente = await prisma.paciente.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PacienteFindFirstArgs>(args?: Prisma.SelectSubset<T, PacienteFindFirstArgs<ExtArgs>>): Prisma.Prisma__PacienteClient<runtime.Types.Result.GetResult<Prisma.$PacientePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Paciente that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PacienteFindFirstOrThrowArgs} args - Arguments to find a Paciente
   * @example
   * // Get one Paciente
   * const paciente = await prisma.paciente.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PacienteFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PacienteFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PacienteClient<runtime.Types.Result.GetResult<Prisma.$PacientePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Pacientes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PacienteFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Pacientes
   * const pacientes = await prisma.paciente.findMany()
   * 
   * // Get first 10 Pacientes
   * const pacientes = await prisma.paciente.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const pacienteWithIdOnly = await prisma.paciente.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PacienteFindManyArgs>(args?: Prisma.SelectSubset<T, PacienteFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PacientePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Paciente.
   * @param {PacienteCreateArgs} args - Arguments to create a Paciente.
   * @example
   * // Create one Paciente
   * const Paciente = await prisma.paciente.create({
   *   data: {
   *     // ... data to create a Paciente
   *   }
   * })
   * 
   */
  create<T extends PacienteCreateArgs>(args: Prisma.SelectSubset<T, PacienteCreateArgs<ExtArgs>>): Prisma.Prisma__PacienteClient<runtime.Types.Result.GetResult<Prisma.$PacientePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Pacientes.
   * @param {PacienteCreateManyArgs} args - Arguments to create many Pacientes.
   * @example
   * // Create many Pacientes
   * const paciente = await prisma.paciente.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PacienteCreateManyArgs>(args?: Prisma.SelectSubset<T, PacienteCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Pacientes and returns the data saved in the database.
   * @param {PacienteCreateManyAndReturnArgs} args - Arguments to create many Pacientes.
   * @example
   * // Create many Pacientes
   * const paciente = await prisma.paciente.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Pacientes and only return the `id`
   * const pacienteWithIdOnly = await prisma.paciente.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PacienteCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PacienteCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PacientePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Paciente.
   * @param {PacienteDeleteArgs} args - Arguments to delete one Paciente.
   * @example
   * // Delete one Paciente
   * const Paciente = await prisma.paciente.delete({
   *   where: {
   *     // ... filter to delete one Paciente
   *   }
   * })
   * 
   */
  delete<T extends PacienteDeleteArgs>(args: Prisma.SelectSubset<T, PacienteDeleteArgs<ExtArgs>>): Prisma.Prisma__PacienteClient<runtime.Types.Result.GetResult<Prisma.$PacientePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Paciente.
   * @param {PacienteUpdateArgs} args - Arguments to update one Paciente.
   * @example
   * // Update one Paciente
   * const paciente = await prisma.paciente.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PacienteUpdateArgs>(args: Prisma.SelectSubset<T, PacienteUpdateArgs<ExtArgs>>): Prisma.Prisma__PacienteClient<runtime.Types.Result.GetResult<Prisma.$PacientePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Pacientes.
   * @param {PacienteDeleteManyArgs} args - Arguments to filter Pacientes to delete.
   * @example
   * // Delete a few Pacientes
   * const { count } = await prisma.paciente.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PacienteDeleteManyArgs>(args?: Prisma.SelectSubset<T, PacienteDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Pacientes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PacienteUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Pacientes
   * const paciente = await prisma.paciente.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PacienteUpdateManyArgs>(args: Prisma.SelectSubset<T, PacienteUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Pacientes and returns the data updated in the database.
   * @param {PacienteUpdateManyAndReturnArgs} args - Arguments to update many Pacientes.
   * @example
   * // Update many Pacientes
   * const paciente = await prisma.paciente.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Pacientes and only return the `id`
   * const pacienteWithIdOnly = await prisma.paciente.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PacienteUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PacienteUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PacientePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Paciente.
   * @param {PacienteUpsertArgs} args - Arguments to update or create a Paciente.
   * @example
   * // Update or create a Paciente
   * const paciente = await prisma.paciente.upsert({
   *   create: {
   *     // ... data to create a Paciente
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Paciente we want to update
   *   }
   * })
   */
  upsert<T extends PacienteUpsertArgs>(args: Prisma.SelectSubset<T, PacienteUpsertArgs<ExtArgs>>): Prisma.Prisma__PacienteClient<runtime.Types.Result.GetResult<Prisma.$PacientePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Pacientes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PacienteCountArgs} args - Arguments to filter Pacientes to count.
   * @example
   * // Count the number of Pacientes
   * const count = await prisma.paciente.count({
   *   where: {
   *     // ... the filter for the Pacientes we want to count
   *   }
   * })
  **/
  count<T extends PacienteCountArgs>(
    args?: Prisma.Subset<T, PacienteCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PacienteCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Paciente.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PacienteAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PacienteAggregateArgs>(args: Prisma.Subset<T, PacienteAggregateArgs>): Prisma.PrismaPromise<GetPacienteAggregateType<T>>

  /**
   * Group by Paciente.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PacienteGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PacienteGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PacienteGroupByArgs['orderBy'] }
      : { orderBy?: PacienteGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PacienteGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPacienteGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Paciente model
 */
readonly fields: PacienteFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Paciente.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PacienteClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  usuario<T extends Prisma.UsuarioDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UsuarioDefaultArgs<ExtArgs>>): Prisma.Prisma__UsuarioClient<runtime.Types.Result.GetResult<Prisma.$UsuarioPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  consultas<T extends Prisma.Paciente$consultasArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Paciente$consultasArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ConsultaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  prontuarios<T extends Prisma.Paciente$prontuariosArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Paciente$prontuariosArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProntuarioPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  notificacoes<T extends Prisma.Paciente$notificacoesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Paciente$notificacoesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NotificacaoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Paciente model
 */
export interface PacienteFieldRefs {
  readonly id: Prisma.FieldRef<"Paciente", 'String'>
  readonly usuarioId: Prisma.FieldRef<"Paciente", 'String'>
  readonly nome: Prisma.FieldRef<"Paciente", 'String'>
  readonly cpf: Prisma.FieldRef<"Paciente", 'String'>
  readonly dataNasc: Prisma.FieldRef<"Paciente", 'DateTime'>
  readonly telefone: Prisma.FieldRef<"Paciente", 'String'>
  readonly endereco: Prisma.FieldRef<"Paciente", 'String'>
  readonly sexo: Prisma.FieldRef<"Paciente", 'String'>
  readonly createdAt: Prisma.FieldRef<"Paciente", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Paciente", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Paciente findUnique
 */
export type PacienteFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Paciente
   */
  select?: Prisma.PacienteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Paciente
   */
  omit?: Prisma.PacienteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PacienteInclude<ExtArgs> | null
  /**
   * Filter, which Paciente to fetch.
   */
  where: Prisma.PacienteWhereUniqueInput
}

/**
 * Paciente findUniqueOrThrow
 */
export type PacienteFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Paciente
   */
  select?: Prisma.PacienteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Paciente
   */
  omit?: Prisma.PacienteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PacienteInclude<ExtArgs> | null
  /**
   * Filter, which Paciente to fetch.
   */
  where: Prisma.PacienteWhereUniqueInput
}

/**
 * Paciente findFirst
 */
export type PacienteFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Paciente
   */
  select?: Prisma.PacienteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Paciente
   */
  omit?: Prisma.PacienteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PacienteInclude<ExtArgs> | null
  /**
   * Filter, which Paciente to fetch.
   */
  where?: Prisma.PacienteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Pacientes to fetch.
   */
  orderBy?: Prisma.PacienteOrderByWithRelationInput | Prisma.PacienteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Pacientes.
   */
  cursor?: Prisma.PacienteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Pacientes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Pacientes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Pacientes.
   */
  distinct?: Prisma.PacienteScalarFieldEnum | Prisma.PacienteScalarFieldEnum[]
}

/**
 * Paciente findFirstOrThrow
 */
export type PacienteFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Paciente
   */
  select?: Prisma.PacienteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Paciente
   */
  omit?: Prisma.PacienteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PacienteInclude<ExtArgs> | null
  /**
   * Filter, which Paciente to fetch.
   */
  where?: Prisma.PacienteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Pacientes to fetch.
   */
  orderBy?: Prisma.PacienteOrderByWithRelationInput | Prisma.PacienteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Pacientes.
   */
  cursor?: Prisma.PacienteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Pacientes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Pacientes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Pacientes.
   */
  distinct?: Prisma.PacienteScalarFieldEnum | Prisma.PacienteScalarFieldEnum[]
}

/**
 * Paciente findMany
 */
export type PacienteFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Paciente
   */
  select?: Prisma.PacienteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Paciente
   */
  omit?: Prisma.PacienteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PacienteInclude<ExtArgs> | null
  /**
   * Filter, which Pacientes to fetch.
   */
  where?: Prisma.PacienteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Pacientes to fetch.
   */
  orderBy?: Prisma.PacienteOrderByWithRelationInput | Prisma.PacienteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Pacientes.
   */
  cursor?: Prisma.PacienteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Pacientes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Pacientes.
   */
  skip?: number
  distinct?: Prisma.PacienteScalarFieldEnum | Prisma.PacienteScalarFieldEnum[]
}

/**
 * Paciente create
 */
export type PacienteCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Paciente
   */
  select?: Prisma.PacienteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Paciente
   */
  omit?: Prisma.PacienteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PacienteInclude<ExtArgs> | null
  /**
   * The data needed to create a Paciente.
   */
  data: Prisma.XOR<Prisma.PacienteCreateInput, Prisma.PacienteUncheckedCreateInput>
}

/**
 * Paciente createMany
 */
export type PacienteCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Pacientes.
   */
  data: Prisma.PacienteCreateManyInput | Prisma.PacienteCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Paciente createManyAndReturn
 */
export type PacienteCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Paciente
   */
  select?: Prisma.PacienteSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Paciente
   */
  omit?: Prisma.PacienteOmit<ExtArgs> | null
  /**
   * The data used to create many Pacientes.
   */
  data: Prisma.PacienteCreateManyInput | Prisma.PacienteCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PacienteIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Paciente update
 */
export type PacienteUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Paciente
   */
  select?: Prisma.PacienteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Paciente
   */
  omit?: Prisma.PacienteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PacienteInclude<ExtArgs> | null
  /**
   * The data needed to update a Paciente.
   */
  data: Prisma.XOR<Prisma.PacienteUpdateInput, Prisma.PacienteUncheckedUpdateInput>
  /**
   * Choose, which Paciente to update.
   */
  where: Prisma.PacienteWhereUniqueInput
}

/**
 * Paciente updateMany
 */
export type PacienteUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Pacientes.
   */
  data: Prisma.XOR<Prisma.PacienteUpdateManyMutationInput, Prisma.PacienteUncheckedUpdateManyInput>
  /**
   * Filter which Pacientes to update
   */
  where?: Prisma.PacienteWhereInput
  /**
   * Limit how many Pacientes to update.
   */
  limit?: number
}

/**
 * Paciente updateManyAndReturn
 */
export type PacienteUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Paciente
   */
  select?: Prisma.PacienteSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Paciente
   */
  omit?: Prisma.PacienteOmit<ExtArgs> | null
  /**
   * The data used to update Pacientes.
   */
  data: Prisma.XOR<Prisma.PacienteUpdateManyMutationInput, Prisma.PacienteUncheckedUpdateManyInput>
  /**
   * Filter which Pacientes to update
   */
  where?: Prisma.PacienteWhereInput
  /**
   * Limit how many Pacientes to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PacienteIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Paciente upsert
 */
export type PacienteUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Paciente
   */
  select?: Prisma.PacienteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Paciente
   */
  omit?: Prisma.PacienteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PacienteInclude<ExtArgs> | null
  /**
   * The filter to search for the Paciente to update in case it exists.
   */
  where: Prisma.PacienteWhereUniqueInput
  /**
   * In case the Paciente found by the `where` argument doesn't exist, create a new Paciente with this data.
   */
  create: Prisma.XOR<Prisma.PacienteCreateInput, Prisma.PacienteUncheckedCreateInput>
  /**
   * In case the Paciente was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PacienteUpdateInput, Prisma.PacienteUncheckedUpdateInput>
}

/**
 * Paciente delete
 */
export type PacienteDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Paciente
   */
  select?: Prisma.PacienteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Paciente
   */
  omit?: Prisma.PacienteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PacienteInclude<ExtArgs> | null
  /**
   * Filter which Paciente to delete.
   */
  where: Prisma.PacienteWhereUniqueInput
}

/**
 * Paciente deleteMany
 */
export type PacienteDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Pacientes to delete
   */
  where?: Prisma.PacienteWhereInput
  /**
   * Limit how many Pacientes to delete.
   */
  limit?: number
}

/**
 * Paciente.consultas
 */
export type Paciente$consultasArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Consulta
   */
  select?: Prisma.ConsultaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Consulta
   */
  omit?: Prisma.ConsultaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConsultaInclude<ExtArgs> | null
  where?: Prisma.ConsultaWhereInput
  orderBy?: Prisma.ConsultaOrderByWithRelationInput | Prisma.ConsultaOrderByWithRelationInput[]
  cursor?: Prisma.ConsultaWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ConsultaScalarFieldEnum | Prisma.ConsultaScalarFieldEnum[]
}

/**
 * Paciente.prontuarios
 */
export type Paciente$prontuariosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Prontuario
   */
  select?: Prisma.ProntuarioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Prontuario
   */
  omit?: Prisma.ProntuarioOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProntuarioInclude<ExtArgs> | null
  where?: Prisma.ProntuarioWhereInput
  orderBy?: Prisma.ProntuarioOrderByWithRelationInput | Prisma.ProntuarioOrderByWithRelationInput[]
  cursor?: Prisma.ProntuarioWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProntuarioScalarFieldEnum | Prisma.ProntuarioScalarFieldEnum[]
}

/**
 * Paciente.notificacoes
 */
export type Paciente$notificacoesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Notificacao
   */
  select?: Prisma.NotificacaoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Notificacao
   */
  omit?: Prisma.NotificacaoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotificacaoInclude<ExtArgs> | null
  where?: Prisma.NotificacaoWhereInput
  orderBy?: Prisma.NotificacaoOrderByWithRelationInput | Prisma.NotificacaoOrderByWithRelationInput[]
  cursor?: Prisma.NotificacaoWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.NotificacaoScalarFieldEnum | Prisma.NotificacaoScalarFieldEnum[]
}

/**
 * Paciente without action
 */
export type PacienteDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Paciente
   */
  select?: Prisma.PacienteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Paciente
   */
  omit?: Prisma.PacienteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PacienteInclude<ExtArgs> | null
}
