
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Prescricao` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Prescricao
 * 
 */
export type PrescricaoModel = runtime.Types.Result.DefaultSelection<Prisma.$PrescricaoPayload>

export type AggregatePrescricao = {
  _count: PrescricaoCountAggregateOutputType | null
  _min: PrescricaoMinAggregateOutputType | null
  _max: PrescricaoMaxAggregateOutputType | null
}

export type PrescricaoMinAggregateOutputType = {
  id: string | null
  consultaId: string | null
  profissionalId: string | null
  medicamento: string | null
  dosagem: string | null
  instrucoes: string | null
  dataEmissao: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PrescricaoMaxAggregateOutputType = {
  id: string | null
  consultaId: string | null
  profissionalId: string | null
  medicamento: string | null
  dosagem: string | null
  instrucoes: string | null
  dataEmissao: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PrescricaoCountAggregateOutputType = {
  id: number
  consultaId: number
  profissionalId: number
  medicamento: number
  dosagem: number
  instrucoes: number
  dataEmissao: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type PrescricaoMinAggregateInputType = {
  id?: true
  consultaId?: true
  profissionalId?: true
  medicamento?: true
  dosagem?: true
  instrucoes?: true
  dataEmissao?: true
  createdAt?: true
  updatedAt?: true
}

export type PrescricaoMaxAggregateInputType = {
  id?: true
  consultaId?: true
  profissionalId?: true
  medicamento?: true
  dosagem?: true
  instrucoes?: true
  dataEmissao?: true
  createdAt?: true
  updatedAt?: true
}

export type PrescricaoCountAggregateInputType = {
  id?: true
  consultaId?: true
  profissionalId?: true
  medicamento?: true
  dosagem?: true
  instrucoes?: true
  dataEmissao?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type PrescricaoAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Prescricao to aggregate.
   */
  where?: Prisma.PrescricaoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Prescricaos to fetch.
   */
  orderBy?: Prisma.PrescricaoOrderByWithRelationInput | Prisma.PrescricaoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PrescricaoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Prescricaos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Prescricaos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Prescricaos
  **/
  _count?: true | PrescricaoCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PrescricaoMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PrescricaoMaxAggregateInputType
}

export type GetPrescricaoAggregateType<T extends PrescricaoAggregateArgs> = {
      [P in keyof T & keyof AggregatePrescricao]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePrescricao[P]>
    : Prisma.GetScalarType<T[P], AggregatePrescricao[P]>
}




export type PrescricaoGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PrescricaoWhereInput
  orderBy?: Prisma.PrescricaoOrderByWithAggregationInput | Prisma.PrescricaoOrderByWithAggregationInput[]
  by: Prisma.PrescricaoScalarFieldEnum[] | Prisma.PrescricaoScalarFieldEnum
  having?: Prisma.PrescricaoScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PrescricaoCountAggregateInputType | true
  _min?: PrescricaoMinAggregateInputType
  _max?: PrescricaoMaxAggregateInputType
}

export type PrescricaoGroupByOutputType = {
  id: string
  consultaId: string
  profissionalId: string
  medicamento: string
  dosagem: string
  instrucoes: string | null
  dataEmissao: Date
  createdAt: Date
  updatedAt: Date
  _count: PrescricaoCountAggregateOutputType | null
  _min: PrescricaoMinAggregateOutputType | null
  _max: PrescricaoMaxAggregateOutputType | null
}

type GetPrescricaoGroupByPayload<T extends PrescricaoGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PrescricaoGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PrescricaoGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PrescricaoGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PrescricaoGroupByOutputType[P]>
      }
    >
  >



export type PrescricaoWhereInput = {
  AND?: Prisma.PrescricaoWhereInput | Prisma.PrescricaoWhereInput[]
  OR?: Prisma.PrescricaoWhereInput[]
  NOT?: Prisma.PrescricaoWhereInput | Prisma.PrescricaoWhereInput[]
  id?: Prisma.StringFilter<"Prescricao"> | string
  consultaId?: Prisma.StringFilter<"Prescricao"> | string
  profissionalId?: Prisma.StringFilter<"Prescricao"> | string
  medicamento?: Prisma.StringFilter<"Prescricao"> | string
  dosagem?: Prisma.StringFilter<"Prescricao"> | string
  instrucoes?: Prisma.StringNullableFilter<"Prescricao"> | string | null
  dataEmissao?: Prisma.DateTimeFilter<"Prescricao"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"Prescricao"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Prescricao"> | Date | string
  consulta?: Prisma.XOR<Prisma.ConsultaScalarRelationFilter, Prisma.ConsultaWhereInput>
  profissional?: Prisma.XOR<Prisma.ProfissionalScalarRelationFilter, Prisma.ProfissionalWhereInput>
}

export type PrescricaoOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  consultaId?: Prisma.SortOrder
  profissionalId?: Prisma.SortOrder
  medicamento?: Prisma.SortOrder
  dosagem?: Prisma.SortOrder
  instrucoes?: Prisma.SortOrderInput | Prisma.SortOrder
  dataEmissao?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  consulta?: Prisma.ConsultaOrderByWithRelationInput
  profissional?: Prisma.ProfissionalOrderByWithRelationInput
}

export type PrescricaoWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PrescricaoWhereInput | Prisma.PrescricaoWhereInput[]
  OR?: Prisma.PrescricaoWhereInput[]
  NOT?: Prisma.PrescricaoWhereInput | Prisma.PrescricaoWhereInput[]
  consultaId?: Prisma.StringFilter<"Prescricao"> | string
  profissionalId?: Prisma.StringFilter<"Prescricao"> | string
  medicamento?: Prisma.StringFilter<"Prescricao"> | string
  dosagem?: Prisma.StringFilter<"Prescricao"> | string
  instrucoes?: Prisma.StringNullableFilter<"Prescricao"> | string | null
  dataEmissao?: Prisma.DateTimeFilter<"Prescricao"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"Prescricao"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Prescricao"> | Date | string
  consulta?: Prisma.XOR<Prisma.ConsultaScalarRelationFilter, Prisma.ConsultaWhereInput>
  profissional?: Prisma.XOR<Prisma.ProfissionalScalarRelationFilter, Prisma.ProfissionalWhereInput>
}, "id">

export type PrescricaoOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  consultaId?: Prisma.SortOrder
  profissionalId?: Prisma.SortOrder
  medicamento?: Prisma.SortOrder
  dosagem?: Prisma.SortOrder
  instrucoes?: Prisma.SortOrderInput | Prisma.SortOrder
  dataEmissao?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PrescricaoCountOrderByAggregateInput
  _max?: Prisma.PrescricaoMaxOrderByAggregateInput
  _min?: Prisma.PrescricaoMinOrderByAggregateInput
}

export type PrescricaoScalarWhereWithAggregatesInput = {
  AND?: Prisma.PrescricaoScalarWhereWithAggregatesInput | Prisma.PrescricaoScalarWhereWithAggregatesInput[]
  OR?: Prisma.PrescricaoScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PrescricaoScalarWhereWithAggregatesInput | Prisma.PrescricaoScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Prescricao"> | string
  consultaId?: Prisma.StringWithAggregatesFilter<"Prescricao"> | string
  profissionalId?: Prisma.StringWithAggregatesFilter<"Prescricao"> | string
  medicamento?: Prisma.StringWithAggregatesFilter<"Prescricao"> | string
  dosagem?: Prisma.StringWithAggregatesFilter<"Prescricao"> | string
  instrucoes?: Prisma.StringNullableWithAggregatesFilter<"Prescricao"> | string | null
  dataEmissao?: Prisma.DateTimeWithAggregatesFilter<"Prescricao"> | Date | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Prescricao"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Prescricao"> | Date | string
}

export type PrescricaoCreateInput = {
  id?: string
  medicamento: string
  dosagem: string
  instrucoes?: string | null
  dataEmissao?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  consulta: Prisma.ConsultaCreateNestedOneWithoutPrescricoesInput
  profissional: Prisma.ProfissionalCreateNestedOneWithoutPrescricoesInput
}

export type PrescricaoUncheckedCreateInput = {
  id?: string
  consultaId: string
  profissionalId: string
  medicamento: string
  dosagem: string
  instrucoes?: string | null
  dataEmissao?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PrescricaoUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  medicamento?: Prisma.StringFieldUpdateOperationsInput | string
  dosagem?: Prisma.StringFieldUpdateOperationsInput | string
  instrucoes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dataEmissao?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  consulta?: Prisma.ConsultaUpdateOneRequiredWithoutPrescricoesNestedInput
  profissional?: Prisma.ProfissionalUpdateOneRequiredWithoutPrescricoesNestedInput
}

export type PrescricaoUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  consultaId?: Prisma.StringFieldUpdateOperationsInput | string
  profissionalId?: Prisma.StringFieldUpdateOperationsInput | string
  medicamento?: Prisma.StringFieldUpdateOperationsInput | string
  dosagem?: Prisma.StringFieldUpdateOperationsInput | string
  instrucoes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dataEmissao?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PrescricaoCreateManyInput = {
  id?: string
  consultaId: string
  profissionalId: string
  medicamento: string
  dosagem: string
  instrucoes?: string | null
  dataEmissao?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PrescricaoUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  medicamento?: Prisma.StringFieldUpdateOperationsInput | string
  dosagem?: Prisma.StringFieldUpdateOperationsInput | string
  instrucoes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dataEmissao?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PrescricaoUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  consultaId?: Prisma.StringFieldUpdateOperationsInput | string
  profissionalId?: Prisma.StringFieldUpdateOperationsInput | string
  medicamento?: Prisma.StringFieldUpdateOperationsInput | string
  dosagem?: Prisma.StringFieldUpdateOperationsInput | string
  instrucoes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dataEmissao?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PrescricaoListRelationFilter = {
  every?: Prisma.PrescricaoWhereInput
  some?: Prisma.PrescricaoWhereInput
  none?: Prisma.PrescricaoWhereInput
}

export type PrescricaoOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PrescricaoCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  consultaId?: Prisma.SortOrder
  profissionalId?: Prisma.SortOrder
  medicamento?: Prisma.SortOrder
  dosagem?: Prisma.SortOrder
  instrucoes?: Prisma.SortOrder
  dataEmissao?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PrescricaoMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  consultaId?: Prisma.SortOrder
  profissionalId?: Prisma.SortOrder
  medicamento?: Prisma.SortOrder
  dosagem?: Prisma.SortOrder
  instrucoes?: Prisma.SortOrder
  dataEmissao?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PrescricaoMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  consultaId?: Prisma.SortOrder
  profissionalId?: Prisma.SortOrder
  medicamento?: Prisma.SortOrder
  dosagem?: Prisma.SortOrder
  instrucoes?: Prisma.SortOrder
  dataEmissao?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PrescricaoCreateNestedManyWithoutProfissionalInput = {
  create?: Prisma.XOR<Prisma.PrescricaoCreateWithoutProfissionalInput, Prisma.PrescricaoUncheckedCreateWithoutProfissionalInput> | Prisma.PrescricaoCreateWithoutProfissionalInput[] | Prisma.PrescricaoUncheckedCreateWithoutProfissionalInput[]
  connectOrCreate?: Prisma.PrescricaoCreateOrConnectWithoutProfissionalInput | Prisma.PrescricaoCreateOrConnectWithoutProfissionalInput[]
  createMany?: Prisma.PrescricaoCreateManyProfissionalInputEnvelope
  connect?: Prisma.PrescricaoWhereUniqueInput | Prisma.PrescricaoWhereUniqueInput[]
}

export type PrescricaoUncheckedCreateNestedManyWithoutProfissionalInput = {
  create?: Prisma.XOR<Prisma.PrescricaoCreateWithoutProfissionalInput, Prisma.PrescricaoUncheckedCreateWithoutProfissionalInput> | Prisma.PrescricaoCreateWithoutProfissionalInput[] | Prisma.PrescricaoUncheckedCreateWithoutProfissionalInput[]
  connectOrCreate?: Prisma.PrescricaoCreateOrConnectWithoutProfissionalInput | Prisma.PrescricaoCreateOrConnectWithoutProfissionalInput[]
  createMany?: Prisma.PrescricaoCreateManyProfissionalInputEnvelope
  connect?: Prisma.PrescricaoWhereUniqueInput | Prisma.PrescricaoWhereUniqueInput[]
}

export type PrescricaoUpdateManyWithoutProfissionalNestedInput = {
  create?: Prisma.XOR<Prisma.PrescricaoCreateWithoutProfissionalInput, Prisma.PrescricaoUncheckedCreateWithoutProfissionalInput> | Prisma.PrescricaoCreateWithoutProfissionalInput[] | Prisma.PrescricaoUncheckedCreateWithoutProfissionalInput[]
  connectOrCreate?: Prisma.PrescricaoCreateOrConnectWithoutProfissionalInput | Prisma.PrescricaoCreateOrConnectWithoutProfissionalInput[]
  upsert?: Prisma.PrescricaoUpsertWithWhereUniqueWithoutProfissionalInput | Prisma.PrescricaoUpsertWithWhereUniqueWithoutProfissionalInput[]
  createMany?: Prisma.PrescricaoCreateManyProfissionalInputEnvelope
  set?: Prisma.PrescricaoWhereUniqueInput | Prisma.PrescricaoWhereUniqueInput[]
  disconnect?: Prisma.PrescricaoWhereUniqueInput | Prisma.PrescricaoWhereUniqueInput[]
  delete?: Prisma.PrescricaoWhereUniqueInput | Prisma.PrescricaoWhereUniqueInput[]
  connect?: Prisma.PrescricaoWhereUniqueInput | Prisma.PrescricaoWhereUniqueInput[]
  update?: Prisma.PrescricaoUpdateWithWhereUniqueWithoutProfissionalInput | Prisma.PrescricaoUpdateWithWhereUniqueWithoutProfissionalInput[]
  updateMany?: Prisma.PrescricaoUpdateManyWithWhereWithoutProfissionalInput | Prisma.PrescricaoUpdateManyWithWhereWithoutProfissionalInput[]
  deleteMany?: Prisma.PrescricaoScalarWhereInput | Prisma.PrescricaoScalarWhereInput[]
}

export type PrescricaoUncheckedUpdateManyWithoutProfissionalNestedInput = {
  create?: Prisma.XOR<Prisma.PrescricaoCreateWithoutProfissionalInput, Prisma.PrescricaoUncheckedCreateWithoutProfissionalInput> | Prisma.PrescricaoCreateWithoutProfissionalInput[] | Prisma.PrescricaoUncheckedCreateWithoutProfissionalInput[]
  connectOrCreate?: Prisma.PrescricaoCreateOrConnectWithoutProfissionalInput | Prisma.PrescricaoCreateOrConnectWithoutProfissionalInput[]
  upsert?: Prisma.PrescricaoUpsertWithWhereUniqueWithoutProfissionalInput | Prisma.PrescricaoUpsertWithWhereUniqueWithoutProfissionalInput[]
  createMany?: Prisma.PrescricaoCreateManyProfissionalInputEnvelope
  set?: Prisma.PrescricaoWhereUniqueInput | Prisma.PrescricaoWhereUniqueInput[]
  disconnect?: Prisma.PrescricaoWhereUniqueInput | Prisma.PrescricaoWhereUniqueInput[]
  delete?: Prisma.PrescricaoWhereUniqueInput | Prisma.PrescricaoWhereUniqueInput[]
  connect?: Prisma.PrescricaoWhereUniqueInput | Prisma.PrescricaoWhereUniqueInput[]
  update?: Prisma.PrescricaoUpdateWithWhereUniqueWithoutProfissionalInput | Prisma.PrescricaoUpdateWithWhereUniqueWithoutProfissionalInput[]
  updateMany?: Prisma.PrescricaoUpdateManyWithWhereWithoutProfissionalInput | Prisma.PrescricaoUpdateManyWithWhereWithoutProfissionalInput[]
  deleteMany?: Prisma.PrescricaoScalarWhereInput | Prisma.PrescricaoScalarWhereInput[]
}

export type PrescricaoCreateNestedManyWithoutConsultaInput = {
  create?: Prisma.XOR<Prisma.PrescricaoCreateWithoutConsultaInput, Prisma.PrescricaoUncheckedCreateWithoutConsultaInput> | Prisma.PrescricaoCreateWithoutConsultaInput[] | Prisma.PrescricaoUncheckedCreateWithoutConsultaInput[]
  connectOrCreate?: Prisma.PrescricaoCreateOrConnectWithoutConsultaInput | Prisma.PrescricaoCreateOrConnectWithoutConsultaInput[]
  createMany?: Prisma.PrescricaoCreateManyConsultaInputEnvelope
  connect?: Prisma.PrescricaoWhereUniqueInput | Prisma.PrescricaoWhereUniqueInput[]
}

export type PrescricaoUncheckedCreateNestedManyWithoutConsultaInput = {
  create?: Prisma.XOR<Prisma.PrescricaoCreateWithoutConsultaInput, Prisma.PrescricaoUncheckedCreateWithoutConsultaInput> | Prisma.PrescricaoCreateWithoutConsultaInput[] | Prisma.PrescricaoUncheckedCreateWithoutConsultaInput[]
  connectOrCreate?: Prisma.PrescricaoCreateOrConnectWithoutConsultaInput | Prisma.PrescricaoCreateOrConnectWithoutConsultaInput[]
  createMany?: Prisma.PrescricaoCreateManyConsultaInputEnvelope
  connect?: Prisma.PrescricaoWhereUniqueInput | Prisma.PrescricaoWhereUniqueInput[]
}

export type PrescricaoUpdateManyWithoutConsultaNestedInput = {
  create?: Prisma.XOR<Prisma.PrescricaoCreateWithoutConsultaInput, Prisma.PrescricaoUncheckedCreateWithoutConsultaInput> | Prisma.PrescricaoCreateWithoutConsultaInput[] | Prisma.PrescricaoUncheckedCreateWithoutConsultaInput[]
  connectOrCreate?: Prisma.PrescricaoCreateOrConnectWithoutConsultaInput | Prisma.PrescricaoCreateOrConnectWithoutConsultaInput[]
  upsert?: Prisma.PrescricaoUpsertWithWhereUniqueWithoutConsultaInput | Prisma.PrescricaoUpsertWithWhereUniqueWithoutConsultaInput[]
  createMany?: Prisma.PrescricaoCreateManyConsultaInputEnvelope
  set?: Prisma.PrescricaoWhereUniqueInput | Prisma.PrescricaoWhereUniqueInput[]
  disconnect?: Prisma.PrescricaoWhereUniqueInput | Prisma.PrescricaoWhereUniqueInput[]
  delete?: Prisma.PrescricaoWhereUniqueInput | Prisma.PrescricaoWhereUniqueInput[]
  connect?: Prisma.PrescricaoWhereUniqueInput | Prisma.PrescricaoWhereUniqueInput[]
  update?: Prisma.PrescricaoUpdateWithWhereUniqueWithoutConsultaInput | Prisma.PrescricaoUpdateWithWhereUniqueWithoutConsultaInput[]
  updateMany?: Prisma.PrescricaoUpdateManyWithWhereWithoutConsultaInput | Prisma.PrescricaoUpdateManyWithWhereWithoutConsultaInput[]
  deleteMany?: Prisma.PrescricaoScalarWhereInput | Prisma.PrescricaoScalarWhereInput[]
}

export type PrescricaoUncheckedUpdateManyWithoutConsultaNestedInput = {
  create?: Prisma.XOR<Prisma.PrescricaoCreateWithoutConsultaInput, Prisma.PrescricaoUncheckedCreateWithoutConsultaInput> | Prisma.PrescricaoCreateWithoutConsultaInput[] | Prisma.PrescricaoUncheckedCreateWithoutConsultaInput[]
  connectOrCreate?: Prisma.PrescricaoCreateOrConnectWithoutConsultaInput | Prisma.PrescricaoCreateOrConnectWithoutConsultaInput[]
  upsert?: Prisma.PrescricaoUpsertWithWhereUniqueWithoutConsultaInput | Prisma.PrescricaoUpsertWithWhereUniqueWithoutConsultaInput[]
  createMany?: Prisma.PrescricaoCreateManyConsultaInputEnvelope
  set?: Prisma.PrescricaoWhereUniqueInput | Prisma.PrescricaoWhereUniqueInput[]
  disconnect?: Prisma.PrescricaoWhereUniqueInput | Prisma.PrescricaoWhereUniqueInput[]
  delete?: Prisma.PrescricaoWhereUniqueInput | Prisma.PrescricaoWhereUniqueInput[]
  connect?: Prisma.PrescricaoWhereUniqueInput | Prisma.PrescricaoWhereUniqueInput[]
  update?: Prisma.PrescricaoUpdateWithWhereUniqueWithoutConsultaInput | Prisma.PrescricaoUpdateWithWhereUniqueWithoutConsultaInput[]
  updateMany?: Prisma.PrescricaoUpdateManyWithWhereWithoutConsultaInput | Prisma.PrescricaoUpdateManyWithWhereWithoutConsultaInput[]
  deleteMany?: Prisma.PrescricaoScalarWhereInput | Prisma.PrescricaoScalarWhereInput[]
}

export type PrescricaoCreateWithoutProfissionalInput = {
  id?: string
  medicamento: string
  dosagem: string
  instrucoes?: string | null
  dataEmissao?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  consulta: Prisma.ConsultaCreateNestedOneWithoutPrescricoesInput
}

export type PrescricaoUncheckedCreateWithoutProfissionalInput = {
  id?: string
  consultaId: string
  medicamento: string
  dosagem: string
  instrucoes?: string | null
  dataEmissao?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PrescricaoCreateOrConnectWithoutProfissionalInput = {
  where: Prisma.PrescricaoWhereUniqueInput
  create: Prisma.XOR<Prisma.PrescricaoCreateWithoutProfissionalInput, Prisma.PrescricaoUncheckedCreateWithoutProfissionalInput>
}

export type PrescricaoCreateManyProfissionalInputEnvelope = {
  data: Prisma.PrescricaoCreateManyProfissionalInput | Prisma.PrescricaoCreateManyProfissionalInput[]
  skipDuplicates?: boolean
}

export type PrescricaoUpsertWithWhereUniqueWithoutProfissionalInput = {
  where: Prisma.PrescricaoWhereUniqueInput
  update: Prisma.XOR<Prisma.PrescricaoUpdateWithoutProfissionalInput, Prisma.PrescricaoUncheckedUpdateWithoutProfissionalInput>
  create: Prisma.XOR<Prisma.PrescricaoCreateWithoutProfissionalInput, Prisma.PrescricaoUncheckedCreateWithoutProfissionalInput>
}

export type PrescricaoUpdateWithWhereUniqueWithoutProfissionalInput = {
  where: Prisma.PrescricaoWhereUniqueInput
  data: Prisma.XOR<Prisma.PrescricaoUpdateWithoutProfissionalInput, Prisma.PrescricaoUncheckedUpdateWithoutProfissionalInput>
}

export type PrescricaoUpdateManyWithWhereWithoutProfissionalInput = {
  where: Prisma.PrescricaoScalarWhereInput
  data: Prisma.XOR<Prisma.PrescricaoUpdateManyMutationInput, Prisma.PrescricaoUncheckedUpdateManyWithoutProfissionalInput>
}

export type PrescricaoScalarWhereInput = {
  AND?: Prisma.PrescricaoScalarWhereInput | Prisma.PrescricaoScalarWhereInput[]
  OR?: Prisma.PrescricaoScalarWhereInput[]
  NOT?: Prisma.PrescricaoScalarWhereInput | Prisma.PrescricaoScalarWhereInput[]
  id?: Prisma.StringFilter<"Prescricao"> | string
  consultaId?: Prisma.StringFilter<"Prescricao"> | string
  profissionalId?: Prisma.StringFilter<"Prescricao"> | string
  medicamento?: Prisma.StringFilter<"Prescricao"> | string
  dosagem?: Prisma.StringFilter<"Prescricao"> | string
  instrucoes?: Prisma.StringNullableFilter<"Prescricao"> | string | null
  dataEmissao?: Prisma.DateTimeFilter<"Prescricao"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"Prescricao"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Prescricao"> | Date | string
}

export type PrescricaoCreateWithoutConsultaInput = {
  id?: string
  medicamento: string
  dosagem: string
  instrucoes?: string | null
  dataEmissao?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  profissional: Prisma.ProfissionalCreateNestedOneWithoutPrescricoesInput
}

export type PrescricaoUncheckedCreateWithoutConsultaInput = {
  id?: string
  profissionalId: string
  medicamento: string
  dosagem: string
  instrucoes?: string | null
  dataEmissao?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PrescricaoCreateOrConnectWithoutConsultaInput = {
  where: Prisma.PrescricaoWhereUniqueInput
  create: Prisma.XOR<Prisma.PrescricaoCreateWithoutConsultaInput, Prisma.PrescricaoUncheckedCreateWithoutConsultaInput>
}

export type PrescricaoCreateManyConsultaInputEnvelope = {
  data: Prisma.PrescricaoCreateManyConsultaInput | Prisma.PrescricaoCreateManyConsultaInput[]
  skipDuplicates?: boolean
}

export type PrescricaoUpsertWithWhereUniqueWithoutConsultaInput = {
  where: Prisma.PrescricaoWhereUniqueInput
  update: Prisma.XOR<Prisma.PrescricaoUpdateWithoutConsultaInput, Prisma.PrescricaoUncheckedUpdateWithoutConsultaInput>
  create: Prisma.XOR<Prisma.PrescricaoCreateWithoutConsultaInput, Prisma.PrescricaoUncheckedCreateWithoutConsultaInput>
}

export type PrescricaoUpdateWithWhereUniqueWithoutConsultaInput = {
  where: Prisma.PrescricaoWhereUniqueInput
  data: Prisma.XOR<Prisma.PrescricaoUpdateWithoutConsultaInput, Prisma.PrescricaoUncheckedUpdateWithoutConsultaInput>
}

export type PrescricaoUpdateManyWithWhereWithoutConsultaInput = {
  where: Prisma.PrescricaoScalarWhereInput
  data: Prisma.XOR<Prisma.PrescricaoUpdateManyMutationInput, Prisma.PrescricaoUncheckedUpdateManyWithoutConsultaInput>
}

export type PrescricaoCreateManyProfissionalInput = {
  id?: string
  consultaId: string
  medicamento: string
  dosagem: string
  instrucoes?: string | null
  dataEmissao?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PrescricaoUpdateWithoutProfissionalInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  medicamento?: Prisma.StringFieldUpdateOperationsInput | string
  dosagem?: Prisma.StringFieldUpdateOperationsInput | string
  instrucoes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dataEmissao?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  consulta?: Prisma.ConsultaUpdateOneRequiredWithoutPrescricoesNestedInput
}

export type PrescricaoUncheckedUpdateWithoutProfissionalInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  consultaId?: Prisma.StringFieldUpdateOperationsInput | string
  medicamento?: Prisma.StringFieldUpdateOperationsInput | string
  dosagem?: Prisma.StringFieldUpdateOperationsInput | string
  instrucoes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dataEmissao?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PrescricaoUncheckedUpdateManyWithoutProfissionalInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  consultaId?: Prisma.StringFieldUpdateOperationsInput | string
  medicamento?: Prisma.StringFieldUpdateOperationsInput | string
  dosagem?: Prisma.StringFieldUpdateOperationsInput | string
  instrucoes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dataEmissao?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PrescricaoCreateManyConsultaInput = {
  id?: string
  profissionalId: string
  medicamento: string
  dosagem: string
  instrucoes?: string | null
  dataEmissao?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PrescricaoUpdateWithoutConsultaInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  medicamento?: Prisma.StringFieldUpdateOperationsInput | string
  dosagem?: Prisma.StringFieldUpdateOperationsInput | string
  instrucoes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dataEmissao?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  profissional?: Prisma.ProfissionalUpdateOneRequiredWithoutPrescricoesNestedInput
}

export type PrescricaoUncheckedUpdateWithoutConsultaInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  profissionalId?: Prisma.StringFieldUpdateOperationsInput | string
  medicamento?: Prisma.StringFieldUpdateOperationsInput | string
  dosagem?: Prisma.StringFieldUpdateOperationsInput | string
  instrucoes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dataEmissao?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PrescricaoUncheckedUpdateManyWithoutConsultaInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  profissionalId?: Prisma.StringFieldUpdateOperationsInput | string
  medicamento?: Prisma.StringFieldUpdateOperationsInput | string
  dosagem?: Prisma.StringFieldUpdateOperationsInput | string
  instrucoes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dataEmissao?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type PrescricaoSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  consultaId?: boolean
  profissionalId?: boolean
  medicamento?: boolean
  dosagem?: boolean
  instrucoes?: boolean
  dataEmissao?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  consulta?: boolean | Prisma.ConsultaDefaultArgs<ExtArgs>
  profissional?: boolean | Prisma.ProfissionalDefaultArgs<ExtArgs>
}, ExtArgs["result"]["prescricao"]>

export type PrescricaoSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  consultaId?: boolean
  profissionalId?: boolean
  medicamento?: boolean
  dosagem?: boolean
  instrucoes?: boolean
  dataEmissao?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  consulta?: boolean | Prisma.ConsultaDefaultArgs<ExtArgs>
  profissional?: boolean | Prisma.ProfissionalDefaultArgs<ExtArgs>
}, ExtArgs["result"]["prescricao"]>

export type PrescricaoSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  consultaId?: boolean
  profissionalId?: boolean
  medicamento?: boolean
  dosagem?: boolean
  instrucoes?: boolean
  dataEmissao?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  consulta?: boolean | Prisma.ConsultaDefaultArgs<ExtArgs>
  profissional?: boolean | Prisma.ProfissionalDefaultArgs<ExtArgs>
}, ExtArgs["result"]["prescricao"]>

export type PrescricaoSelectScalar = {
  id?: boolean
  consultaId?: boolean
  profissionalId?: boolean
  medicamento?: boolean
  dosagem?: boolean
  instrucoes?: boolean
  dataEmissao?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type PrescricaoOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "consultaId" | "profissionalId" | "medicamento" | "dosagem" | "instrucoes" | "dataEmissao" | "createdAt" | "updatedAt", ExtArgs["result"]["prescricao"]>
export type PrescricaoInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  consulta?: boolean | Prisma.ConsultaDefaultArgs<ExtArgs>
  profissional?: boolean | Prisma.ProfissionalDefaultArgs<ExtArgs>
}
export type PrescricaoIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  consulta?: boolean | Prisma.ConsultaDefaultArgs<ExtArgs>
  profissional?: boolean | Prisma.ProfissionalDefaultArgs<ExtArgs>
}
export type PrescricaoIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  consulta?: boolean | Prisma.ConsultaDefaultArgs<ExtArgs>
  profissional?: boolean | Prisma.ProfissionalDefaultArgs<ExtArgs>
}

export type $PrescricaoPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Prescricao"
  objects: {
    consulta: Prisma.$ConsultaPayload<ExtArgs>
    profissional: Prisma.$ProfissionalPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    consultaId: string
    profissionalId: string
    medicamento: string
    dosagem: string
    instrucoes: string | null
    dataEmissao: Date
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["prescricao"]>
  composites: {}
}

export type PrescricaoGetPayload<S extends boolean | null | undefined | PrescricaoDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PrescricaoPayload, S>

export type PrescricaoCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PrescricaoFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PrescricaoCountAggregateInputType | true
  }

export interface PrescricaoDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Prescricao'], meta: { name: 'Prescricao' } }
  /**
   * Find zero or one Prescricao that matches the filter.
   * @param {PrescricaoFindUniqueArgs} args - Arguments to find a Prescricao
   * @example
   * // Get one Prescricao
   * const prescricao = await prisma.prescricao.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PrescricaoFindUniqueArgs>(args: Prisma.SelectSubset<T, PrescricaoFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PrescricaoClient<runtime.Types.Result.GetResult<Prisma.$PrescricaoPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Prescricao that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PrescricaoFindUniqueOrThrowArgs} args - Arguments to find a Prescricao
   * @example
   * // Get one Prescricao
   * const prescricao = await prisma.prescricao.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PrescricaoFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PrescricaoFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PrescricaoClient<runtime.Types.Result.GetResult<Prisma.$PrescricaoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Prescricao that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PrescricaoFindFirstArgs} args - Arguments to find a Prescricao
   * @example
   * // Get one Prescricao
   * const prescricao = await prisma.prescricao.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PrescricaoFindFirstArgs>(args?: Prisma.SelectSubset<T, PrescricaoFindFirstArgs<ExtArgs>>): Prisma.Prisma__PrescricaoClient<runtime.Types.Result.GetResult<Prisma.$PrescricaoPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Prescricao that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PrescricaoFindFirstOrThrowArgs} args - Arguments to find a Prescricao
   * @example
   * // Get one Prescricao
   * const prescricao = await prisma.prescricao.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PrescricaoFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PrescricaoFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PrescricaoClient<runtime.Types.Result.GetResult<Prisma.$PrescricaoPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Prescricaos that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PrescricaoFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Prescricaos
   * const prescricaos = await prisma.prescricao.findMany()
   * 
   * // Get first 10 Prescricaos
   * const prescricaos = await prisma.prescricao.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const prescricaoWithIdOnly = await prisma.prescricao.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PrescricaoFindManyArgs>(args?: Prisma.SelectSubset<T, PrescricaoFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PrescricaoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Prescricao.
   * @param {PrescricaoCreateArgs} args - Arguments to create a Prescricao.
   * @example
   * // Create one Prescricao
   * const Prescricao = await prisma.prescricao.create({
   *   data: {
   *     // ... data to create a Prescricao
   *   }
   * })
   * 
   */
  create<T extends PrescricaoCreateArgs>(args: Prisma.SelectSubset<T, PrescricaoCreateArgs<ExtArgs>>): Prisma.Prisma__PrescricaoClient<runtime.Types.Result.GetResult<Prisma.$PrescricaoPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Prescricaos.
   * @param {PrescricaoCreateManyArgs} args - Arguments to create many Prescricaos.
   * @example
   * // Create many Prescricaos
   * const prescricao = await prisma.prescricao.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PrescricaoCreateManyArgs>(args?: Prisma.SelectSubset<T, PrescricaoCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Prescricaos and returns the data saved in the database.
   * @param {PrescricaoCreateManyAndReturnArgs} args - Arguments to create many Prescricaos.
   * @example
   * // Create many Prescricaos
   * const prescricao = await prisma.prescricao.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Prescricaos and only return the `id`
   * const prescricaoWithIdOnly = await prisma.prescricao.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PrescricaoCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PrescricaoCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PrescricaoPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Prescricao.
   * @param {PrescricaoDeleteArgs} args - Arguments to delete one Prescricao.
   * @example
   * // Delete one Prescricao
   * const Prescricao = await prisma.prescricao.delete({
   *   where: {
   *     // ... filter to delete one Prescricao
   *   }
   * })
   * 
   */
  delete<T extends PrescricaoDeleteArgs>(args: Prisma.SelectSubset<T, PrescricaoDeleteArgs<ExtArgs>>): Prisma.Prisma__PrescricaoClient<runtime.Types.Result.GetResult<Prisma.$PrescricaoPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Prescricao.
   * @param {PrescricaoUpdateArgs} args - Arguments to update one Prescricao.
   * @example
   * // Update one Prescricao
   * const prescricao = await prisma.prescricao.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PrescricaoUpdateArgs>(args: Prisma.SelectSubset<T, PrescricaoUpdateArgs<ExtArgs>>): Prisma.Prisma__PrescricaoClient<runtime.Types.Result.GetResult<Prisma.$PrescricaoPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Prescricaos.
   * @param {PrescricaoDeleteManyArgs} args - Arguments to filter Prescricaos to delete.
   * @example
   * // Delete a few Prescricaos
   * const { count } = await prisma.prescricao.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PrescricaoDeleteManyArgs>(args?: Prisma.SelectSubset<T, PrescricaoDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Prescricaos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PrescricaoUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Prescricaos
   * const prescricao = await prisma.prescricao.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PrescricaoUpdateManyArgs>(args: Prisma.SelectSubset<T, PrescricaoUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Prescricaos and returns the data updated in the database.
   * @param {PrescricaoUpdateManyAndReturnArgs} args - Arguments to update many Prescricaos.
   * @example
   * // Update many Prescricaos
   * const prescricao = await prisma.prescricao.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Prescricaos and only return the `id`
   * const prescricaoWithIdOnly = await prisma.prescricao.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PrescricaoUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PrescricaoUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PrescricaoPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Prescricao.
   * @param {PrescricaoUpsertArgs} args - Arguments to update or create a Prescricao.
   * @example
   * // Update or create a Prescricao
   * const prescricao = await prisma.prescricao.upsert({
   *   create: {
   *     // ... data to create a Prescricao
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Prescricao we want to update
   *   }
   * })
   */
  upsert<T extends PrescricaoUpsertArgs>(args: Prisma.SelectSubset<T, PrescricaoUpsertArgs<ExtArgs>>): Prisma.Prisma__PrescricaoClient<runtime.Types.Result.GetResult<Prisma.$PrescricaoPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Prescricaos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PrescricaoCountArgs} args - Arguments to filter Prescricaos to count.
   * @example
   * // Count the number of Prescricaos
   * const count = await prisma.prescricao.count({
   *   where: {
   *     // ... the filter for the Prescricaos we want to count
   *   }
   * })
  **/
  count<T extends PrescricaoCountArgs>(
    args?: Prisma.Subset<T, PrescricaoCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PrescricaoCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Prescricao.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PrescricaoAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PrescricaoAggregateArgs>(args: Prisma.Subset<T, PrescricaoAggregateArgs>): Prisma.PrismaPromise<GetPrescricaoAggregateType<T>>

  /**
   * Group by Prescricao.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PrescricaoGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PrescricaoGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PrescricaoGroupByArgs['orderBy'] }
      : { orderBy?: PrescricaoGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PrescricaoGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPrescricaoGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Prescricao model
 */
readonly fields: PrescricaoFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Prescricao.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PrescricaoClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  consulta<T extends Prisma.ConsultaDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ConsultaDefaultArgs<ExtArgs>>): Prisma.Prisma__ConsultaClient<runtime.Types.Result.GetResult<Prisma.$ConsultaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  profissional<T extends Prisma.ProfissionalDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProfissionalDefaultArgs<ExtArgs>>): Prisma.Prisma__ProfissionalClient<runtime.Types.Result.GetResult<Prisma.$ProfissionalPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Prescricao model
 */
export interface PrescricaoFieldRefs {
  readonly id: Prisma.FieldRef<"Prescricao", 'String'>
  readonly consultaId: Prisma.FieldRef<"Prescricao", 'String'>
  readonly profissionalId: Prisma.FieldRef<"Prescricao", 'String'>
  readonly medicamento: Prisma.FieldRef<"Prescricao", 'String'>
  readonly dosagem: Prisma.FieldRef<"Prescricao", 'String'>
  readonly instrucoes: Prisma.FieldRef<"Prescricao", 'String'>
  readonly dataEmissao: Prisma.FieldRef<"Prescricao", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"Prescricao", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Prescricao", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Prescricao findUnique
 */
export type PrescricaoFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Prescricao
   */
  select?: Prisma.PrescricaoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Prescricao
   */
  omit?: Prisma.PrescricaoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PrescricaoInclude<ExtArgs> | null
  /**
   * Filter, which Prescricao to fetch.
   */
  where: Prisma.PrescricaoWhereUniqueInput
}

/**
 * Prescricao findUniqueOrThrow
 */
export type PrescricaoFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Prescricao
   */
  select?: Prisma.PrescricaoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Prescricao
   */
  omit?: Prisma.PrescricaoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PrescricaoInclude<ExtArgs> | null
  /**
   * Filter, which Prescricao to fetch.
   */
  where: Prisma.PrescricaoWhereUniqueInput
}

/**
 * Prescricao findFirst
 */
export type PrescricaoFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Prescricao
   */
  select?: Prisma.PrescricaoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Prescricao
   */
  omit?: Prisma.PrescricaoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PrescricaoInclude<ExtArgs> | null
  /**
   * Filter, which Prescricao to fetch.
   */
  where?: Prisma.PrescricaoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Prescricaos to fetch.
   */
  orderBy?: Prisma.PrescricaoOrderByWithRelationInput | Prisma.PrescricaoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Prescricaos.
   */
  cursor?: Prisma.PrescricaoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Prescricaos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Prescricaos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Prescricaos.
   */
  distinct?: Prisma.PrescricaoScalarFieldEnum | Prisma.PrescricaoScalarFieldEnum[]
}

/**
 * Prescricao findFirstOrThrow
 */
export type PrescricaoFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Prescricao
   */
  select?: Prisma.PrescricaoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Prescricao
   */
  omit?: Prisma.PrescricaoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PrescricaoInclude<ExtArgs> | null
  /**
   * Filter, which Prescricao to fetch.
   */
  where?: Prisma.PrescricaoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Prescricaos to fetch.
   */
  orderBy?: Prisma.PrescricaoOrderByWithRelationInput | Prisma.PrescricaoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Prescricaos.
   */
  cursor?: Prisma.PrescricaoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Prescricaos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Prescricaos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Prescricaos.
   */
  distinct?: Prisma.PrescricaoScalarFieldEnum | Prisma.PrescricaoScalarFieldEnum[]
}

/**
 * Prescricao findMany
 */
export type PrescricaoFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Prescricao
   */
  select?: Prisma.PrescricaoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Prescricao
   */
  omit?: Prisma.PrescricaoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PrescricaoInclude<ExtArgs> | null
  /**
   * Filter, which Prescricaos to fetch.
   */
  where?: Prisma.PrescricaoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Prescricaos to fetch.
   */
  orderBy?: Prisma.PrescricaoOrderByWithRelationInput | Prisma.PrescricaoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Prescricaos.
   */
  cursor?: Prisma.PrescricaoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Prescricaos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Prescricaos.
   */
  skip?: number
  distinct?: Prisma.PrescricaoScalarFieldEnum | Prisma.PrescricaoScalarFieldEnum[]
}

/**
 * Prescricao create
 */
export type PrescricaoCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Prescricao
   */
  select?: Prisma.PrescricaoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Prescricao
   */
  omit?: Prisma.PrescricaoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PrescricaoInclude<ExtArgs> | null
  /**
   * The data needed to create a Prescricao.
   */
  data: Prisma.XOR<Prisma.PrescricaoCreateInput, Prisma.PrescricaoUncheckedCreateInput>
}

/**
 * Prescricao createMany
 */
export type PrescricaoCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Prescricaos.
   */
  data: Prisma.PrescricaoCreateManyInput | Prisma.PrescricaoCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Prescricao createManyAndReturn
 */
export type PrescricaoCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Prescricao
   */
  select?: Prisma.PrescricaoSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Prescricao
   */
  omit?: Prisma.PrescricaoOmit<ExtArgs> | null
  /**
   * The data used to create many Prescricaos.
   */
  data: Prisma.PrescricaoCreateManyInput | Prisma.PrescricaoCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PrescricaoIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Prescricao update
 */
export type PrescricaoUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Prescricao
   */
  select?: Prisma.PrescricaoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Prescricao
   */
  omit?: Prisma.PrescricaoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PrescricaoInclude<ExtArgs> | null
  /**
   * The data needed to update a Prescricao.
   */
  data: Prisma.XOR<Prisma.PrescricaoUpdateInput, Prisma.PrescricaoUncheckedUpdateInput>
  /**
   * Choose, which Prescricao to update.
   */
  where: Prisma.PrescricaoWhereUniqueInput
}

/**
 * Prescricao updateMany
 */
export type PrescricaoUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Prescricaos.
   */
  data: Prisma.XOR<Prisma.PrescricaoUpdateManyMutationInput, Prisma.PrescricaoUncheckedUpdateManyInput>
  /**
   * Filter which Prescricaos to update
   */
  where?: Prisma.PrescricaoWhereInput
  /**
   * Limit how many Prescricaos to update.
   */
  limit?: number
}

/**
 * Prescricao updateManyAndReturn
 */
export type PrescricaoUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Prescricao
   */
  select?: Prisma.PrescricaoSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Prescricao
   */
  omit?: Prisma.PrescricaoOmit<ExtArgs> | null
  /**
   * The data used to update Prescricaos.
   */
  data: Prisma.XOR<Prisma.PrescricaoUpdateManyMutationInput, Prisma.PrescricaoUncheckedUpdateManyInput>
  /**
   * Filter which Prescricaos to update
   */
  where?: Prisma.PrescricaoWhereInput
  /**
   * Limit how many Prescricaos to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PrescricaoIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Prescricao upsert
 */
export type PrescricaoUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Prescricao
   */
  select?: Prisma.PrescricaoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Prescricao
   */
  omit?: Prisma.PrescricaoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PrescricaoInclude<ExtArgs> | null
  /**
   * The filter to search for the Prescricao to update in case it exists.
   */
  where: Prisma.PrescricaoWhereUniqueInput
  /**
   * In case the Prescricao found by the `where` argument doesn't exist, create a new Prescricao with this data.
   */
  create: Prisma.XOR<Prisma.PrescricaoCreateInput, Prisma.PrescricaoUncheckedCreateInput>
  /**
   * In case the Prescricao was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PrescricaoUpdateInput, Prisma.PrescricaoUncheckedUpdateInput>
}

/**
 * Prescricao delete
 */
export type PrescricaoDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Prescricao
   */
  select?: Prisma.PrescricaoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Prescricao
   */
  omit?: Prisma.PrescricaoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PrescricaoInclude<ExtArgs> | null
  /**
   * Filter which Prescricao to delete.
   */
  where: Prisma.PrescricaoWhereUniqueInput
}

/**
 * Prescricao deleteMany
 */
export type PrescricaoDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Prescricaos to delete
   */
  where?: Prisma.PrescricaoWhereInput
  /**
   * Limit how many Prescricaos to delete.
   */
  limit?: number
}

/**
 * Prescricao without action
 */
export type PrescricaoDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Prescricao
   */
  select?: Prisma.PrescricaoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Prescricao
   */
  omit?: Prisma.PrescricaoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PrescricaoInclude<ExtArgs> | null
}
