
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Profissional` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Profissional
 * 
 */
export type ProfissionalModel = runtime.Types.Result.DefaultSelection<Prisma.$ProfissionalPayload>

export type AggregateProfissional = {
  _count: ProfissionalCountAggregateOutputType | null
  _min: ProfissionalMinAggregateOutputType | null
  _max: ProfissionalMaxAggregateOutputType | null
}

export type ProfissionalMinAggregateOutputType = {
  id: string | null
  usuarioId: string | null
  nome: string | null
  registroConselho: string | null
  especialidade: string | null
  tipo: $Enums.TipoProfissional | null
  unidadeId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ProfissionalMaxAggregateOutputType = {
  id: string | null
  usuarioId: string | null
  nome: string | null
  registroConselho: string | null
  especialidade: string | null
  tipo: $Enums.TipoProfissional | null
  unidadeId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ProfissionalCountAggregateOutputType = {
  id: number
  usuarioId: number
  nome: number
  registroConselho: number
  especialidade: number
  tipo: number
  unidadeId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ProfissionalMinAggregateInputType = {
  id?: true
  usuarioId?: true
  nome?: true
  registroConselho?: true
  especialidade?: true
  tipo?: true
  unidadeId?: true
  createdAt?: true
  updatedAt?: true
}

export type ProfissionalMaxAggregateInputType = {
  id?: true
  usuarioId?: true
  nome?: true
  registroConselho?: true
  especialidade?: true
  tipo?: true
  unidadeId?: true
  createdAt?: true
  updatedAt?: true
}

export type ProfissionalCountAggregateInputType = {
  id?: true
  usuarioId?: true
  nome?: true
  registroConselho?: true
  especialidade?: true
  tipo?: true
  unidadeId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ProfissionalAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Profissional to aggregate.
   */
  where?: Prisma.ProfissionalWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Profissionals to fetch.
   */
  orderBy?: Prisma.ProfissionalOrderByWithRelationInput | Prisma.ProfissionalOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProfissionalWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Profissionals from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Profissionals.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Profissionals
  **/
  _count?: true | ProfissionalCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProfissionalMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProfissionalMaxAggregateInputType
}

export type GetProfissionalAggregateType<T extends ProfissionalAggregateArgs> = {
      [P in keyof T & keyof AggregateProfissional]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProfissional[P]>
    : Prisma.GetScalarType<T[P], AggregateProfissional[P]>
}




export type ProfissionalGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProfissionalWhereInput
  orderBy?: Prisma.ProfissionalOrderByWithAggregationInput | Prisma.ProfissionalOrderByWithAggregationInput[]
  by: Prisma.ProfissionalScalarFieldEnum[] | Prisma.ProfissionalScalarFieldEnum
  having?: Prisma.ProfissionalScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProfissionalCountAggregateInputType | true
  _min?: ProfissionalMinAggregateInputType
  _max?: ProfissionalMaxAggregateInputType
}

export type ProfissionalGroupByOutputType = {
  id: string
  usuarioId: string
  nome: string
  registroConselho: string
  especialidade: string
  tipo: $Enums.TipoProfissional
  unidadeId: string | null
  createdAt: Date
  updatedAt: Date
  _count: ProfissionalCountAggregateOutputType | null
  _min: ProfissionalMinAggregateOutputType | null
  _max: ProfissionalMaxAggregateOutputType | null
}

type GetProfissionalGroupByPayload<T extends ProfissionalGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProfissionalGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProfissionalGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProfissionalGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProfissionalGroupByOutputType[P]>
      }
    >
  >



export type ProfissionalWhereInput = {
  AND?: Prisma.ProfissionalWhereInput | Prisma.ProfissionalWhereInput[]
  OR?: Prisma.ProfissionalWhereInput[]
  NOT?: Prisma.ProfissionalWhereInput | Prisma.ProfissionalWhereInput[]
  id?: Prisma.StringFilter<"Profissional"> | string
  usuarioId?: Prisma.StringFilter<"Profissional"> | string
  nome?: Prisma.StringFilter<"Profissional"> | string
  registroConselho?: Prisma.StringFilter<"Profissional"> | string
  especialidade?: Prisma.StringFilter<"Profissional"> | string
  tipo?: Prisma.EnumTipoProfissionalFilter<"Profissional"> | $Enums.TipoProfissional
  unidadeId?: Prisma.StringNullableFilter<"Profissional"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Profissional"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Profissional"> | Date | string
  usuario?: Prisma.XOR<Prisma.UsuarioScalarRelationFilter, Prisma.UsuarioWhereInput>
  unidade?: Prisma.XOR<Prisma.UnidadeHospitalarNullableScalarRelationFilter, Prisma.UnidadeHospitalarWhereInput> | null
  consultas?: Prisma.ConsultaListRelationFilter
  prescricoes?: Prisma.PrescricaoListRelationFilter
  agendas?: Prisma.AgendaListRelationFilter
}

export type ProfissionalOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  usuarioId?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  registroConselho?: Prisma.SortOrder
  especialidade?: Prisma.SortOrder
  tipo?: Prisma.SortOrder
  unidadeId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  usuario?: Prisma.UsuarioOrderByWithRelationInput
  unidade?: Prisma.UnidadeHospitalarOrderByWithRelationInput
  consultas?: Prisma.ConsultaOrderByRelationAggregateInput
  prescricoes?: Prisma.PrescricaoOrderByRelationAggregateInput
  agendas?: Prisma.AgendaOrderByRelationAggregateInput
}

export type ProfissionalWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  usuarioId?: string
  AND?: Prisma.ProfissionalWhereInput | Prisma.ProfissionalWhereInput[]
  OR?: Prisma.ProfissionalWhereInput[]
  NOT?: Prisma.ProfissionalWhereInput | Prisma.ProfissionalWhereInput[]
  nome?: Prisma.StringFilter<"Profissional"> | string
  registroConselho?: Prisma.StringFilter<"Profissional"> | string
  especialidade?: Prisma.StringFilter<"Profissional"> | string
  tipo?: Prisma.EnumTipoProfissionalFilter<"Profissional"> | $Enums.TipoProfissional
  unidadeId?: Prisma.StringNullableFilter<"Profissional"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Profissional"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Profissional"> | Date | string
  usuario?: Prisma.XOR<Prisma.UsuarioScalarRelationFilter, Prisma.UsuarioWhereInput>
  unidade?: Prisma.XOR<Prisma.UnidadeHospitalarNullableScalarRelationFilter, Prisma.UnidadeHospitalarWhereInput> | null
  consultas?: Prisma.ConsultaListRelationFilter
  prescricoes?: Prisma.PrescricaoListRelationFilter
  agendas?: Prisma.AgendaListRelationFilter
}, "id" | "usuarioId">

export type ProfissionalOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  usuarioId?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  registroConselho?: Prisma.SortOrder
  especialidade?: Prisma.SortOrder
  tipo?: Prisma.SortOrder
  unidadeId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ProfissionalCountOrderByAggregateInput
  _max?: Prisma.ProfissionalMaxOrderByAggregateInput
  _min?: Prisma.ProfissionalMinOrderByAggregateInput
}

export type ProfissionalScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProfissionalScalarWhereWithAggregatesInput | Prisma.ProfissionalScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProfissionalScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProfissionalScalarWhereWithAggregatesInput | Prisma.ProfissionalScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Profissional"> | string
  usuarioId?: Prisma.StringWithAggregatesFilter<"Profissional"> | string
  nome?: Prisma.StringWithAggregatesFilter<"Profissional"> | string
  registroConselho?: Prisma.StringWithAggregatesFilter<"Profissional"> | string
  especialidade?: Prisma.StringWithAggregatesFilter<"Profissional"> | string
  tipo?: Prisma.EnumTipoProfissionalWithAggregatesFilter<"Profissional"> | $Enums.TipoProfissional
  unidadeId?: Prisma.StringNullableWithAggregatesFilter<"Profissional"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Profissional"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Profissional"> | Date | string
}

export type ProfissionalCreateInput = {
  id?: string
  nome: string
  registroConselho: string
  especialidade: string
  tipo: $Enums.TipoProfissional
  createdAt?: Date | string
  updatedAt?: Date | string
  usuario: Prisma.UsuarioCreateNestedOneWithoutProfissionalInput
  unidade?: Prisma.UnidadeHospitalarCreateNestedOneWithoutProfissionaisInput
  consultas?: Prisma.ConsultaCreateNestedManyWithoutProfissionalInput
  prescricoes?: Prisma.PrescricaoCreateNestedManyWithoutProfissionalInput
  agendas?: Prisma.AgendaCreateNestedManyWithoutProfissionalInput
}

export type ProfissionalUncheckedCreateInput = {
  id?: string
  usuarioId: string
  nome: string
  registroConselho: string
  especialidade: string
  tipo: $Enums.TipoProfissional
  unidadeId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  consultas?: Prisma.ConsultaUncheckedCreateNestedManyWithoutProfissionalInput
  prescricoes?: Prisma.PrescricaoUncheckedCreateNestedManyWithoutProfissionalInput
  agendas?: Prisma.AgendaUncheckedCreateNestedManyWithoutProfissionalInput
}

export type ProfissionalUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  registroConselho?: Prisma.StringFieldUpdateOperationsInput | string
  especialidade?: Prisma.StringFieldUpdateOperationsInput | string
  tipo?: Prisma.EnumTipoProfissionalFieldUpdateOperationsInput | $Enums.TipoProfissional
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usuario?: Prisma.UsuarioUpdateOneRequiredWithoutProfissionalNestedInput
  unidade?: Prisma.UnidadeHospitalarUpdateOneWithoutProfissionaisNestedInput
  consultas?: Prisma.ConsultaUpdateManyWithoutProfissionalNestedInput
  prescricoes?: Prisma.PrescricaoUpdateManyWithoutProfissionalNestedInput
  agendas?: Prisma.AgendaUpdateManyWithoutProfissionalNestedInput
}

export type ProfissionalUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  usuarioId?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  registroConselho?: Prisma.StringFieldUpdateOperationsInput | string
  especialidade?: Prisma.StringFieldUpdateOperationsInput | string
  tipo?: Prisma.EnumTipoProfissionalFieldUpdateOperationsInput | $Enums.TipoProfissional
  unidadeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  consultas?: Prisma.ConsultaUncheckedUpdateManyWithoutProfissionalNestedInput
  prescricoes?: Prisma.PrescricaoUncheckedUpdateManyWithoutProfissionalNestedInput
  agendas?: Prisma.AgendaUncheckedUpdateManyWithoutProfissionalNestedInput
}

export type ProfissionalCreateManyInput = {
  id?: string
  usuarioId: string
  nome: string
  registroConselho: string
  especialidade: string
  tipo: $Enums.TipoProfissional
  unidadeId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ProfissionalUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  registroConselho?: Prisma.StringFieldUpdateOperationsInput | string
  especialidade?: Prisma.StringFieldUpdateOperationsInput | string
  tipo?: Prisma.EnumTipoProfissionalFieldUpdateOperationsInput | $Enums.TipoProfissional
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProfissionalUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  usuarioId?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  registroConselho?: Prisma.StringFieldUpdateOperationsInput | string
  especialidade?: Prisma.StringFieldUpdateOperationsInput | string
  tipo?: Prisma.EnumTipoProfissionalFieldUpdateOperationsInput | $Enums.TipoProfissional
  unidadeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProfissionalNullableScalarRelationFilter = {
  is?: Prisma.ProfissionalWhereInput | null
  isNot?: Prisma.ProfissionalWhereInput | null
}

export type ProfissionalCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  usuarioId?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  registroConselho?: Prisma.SortOrder
  especialidade?: Prisma.SortOrder
  tipo?: Prisma.SortOrder
  unidadeId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProfissionalMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  usuarioId?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  registroConselho?: Prisma.SortOrder
  especialidade?: Prisma.SortOrder
  tipo?: Prisma.SortOrder
  unidadeId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProfissionalMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  usuarioId?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  registroConselho?: Prisma.SortOrder
  especialidade?: Prisma.SortOrder
  tipo?: Prisma.SortOrder
  unidadeId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProfissionalScalarRelationFilter = {
  is?: Prisma.ProfissionalWhereInput
  isNot?: Prisma.ProfissionalWhereInput
}

export type ProfissionalListRelationFilter = {
  every?: Prisma.ProfissionalWhereInput
  some?: Prisma.ProfissionalWhereInput
  none?: Prisma.ProfissionalWhereInput
}

export type ProfissionalOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ProfissionalCreateNestedOneWithoutUsuarioInput = {
  create?: Prisma.XOR<Prisma.ProfissionalCreateWithoutUsuarioInput, Prisma.ProfissionalUncheckedCreateWithoutUsuarioInput>
  connectOrCreate?: Prisma.ProfissionalCreateOrConnectWithoutUsuarioInput
  connect?: Prisma.ProfissionalWhereUniqueInput
}

export type ProfissionalUncheckedCreateNestedOneWithoutUsuarioInput = {
  create?: Prisma.XOR<Prisma.ProfissionalCreateWithoutUsuarioInput, Prisma.ProfissionalUncheckedCreateWithoutUsuarioInput>
  connectOrCreate?: Prisma.ProfissionalCreateOrConnectWithoutUsuarioInput
  connect?: Prisma.ProfissionalWhereUniqueInput
}

export type ProfissionalUpdateOneWithoutUsuarioNestedInput = {
  create?: Prisma.XOR<Prisma.ProfissionalCreateWithoutUsuarioInput, Prisma.ProfissionalUncheckedCreateWithoutUsuarioInput>
  connectOrCreate?: Prisma.ProfissionalCreateOrConnectWithoutUsuarioInput
  upsert?: Prisma.ProfissionalUpsertWithoutUsuarioInput
  disconnect?: Prisma.ProfissionalWhereInput | boolean
  delete?: Prisma.ProfissionalWhereInput | boolean
  connect?: Prisma.ProfissionalWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProfissionalUpdateToOneWithWhereWithoutUsuarioInput, Prisma.ProfissionalUpdateWithoutUsuarioInput>, Prisma.ProfissionalUncheckedUpdateWithoutUsuarioInput>
}

export type ProfissionalUncheckedUpdateOneWithoutUsuarioNestedInput = {
  create?: Prisma.XOR<Prisma.ProfissionalCreateWithoutUsuarioInput, Prisma.ProfissionalUncheckedCreateWithoutUsuarioInput>
  connectOrCreate?: Prisma.ProfissionalCreateOrConnectWithoutUsuarioInput
  upsert?: Prisma.ProfissionalUpsertWithoutUsuarioInput
  disconnect?: Prisma.ProfissionalWhereInput | boolean
  delete?: Prisma.ProfissionalWhereInput | boolean
  connect?: Prisma.ProfissionalWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProfissionalUpdateToOneWithWhereWithoutUsuarioInput, Prisma.ProfissionalUpdateWithoutUsuarioInput>, Prisma.ProfissionalUncheckedUpdateWithoutUsuarioInput>
}

export type EnumTipoProfissionalFieldUpdateOperationsInput = {
  set?: $Enums.TipoProfissional
}

export type ProfissionalCreateNestedOneWithoutAgendasInput = {
  create?: Prisma.XOR<Prisma.ProfissionalCreateWithoutAgendasInput, Prisma.ProfissionalUncheckedCreateWithoutAgendasInput>
  connectOrCreate?: Prisma.ProfissionalCreateOrConnectWithoutAgendasInput
  connect?: Prisma.ProfissionalWhereUniqueInput
}

export type ProfissionalUpdateOneRequiredWithoutAgendasNestedInput = {
  create?: Prisma.XOR<Prisma.ProfissionalCreateWithoutAgendasInput, Prisma.ProfissionalUncheckedCreateWithoutAgendasInput>
  connectOrCreate?: Prisma.ProfissionalCreateOrConnectWithoutAgendasInput
  upsert?: Prisma.ProfissionalUpsertWithoutAgendasInput
  connect?: Prisma.ProfissionalWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProfissionalUpdateToOneWithWhereWithoutAgendasInput, Prisma.ProfissionalUpdateWithoutAgendasInput>, Prisma.ProfissionalUncheckedUpdateWithoutAgendasInput>
}

export type ProfissionalCreateNestedOneWithoutConsultasInput = {
  create?: Prisma.XOR<Prisma.ProfissionalCreateWithoutConsultasInput, Prisma.ProfissionalUncheckedCreateWithoutConsultasInput>
  connectOrCreate?: Prisma.ProfissionalCreateOrConnectWithoutConsultasInput
  connect?: Prisma.ProfissionalWhereUniqueInput
}

export type ProfissionalUpdateOneRequiredWithoutConsultasNestedInput = {
  create?: Prisma.XOR<Prisma.ProfissionalCreateWithoutConsultasInput, Prisma.ProfissionalUncheckedCreateWithoutConsultasInput>
  connectOrCreate?: Prisma.ProfissionalCreateOrConnectWithoutConsultasInput
  upsert?: Prisma.ProfissionalUpsertWithoutConsultasInput
  connect?: Prisma.ProfissionalWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProfissionalUpdateToOneWithWhereWithoutConsultasInput, Prisma.ProfissionalUpdateWithoutConsultasInput>, Prisma.ProfissionalUncheckedUpdateWithoutConsultasInput>
}

export type ProfissionalCreateNestedOneWithoutPrescricoesInput = {
  create?: Prisma.XOR<Prisma.ProfissionalCreateWithoutPrescricoesInput, Prisma.ProfissionalUncheckedCreateWithoutPrescricoesInput>
  connectOrCreate?: Prisma.ProfissionalCreateOrConnectWithoutPrescricoesInput
  connect?: Prisma.ProfissionalWhereUniqueInput
}

export type ProfissionalUpdateOneRequiredWithoutPrescricoesNestedInput = {
  create?: Prisma.XOR<Prisma.ProfissionalCreateWithoutPrescricoesInput, Prisma.ProfissionalUncheckedCreateWithoutPrescricoesInput>
  connectOrCreate?: Prisma.ProfissionalCreateOrConnectWithoutPrescricoesInput
  upsert?: Prisma.ProfissionalUpsertWithoutPrescricoesInput
  connect?: Prisma.ProfissionalWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProfissionalUpdateToOneWithWhereWithoutPrescricoesInput, Prisma.ProfissionalUpdateWithoutPrescricoesInput>, Prisma.ProfissionalUncheckedUpdateWithoutPrescricoesInput>
}

export type ProfissionalCreateNestedManyWithoutUnidadeInput = {
  create?: Prisma.XOR<Prisma.ProfissionalCreateWithoutUnidadeInput, Prisma.ProfissionalUncheckedCreateWithoutUnidadeInput> | Prisma.ProfissionalCreateWithoutUnidadeInput[] | Prisma.ProfissionalUncheckedCreateWithoutUnidadeInput[]
  connectOrCreate?: Prisma.ProfissionalCreateOrConnectWithoutUnidadeInput | Prisma.ProfissionalCreateOrConnectWithoutUnidadeInput[]
  createMany?: Prisma.ProfissionalCreateManyUnidadeInputEnvelope
  connect?: Prisma.ProfissionalWhereUniqueInput | Prisma.ProfissionalWhereUniqueInput[]
}

export type ProfissionalUncheckedCreateNestedManyWithoutUnidadeInput = {
  create?: Prisma.XOR<Prisma.ProfissionalCreateWithoutUnidadeInput, Prisma.ProfissionalUncheckedCreateWithoutUnidadeInput> | Prisma.ProfissionalCreateWithoutUnidadeInput[] | Prisma.ProfissionalUncheckedCreateWithoutUnidadeInput[]
  connectOrCreate?: Prisma.ProfissionalCreateOrConnectWithoutUnidadeInput | Prisma.ProfissionalCreateOrConnectWithoutUnidadeInput[]
  createMany?: Prisma.ProfissionalCreateManyUnidadeInputEnvelope
  connect?: Prisma.ProfissionalWhereUniqueInput | Prisma.ProfissionalWhereUniqueInput[]
}

export type ProfissionalUpdateManyWithoutUnidadeNestedInput = {
  create?: Prisma.XOR<Prisma.ProfissionalCreateWithoutUnidadeInput, Prisma.ProfissionalUncheckedCreateWithoutUnidadeInput> | Prisma.ProfissionalCreateWithoutUnidadeInput[] | Prisma.ProfissionalUncheckedCreateWithoutUnidadeInput[]
  connectOrCreate?: Prisma.ProfissionalCreateOrConnectWithoutUnidadeInput | Prisma.ProfissionalCreateOrConnectWithoutUnidadeInput[]
  upsert?: Prisma.ProfissionalUpsertWithWhereUniqueWithoutUnidadeInput | Prisma.ProfissionalUpsertWithWhereUniqueWithoutUnidadeInput[]
  createMany?: Prisma.ProfissionalCreateManyUnidadeInputEnvelope
  set?: Prisma.ProfissionalWhereUniqueInput | Prisma.ProfissionalWhereUniqueInput[]
  disconnect?: Prisma.ProfissionalWhereUniqueInput | Prisma.ProfissionalWhereUniqueInput[]
  delete?: Prisma.ProfissionalWhereUniqueInput | Prisma.ProfissionalWhereUniqueInput[]
  connect?: Prisma.ProfissionalWhereUniqueInput | Prisma.ProfissionalWhereUniqueInput[]
  update?: Prisma.ProfissionalUpdateWithWhereUniqueWithoutUnidadeInput | Prisma.ProfissionalUpdateWithWhereUniqueWithoutUnidadeInput[]
  updateMany?: Prisma.ProfissionalUpdateManyWithWhereWithoutUnidadeInput | Prisma.ProfissionalUpdateManyWithWhereWithoutUnidadeInput[]
  deleteMany?: Prisma.ProfissionalScalarWhereInput | Prisma.ProfissionalScalarWhereInput[]
}

export type ProfissionalUncheckedUpdateManyWithoutUnidadeNestedInput = {
  create?: Prisma.XOR<Prisma.ProfissionalCreateWithoutUnidadeInput, Prisma.ProfissionalUncheckedCreateWithoutUnidadeInput> | Prisma.ProfissionalCreateWithoutUnidadeInput[] | Prisma.ProfissionalUncheckedCreateWithoutUnidadeInput[]
  connectOrCreate?: Prisma.ProfissionalCreateOrConnectWithoutUnidadeInput | Prisma.ProfissionalCreateOrConnectWithoutUnidadeInput[]
  upsert?: Prisma.ProfissionalUpsertWithWhereUniqueWithoutUnidadeInput | Prisma.ProfissionalUpsertWithWhereUniqueWithoutUnidadeInput[]
  createMany?: Prisma.ProfissionalCreateManyUnidadeInputEnvelope
  set?: Prisma.ProfissionalWhereUniqueInput | Prisma.ProfissionalWhereUniqueInput[]
  disconnect?: Prisma.ProfissionalWhereUniqueInput | Prisma.ProfissionalWhereUniqueInput[]
  delete?: Prisma.ProfissionalWhereUniqueInput | Prisma.ProfissionalWhereUniqueInput[]
  connect?: Prisma.ProfissionalWhereUniqueInput | Prisma.ProfissionalWhereUniqueInput[]
  update?: Prisma.ProfissionalUpdateWithWhereUniqueWithoutUnidadeInput | Prisma.ProfissionalUpdateWithWhereUniqueWithoutUnidadeInput[]
  updateMany?: Prisma.ProfissionalUpdateManyWithWhereWithoutUnidadeInput | Prisma.ProfissionalUpdateManyWithWhereWithoutUnidadeInput[]
  deleteMany?: Prisma.ProfissionalScalarWhereInput | Prisma.ProfissionalScalarWhereInput[]
}

export type ProfissionalCreateWithoutUsuarioInput = {
  id?: string
  nome: string
  registroConselho: string
  especialidade: string
  tipo: $Enums.TipoProfissional
  createdAt?: Date | string
  updatedAt?: Date | string
  unidade?: Prisma.UnidadeHospitalarCreateNestedOneWithoutProfissionaisInput
  consultas?: Prisma.ConsultaCreateNestedManyWithoutProfissionalInput
  prescricoes?: Prisma.PrescricaoCreateNestedManyWithoutProfissionalInput
  agendas?: Prisma.AgendaCreateNestedManyWithoutProfissionalInput
}

export type ProfissionalUncheckedCreateWithoutUsuarioInput = {
  id?: string
  nome: string
  registroConselho: string
  especialidade: string
  tipo: $Enums.TipoProfissional
  unidadeId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  consultas?: Prisma.ConsultaUncheckedCreateNestedManyWithoutProfissionalInput
  prescricoes?: Prisma.PrescricaoUncheckedCreateNestedManyWithoutProfissionalInput
  agendas?: Prisma.AgendaUncheckedCreateNestedManyWithoutProfissionalInput
}

export type ProfissionalCreateOrConnectWithoutUsuarioInput = {
  where: Prisma.ProfissionalWhereUniqueInput
  create: Prisma.XOR<Prisma.ProfissionalCreateWithoutUsuarioInput, Prisma.ProfissionalUncheckedCreateWithoutUsuarioInput>
}

export type ProfissionalUpsertWithoutUsuarioInput = {
  update: Prisma.XOR<Prisma.ProfissionalUpdateWithoutUsuarioInput, Prisma.ProfissionalUncheckedUpdateWithoutUsuarioInput>
  create: Prisma.XOR<Prisma.ProfissionalCreateWithoutUsuarioInput, Prisma.ProfissionalUncheckedCreateWithoutUsuarioInput>
  where?: Prisma.ProfissionalWhereInput
}

export type ProfissionalUpdateToOneWithWhereWithoutUsuarioInput = {
  where?: Prisma.ProfissionalWhereInput
  data: Prisma.XOR<Prisma.ProfissionalUpdateWithoutUsuarioInput, Prisma.ProfissionalUncheckedUpdateWithoutUsuarioInput>
}

export type ProfissionalUpdateWithoutUsuarioInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  registroConselho?: Prisma.StringFieldUpdateOperationsInput | string
  especialidade?: Prisma.StringFieldUpdateOperationsInput | string
  tipo?: Prisma.EnumTipoProfissionalFieldUpdateOperationsInput | $Enums.TipoProfissional
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  unidade?: Prisma.UnidadeHospitalarUpdateOneWithoutProfissionaisNestedInput
  consultas?: Prisma.ConsultaUpdateManyWithoutProfissionalNestedInput
  prescricoes?: Prisma.PrescricaoUpdateManyWithoutProfissionalNestedInput
  agendas?: Prisma.AgendaUpdateManyWithoutProfissionalNestedInput
}

export type ProfissionalUncheckedUpdateWithoutUsuarioInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  registroConselho?: Prisma.StringFieldUpdateOperationsInput | string
  especialidade?: Prisma.StringFieldUpdateOperationsInput | string
  tipo?: Prisma.EnumTipoProfissionalFieldUpdateOperationsInput | $Enums.TipoProfissional
  unidadeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  consultas?: Prisma.ConsultaUncheckedUpdateManyWithoutProfissionalNestedInput
  prescricoes?: Prisma.PrescricaoUncheckedUpdateManyWithoutProfissionalNestedInput
  agendas?: Prisma.AgendaUncheckedUpdateManyWithoutProfissionalNestedInput
}

export type ProfissionalCreateWithoutAgendasInput = {
  id?: string
  nome: string
  registroConselho: string
  especialidade: string
  tipo: $Enums.TipoProfissional
  createdAt?: Date | string
  updatedAt?: Date | string
  usuario: Prisma.UsuarioCreateNestedOneWithoutProfissionalInput
  unidade?: Prisma.UnidadeHospitalarCreateNestedOneWithoutProfissionaisInput
  consultas?: Prisma.ConsultaCreateNestedManyWithoutProfissionalInput
  prescricoes?: Prisma.PrescricaoCreateNestedManyWithoutProfissionalInput
}

export type ProfissionalUncheckedCreateWithoutAgendasInput = {
  id?: string
  usuarioId: string
  nome: string
  registroConselho: string
  especialidade: string
  tipo: $Enums.TipoProfissional
  unidadeId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  consultas?: Prisma.ConsultaUncheckedCreateNestedManyWithoutProfissionalInput
  prescricoes?: Prisma.PrescricaoUncheckedCreateNestedManyWithoutProfissionalInput
}

export type ProfissionalCreateOrConnectWithoutAgendasInput = {
  where: Prisma.ProfissionalWhereUniqueInput
  create: Prisma.XOR<Prisma.ProfissionalCreateWithoutAgendasInput, Prisma.ProfissionalUncheckedCreateWithoutAgendasInput>
}

export type ProfissionalUpsertWithoutAgendasInput = {
  update: Prisma.XOR<Prisma.ProfissionalUpdateWithoutAgendasInput, Prisma.ProfissionalUncheckedUpdateWithoutAgendasInput>
  create: Prisma.XOR<Prisma.ProfissionalCreateWithoutAgendasInput, Prisma.ProfissionalUncheckedCreateWithoutAgendasInput>
  where?: Prisma.ProfissionalWhereInput
}

export type ProfissionalUpdateToOneWithWhereWithoutAgendasInput = {
  where?: Prisma.ProfissionalWhereInput
  data: Prisma.XOR<Prisma.ProfissionalUpdateWithoutAgendasInput, Prisma.ProfissionalUncheckedUpdateWithoutAgendasInput>
}

export type ProfissionalUpdateWithoutAgendasInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  registroConselho?: Prisma.StringFieldUpdateOperationsInput | string
  especialidade?: Prisma.StringFieldUpdateOperationsInput | string
  tipo?: Prisma.EnumTipoProfissionalFieldUpdateOperationsInput | $Enums.TipoProfissional
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usuario?: Prisma.UsuarioUpdateOneRequiredWithoutProfissionalNestedInput
  unidade?: Prisma.UnidadeHospitalarUpdateOneWithoutProfissionaisNestedInput
  consultas?: Prisma.ConsultaUpdateManyWithoutProfissionalNestedInput
  prescricoes?: Prisma.PrescricaoUpdateManyWithoutProfissionalNestedInput
}

export type ProfissionalUncheckedUpdateWithoutAgendasInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  usuarioId?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  registroConselho?: Prisma.StringFieldUpdateOperationsInput | string
  especialidade?: Prisma.StringFieldUpdateOperationsInput | string
  tipo?: Prisma.EnumTipoProfissionalFieldUpdateOperationsInput | $Enums.TipoProfissional
  unidadeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  consultas?: Prisma.ConsultaUncheckedUpdateManyWithoutProfissionalNestedInput
  prescricoes?: Prisma.PrescricaoUncheckedUpdateManyWithoutProfissionalNestedInput
}

export type ProfissionalCreateWithoutConsultasInput = {
  id?: string
  nome: string
  registroConselho: string
  especialidade: string
  tipo: $Enums.TipoProfissional
  createdAt?: Date | string
  updatedAt?: Date | string
  usuario: Prisma.UsuarioCreateNestedOneWithoutProfissionalInput
  unidade?: Prisma.UnidadeHospitalarCreateNestedOneWithoutProfissionaisInput
  prescricoes?: Prisma.PrescricaoCreateNestedManyWithoutProfissionalInput
  agendas?: Prisma.AgendaCreateNestedManyWithoutProfissionalInput
}

export type ProfissionalUncheckedCreateWithoutConsultasInput = {
  id?: string
  usuarioId: string
  nome: string
  registroConselho: string
  especialidade: string
  tipo: $Enums.TipoProfissional
  unidadeId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  prescricoes?: Prisma.PrescricaoUncheckedCreateNestedManyWithoutProfissionalInput
  agendas?: Prisma.AgendaUncheckedCreateNestedManyWithoutProfissionalInput
}

export type ProfissionalCreateOrConnectWithoutConsultasInput = {
  where: Prisma.ProfissionalWhereUniqueInput
  create: Prisma.XOR<Prisma.ProfissionalCreateWithoutConsultasInput, Prisma.ProfissionalUncheckedCreateWithoutConsultasInput>
}

export type ProfissionalUpsertWithoutConsultasInput = {
  update: Prisma.XOR<Prisma.ProfissionalUpdateWithoutConsultasInput, Prisma.ProfissionalUncheckedUpdateWithoutConsultasInput>
  create: Prisma.XOR<Prisma.ProfissionalCreateWithoutConsultasInput, Prisma.ProfissionalUncheckedCreateWithoutConsultasInput>
  where?: Prisma.ProfissionalWhereInput
}

export type ProfissionalUpdateToOneWithWhereWithoutConsultasInput = {
  where?: Prisma.ProfissionalWhereInput
  data: Prisma.XOR<Prisma.ProfissionalUpdateWithoutConsultasInput, Prisma.ProfissionalUncheckedUpdateWithoutConsultasInput>
}

export type ProfissionalUpdateWithoutConsultasInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  registroConselho?: Prisma.StringFieldUpdateOperationsInput | string
  especialidade?: Prisma.StringFieldUpdateOperationsInput | string
  tipo?: Prisma.EnumTipoProfissionalFieldUpdateOperationsInput | $Enums.TipoProfissional
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usuario?: Prisma.UsuarioUpdateOneRequiredWithoutProfissionalNestedInput
  unidade?: Prisma.UnidadeHospitalarUpdateOneWithoutProfissionaisNestedInput
  prescricoes?: Prisma.PrescricaoUpdateManyWithoutProfissionalNestedInput
  agendas?: Prisma.AgendaUpdateManyWithoutProfissionalNestedInput
}

export type ProfissionalUncheckedUpdateWithoutConsultasInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  usuarioId?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  registroConselho?: Prisma.StringFieldUpdateOperationsInput | string
  especialidade?: Prisma.StringFieldUpdateOperationsInput | string
  tipo?: Prisma.EnumTipoProfissionalFieldUpdateOperationsInput | $Enums.TipoProfissional
  unidadeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  prescricoes?: Prisma.PrescricaoUncheckedUpdateManyWithoutProfissionalNestedInput
  agendas?: Prisma.AgendaUncheckedUpdateManyWithoutProfissionalNestedInput
}

export type ProfissionalCreateWithoutPrescricoesInput = {
  id?: string
  nome: string
  registroConselho: string
  especialidade: string
  tipo: $Enums.TipoProfissional
  createdAt?: Date | string
  updatedAt?: Date | string
  usuario: Prisma.UsuarioCreateNestedOneWithoutProfissionalInput
  unidade?: Prisma.UnidadeHospitalarCreateNestedOneWithoutProfissionaisInput
  consultas?: Prisma.ConsultaCreateNestedManyWithoutProfissionalInput
  agendas?: Prisma.AgendaCreateNestedManyWithoutProfissionalInput
}

export type ProfissionalUncheckedCreateWithoutPrescricoesInput = {
  id?: string
  usuarioId: string
  nome: string
  registroConselho: string
  especialidade: string
  tipo: $Enums.TipoProfissional
  unidadeId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  consultas?: Prisma.ConsultaUncheckedCreateNestedManyWithoutProfissionalInput
  agendas?: Prisma.AgendaUncheckedCreateNestedManyWithoutProfissionalInput
}

export type ProfissionalCreateOrConnectWithoutPrescricoesInput = {
  where: Prisma.ProfissionalWhereUniqueInput
  create: Prisma.XOR<Prisma.ProfissionalCreateWithoutPrescricoesInput, Prisma.ProfissionalUncheckedCreateWithoutPrescricoesInput>
}

export type ProfissionalUpsertWithoutPrescricoesInput = {
  update: Prisma.XOR<Prisma.ProfissionalUpdateWithoutPrescricoesInput, Prisma.ProfissionalUncheckedUpdateWithoutPrescricoesInput>
  create: Prisma.XOR<Prisma.ProfissionalCreateWithoutPrescricoesInput, Prisma.ProfissionalUncheckedCreateWithoutPrescricoesInput>
  where?: Prisma.ProfissionalWhereInput
}

export type ProfissionalUpdateToOneWithWhereWithoutPrescricoesInput = {
  where?: Prisma.ProfissionalWhereInput
  data: Prisma.XOR<Prisma.ProfissionalUpdateWithoutPrescricoesInput, Prisma.ProfissionalUncheckedUpdateWithoutPrescricoesInput>
}

export type ProfissionalUpdateWithoutPrescricoesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  registroConselho?: Prisma.StringFieldUpdateOperationsInput | string
  especialidade?: Prisma.StringFieldUpdateOperationsInput | string
  tipo?: Prisma.EnumTipoProfissionalFieldUpdateOperationsInput | $Enums.TipoProfissional
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usuario?: Prisma.UsuarioUpdateOneRequiredWithoutProfissionalNestedInput
  unidade?: Prisma.UnidadeHospitalarUpdateOneWithoutProfissionaisNestedInput
  consultas?: Prisma.ConsultaUpdateManyWithoutProfissionalNestedInput
  agendas?: Prisma.AgendaUpdateManyWithoutProfissionalNestedInput
}

export type ProfissionalUncheckedUpdateWithoutPrescricoesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  usuarioId?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  registroConselho?: Prisma.StringFieldUpdateOperationsInput | string
  especialidade?: Prisma.StringFieldUpdateOperationsInput | string
  tipo?: Prisma.EnumTipoProfissionalFieldUpdateOperationsInput | $Enums.TipoProfissional
  unidadeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  consultas?: Prisma.ConsultaUncheckedUpdateManyWithoutProfissionalNestedInput
  agendas?: Prisma.AgendaUncheckedUpdateManyWithoutProfissionalNestedInput
}

export type ProfissionalCreateWithoutUnidadeInput = {
  id?: string
  nome: string
  registroConselho: string
  especialidade: string
  tipo: $Enums.TipoProfissional
  createdAt?: Date | string
  updatedAt?: Date | string
  usuario: Prisma.UsuarioCreateNestedOneWithoutProfissionalInput
  consultas?: Prisma.ConsultaCreateNestedManyWithoutProfissionalInput
  prescricoes?: Prisma.PrescricaoCreateNestedManyWithoutProfissionalInput
  agendas?: Prisma.AgendaCreateNestedManyWithoutProfissionalInput
}

export type ProfissionalUncheckedCreateWithoutUnidadeInput = {
  id?: string
  usuarioId: string
  nome: string
  registroConselho: string
  especialidade: string
  tipo: $Enums.TipoProfissional
  createdAt?: Date | string
  updatedAt?: Date | string
  consultas?: Prisma.ConsultaUncheckedCreateNestedManyWithoutProfissionalInput
  prescricoes?: Prisma.PrescricaoUncheckedCreateNestedManyWithoutProfissionalInput
  agendas?: Prisma.AgendaUncheckedCreateNestedManyWithoutProfissionalInput
}

export type ProfissionalCreateOrConnectWithoutUnidadeInput = {
  where: Prisma.ProfissionalWhereUniqueInput
  create: Prisma.XOR<Prisma.ProfissionalCreateWithoutUnidadeInput, Prisma.ProfissionalUncheckedCreateWithoutUnidadeInput>
}

export type ProfissionalCreateManyUnidadeInputEnvelope = {
  data: Prisma.ProfissionalCreateManyUnidadeInput | Prisma.ProfissionalCreateManyUnidadeInput[]
  skipDuplicates?: boolean
}

export type ProfissionalUpsertWithWhereUniqueWithoutUnidadeInput = {
  where: Prisma.ProfissionalWhereUniqueInput
  update: Prisma.XOR<Prisma.ProfissionalUpdateWithoutUnidadeInput, Prisma.ProfissionalUncheckedUpdateWithoutUnidadeInput>
  create: Prisma.XOR<Prisma.ProfissionalCreateWithoutUnidadeInput, Prisma.ProfissionalUncheckedCreateWithoutUnidadeInput>
}

export type ProfissionalUpdateWithWhereUniqueWithoutUnidadeInput = {
  where: Prisma.ProfissionalWhereUniqueInput
  data: Prisma.XOR<Prisma.ProfissionalUpdateWithoutUnidadeInput, Prisma.ProfissionalUncheckedUpdateWithoutUnidadeInput>
}

export type ProfissionalUpdateManyWithWhereWithoutUnidadeInput = {
  where: Prisma.ProfissionalScalarWhereInput
  data: Prisma.XOR<Prisma.ProfissionalUpdateManyMutationInput, Prisma.ProfissionalUncheckedUpdateManyWithoutUnidadeInput>
}

export type ProfissionalScalarWhereInput = {
  AND?: Prisma.ProfissionalScalarWhereInput | Prisma.ProfissionalScalarWhereInput[]
  OR?: Prisma.ProfissionalScalarWhereInput[]
  NOT?: Prisma.ProfissionalScalarWhereInput | Prisma.ProfissionalScalarWhereInput[]
  id?: Prisma.StringFilter<"Profissional"> | string
  usuarioId?: Prisma.StringFilter<"Profissional"> | string
  nome?: Prisma.StringFilter<"Profissional"> | string
  registroConselho?: Prisma.StringFilter<"Profissional"> | string
  especialidade?: Prisma.StringFilter<"Profissional"> | string
  tipo?: Prisma.EnumTipoProfissionalFilter<"Profissional"> | $Enums.TipoProfissional
  unidadeId?: Prisma.StringNullableFilter<"Profissional"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Profissional"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Profissional"> | Date | string
}

export type ProfissionalCreateManyUnidadeInput = {
  id?: string
  usuarioId: string
  nome: string
  registroConselho: string
  especialidade: string
  tipo: $Enums.TipoProfissional
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ProfissionalUpdateWithoutUnidadeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  registroConselho?: Prisma.StringFieldUpdateOperationsInput | string
  especialidade?: Prisma.StringFieldUpdateOperationsInput | string
  tipo?: Prisma.EnumTipoProfissionalFieldUpdateOperationsInput | $Enums.TipoProfissional
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usuario?: Prisma.UsuarioUpdateOneRequiredWithoutProfissionalNestedInput
  consultas?: Prisma.ConsultaUpdateManyWithoutProfissionalNestedInput
  prescricoes?: Prisma.PrescricaoUpdateManyWithoutProfissionalNestedInput
  agendas?: Prisma.AgendaUpdateManyWithoutProfissionalNestedInput
}

export type ProfissionalUncheckedUpdateWithoutUnidadeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  usuarioId?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  registroConselho?: Prisma.StringFieldUpdateOperationsInput | string
  especialidade?: Prisma.StringFieldUpdateOperationsInput | string
  tipo?: Prisma.EnumTipoProfissionalFieldUpdateOperationsInput | $Enums.TipoProfissional
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  consultas?: Prisma.ConsultaUncheckedUpdateManyWithoutProfissionalNestedInput
  prescricoes?: Prisma.PrescricaoUncheckedUpdateManyWithoutProfissionalNestedInput
  agendas?: Prisma.AgendaUncheckedUpdateManyWithoutProfissionalNestedInput
}

export type ProfissionalUncheckedUpdateManyWithoutUnidadeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  usuarioId?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  registroConselho?: Prisma.StringFieldUpdateOperationsInput | string
  especialidade?: Prisma.StringFieldUpdateOperationsInput | string
  tipo?: Prisma.EnumTipoProfissionalFieldUpdateOperationsInput | $Enums.TipoProfissional
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type ProfissionalCountOutputType
 */

export type ProfissionalCountOutputType = {
  consultas: number
  prescricoes: number
  agendas: number
}

export type ProfissionalCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  consultas?: boolean | ProfissionalCountOutputTypeCountConsultasArgs
  prescricoes?: boolean | ProfissionalCountOutputTypeCountPrescricoesArgs
  agendas?: boolean | ProfissionalCountOutputTypeCountAgendasArgs
}

/**
 * ProfissionalCountOutputType without action
 */
export type ProfissionalCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProfissionalCountOutputType
   */
  select?: Prisma.ProfissionalCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ProfissionalCountOutputType without action
 */
export type ProfissionalCountOutputTypeCountConsultasArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ConsultaWhereInput
}

/**
 * ProfissionalCountOutputType without action
 */
export type ProfissionalCountOutputTypeCountPrescricoesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PrescricaoWhereInput
}

/**
 * ProfissionalCountOutputType without action
 */
export type ProfissionalCountOutputTypeCountAgendasArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AgendaWhereInput
}


export type ProfissionalSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  usuarioId?: boolean
  nome?: boolean
  registroConselho?: boolean
  especialidade?: boolean
  tipo?: boolean
  unidadeId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  usuario?: boolean | Prisma.UsuarioDefaultArgs<ExtArgs>
  unidade?: boolean | Prisma.Profissional$unidadeArgs<ExtArgs>
  consultas?: boolean | Prisma.Profissional$consultasArgs<ExtArgs>
  prescricoes?: boolean | Prisma.Profissional$prescricoesArgs<ExtArgs>
  agendas?: boolean | Prisma.Profissional$agendasArgs<ExtArgs>
  _count?: boolean | Prisma.ProfissionalCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["profissional"]>

export type ProfissionalSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  usuarioId?: boolean
  nome?: boolean
  registroConselho?: boolean
  especialidade?: boolean
  tipo?: boolean
  unidadeId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  usuario?: boolean | Prisma.UsuarioDefaultArgs<ExtArgs>
  unidade?: boolean | Prisma.Profissional$unidadeArgs<ExtArgs>
}, ExtArgs["result"]["profissional"]>

export type ProfissionalSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  usuarioId?: boolean
  nome?: boolean
  registroConselho?: boolean
  especialidade?: boolean
  tipo?: boolean
  unidadeId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  usuario?: boolean | Prisma.UsuarioDefaultArgs<ExtArgs>
  unidade?: boolean | Prisma.Profissional$unidadeArgs<ExtArgs>
}, ExtArgs["result"]["profissional"]>

export type ProfissionalSelectScalar = {
  id?: boolean
  usuarioId?: boolean
  nome?: boolean
  registroConselho?: boolean
  especialidade?: boolean
  tipo?: boolean
  unidadeId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ProfissionalOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "usuarioId" | "nome" | "registroConselho" | "especialidade" | "tipo" | "unidadeId" | "createdAt" | "updatedAt", ExtArgs["result"]["profissional"]>
export type ProfissionalInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  usuario?: boolean | Prisma.UsuarioDefaultArgs<ExtArgs>
  unidade?: boolean | Prisma.Profissional$unidadeArgs<ExtArgs>
  consultas?: boolean | Prisma.Profissional$consultasArgs<ExtArgs>
  prescricoes?: boolean | Prisma.Profissional$prescricoesArgs<ExtArgs>
  agendas?: boolean | Prisma.Profissional$agendasArgs<ExtArgs>
  _count?: boolean | Prisma.ProfissionalCountOutputTypeDefaultArgs<ExtArgs>
}
export type ProfissionalIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  usuario?: boolean | Prisma.UsuarioDefaultArgs<ExtArgs>
  unidade?: boolean | Prisma.Profissional$unidadeArgs<ExtArgs>
}
export type ProfissionalIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  usuario?: boolean | Prisma.UsuarioDefaultArgs<ExtArgs>
  unidade?: boolean | Prisma.Profissional$unidadeArgs<ExtArgs>
}

export type $ProfissionalPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Profissional"
  objects: {
    usuario: Prisma.$UsuarioPayload<ExtArgs>
    unidade: Prisma.$UnidadeHospitalarPayload<ExtArgs> | null
    consultas: Prisma.$ConsultaPayload<ExtArgs>[]
    prescricoes: Prisma.$PrescricaoPayload<ExtArgs>[]
    agendas: Prisma.$AgendaPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    usuarioId: string
    nome: string
    registroConselho: string
    especialidade: string
    tipo: $Enums.TipoProfissional
    unidadeId: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["profissional"]>
  composites: {}
}

export type ProfissionalGetPayload<S extends boolean | null | undefined | ProfissionalDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProfissionalPayload, S>

export type ProfissionalCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProfissionalFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProfissionalCountAggregateInputType | true
  }

export interface ProfissionalDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Profissional'], meta: { name: 'Profissional' } }
  /**
   * Find zero or one Profissional that matches the filter.
   * @param {ProfissionalFindUniqueArgs} args - Arguments to find a Profissional
   * @example
   * // Get one Profissional
   * const profissional = await prisma.profissional.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProfissionalFindUniqueArgs>(args: Prisma.SelectSubset<T, ProfissionalFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProfissionalClient<runtime.Types.Result.GetResult<Prisma.$ProfissionalPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Profissional that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProfissionalFindUniqueOrThrowArgs} args - Arguments to find a Profissional
   * @example
   * // Get one Profissional
   * const profissional = await prisma.profissional.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProfissionalFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProfissionalFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProfissionalClient<runtime.Types.Result.GetResult<Prisma.$ProfissionalPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Profissional that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfissionalFindFirstArgs} args - Arguments to find a Profissional
   * @example
   * // Get one Profissional
   * const profissional = await prisma.profissional.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProfissionalFindFirstArgs>(args?: Prisma.SelectSubset<T, ProfissionalFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProfissionalClient<runtime.Types.Result.GetResult<Prisma.$ProfissionalPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Profissional that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfissionalFindFirstOrThrowArgs} args - Arguments to find a Profissional
   * @example
   * // Get one Profissional
   * const profissional = await prisma.profissional.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProfissionalFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProfissionalFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProfissionalClient<runtime.Types.Result.GetResult<Prisma.$ProfissionalPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Profissionals that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfissionalFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Profissionals
   * const profissionals = await prisma.profissional.findMany()
   * 
   * // Get first 10 Profissionals
   * const profissionals = await prisma.profissional.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const profissionalWithIdOnly = await prisma.profissional.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ProfissionalFindManyArgs>(args?: Prisma.SelectSubset<T, ProfissionalFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProfissionalPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Profissional.
   * @param {ProfissionalCreateArgs} args - Arguments to create a Profissional.
   * @example
   * // Create one Profissional
   * const Profissional = await prisma.profissional.create({
   *   data: {
   *     // ... data to create a Profissional
   *   }
   * })
   * 
   */
  create<T extends ProfissionalCreateArgs>(args: Prisma.SelectSubset<T, ProfissionalCreateArgs<ExtArgs>>): Prisma.Prisma__ProfissionalClient<runtime.Types.Result.GetResult<Prisma.$ProfissionalPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Profissionals.
   * @param {ProfissionalCreateManyArgs} args - Arguments to create many Profissionals.
   * @example
   * // Create many Profissionals
   * const profissional = await prisma.profissional.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProfissionalCreateManyArgs>(args?: Prisma.SelectSubset<T, ProfissionalCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Profissionals and returns the data saved in the database.
   * @param {ProfissionalCreateManyAndReturnArgs} args - Arguments to create many Profissionals.
   * @example
   * // Create many Profissionals
   * const profissional = await prisma.profissional.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Profissionals and only return the `id`
   * const profissionalWithIdOnly = await prisma.profissional.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ProfissionalCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProfissionalCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProfissionalPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Profissional.
   * @param {ProfissionalDeleteArgs} args - Arguments to delete one Profissional.
   * @example
   * // Delete one Profissional
   * const Profissional = await prisma.profissional.delete({
   *   where: {
   *     // ... filter to delete one Profissional
   *   }
   * })
   * 
   */
  delete<T extends ProfissionalDeleteArgs>(args: Prisma.SelectSubset<T, ProfissionalDeleteArgs<ExtArgs>>): Prisma.Prisma__ProfissionalClient<runtime.Types.Result.GetResult<Prisma.$ProfissionalPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Profissional.
   * @param {ProfissionalUpdateArgs} args - Arguments to update one Profissional.
   * @example
   * // Update one Profissional
   * const profissional = await prisma.profissional.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProfissionalUpdateArgs>(args: Prisma.SelectSubset<T, ProfissionalUpdateArgs<ExtArgs>>): Prisma.Prisma__ProfissionalClient<runtime.Types.Result.GetResult<Prisma.$ProfissionalPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Profissionals.
   * @param {ProfissionalDeleteManyArgs} args - Arguments to filter Profissionals to delete.
   * @example
   * // Delete a few Profissionals
   * const { count } = await prisma.profissional.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProfissionalDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProfissionalDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Profissionals.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfissionalUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Profissionals
   * const profissional = await prisma.profissional.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProfissionalUpdateManyArgs>(args: Prisma.SelectSubset<T, ProfissionalUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Profissionals and returns the data updated in the database.
   * @param {ProfissionalUpdateManyAndReturnArgs} args - Arguments to update many Profissionals.
   * @example
   * // Update many Profissionals
   * const profissional = await prisma.profissional.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Profissionals and only return the `id`
   * const profissionalWithIdOnly = await prisma.profissional.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ProfissionalUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProfissionalUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProfissionalPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Profissional.
   * @param {ProfissionalUpsertArgs} args - Arguments to update or create a Profissional.
   * @example
   * // Update or create a Profissional
   * const profissional = await prisma.profissional.upsert({
   *   create: {
   *     // ... data to create a Profissional
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Profissional we want to update
   *   }
   * })
   */
  upsert<T extends ProfissionalUpsertArgs>(args: Prisma.SelectSubset<T, ProfissionalUpsertArgs<ExtArgs>>): Prisma.Prisma__ProfissionalClient<runtime.Types.Result.GetResult<Prisma.$ProfissionalPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Profissionals.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfissionalCountArgs} args - Arguments to filter Profissionals to count.
   * @example
   * // Count the number of Profissionals
   * const count = await prisma.profissional.count({
   *   where: {
   *     // ... the filter for the Profissionals we want to count
   *   }
   * })
  **/
  count<T extends ProfissionalCountArgs>(
    args?: Prisma.Subset<T, ProfissionalCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProfissionalCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Profissional.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfissionalAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProfissionalAggregateArgs>(args: Prisma.Subset<T, ProfissionalAggregateArgs>): Prisma.PrismaPromise<GetProfissionalAggregateType<T>>

  /**
   * Group by Profissional.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfissionalGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProfissionalGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProfissionalGroupByArgs['orderBy'] }
      : { orderBy?: ProfissionalGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProfissionalGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProfissionalGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Profissional model
 */
readonly fields: ProfissionalFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Profissional.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProfissionalClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  usuario<T extends Prisma.UsuarioDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UsuarioDefaultArgs<ExtArgs>>): Prisma.Prisma__UsuarioClient<runtime.Types.Result.GetResult<Prisma.$UsuarioPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  unidade<T extends Prisma.Profissional$unidadeArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Profissional$unidadeArgs<ExtArgs>>): Prisma.Prisma__UnidadeHospitalarClient<runtime.Types.Result.GetResult<Prisma.$UnidadeHospitalarPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  consultas<T extends Prisma.Profissional$consultasArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Profissional$consultasArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ConsultaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  prescricoes<T extends Prisma.Profissional$prescricoesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Profissional$prescricoesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PrescricaoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  agendas<T extends Prisma.Profissional$agendasArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Profissional$agendasArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgendaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Profissional model
 */
export interface ProfissionalFieldRefs {
  readonly id: Prisma.FieldRef<"Profissional", 'String'>
  readonly usuarioId: Prisma.FieldRef<"Profissional", 'String'>
  readonly nome: Prisma.FieldRef<"Profissional", 'String'>
  readonly registroConselho: Prisma.FieldRef<"Profissional", 'String'>
  readonly especialidade: Prisma.FieldRef<"Profissional", 'String'>
  readonly tipo: Prisma.FieldRef<"Profissional", 'TipoProfissional'>
  readonly unidadeId: Prisma.FieldRef<"Profissional", 'String'>
  readonly createdAt: Prisma.FieldRef<"Profissional", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Profissional", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Profissional findUnique
 */
export type ProfissionalFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profissional
   */
  select?: Prisma.ProfissionalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profissional
   */
  omit?: Prisma.ProfissionalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfissionalInclude<ExtArgs> | null
  /**
   * Filter, which Profissional to fetch.
   */
  where: Prisma.ProfissionalWhereUniqueInput
}

/**
 * Profissional findUniqueOrThrow
 */
export type ProfissionalFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profissional
   */
  select?: Prisma.ProfissionalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profissional
   */
  omit?: Prisma.ProfissionalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfissionalInclude<ExtArgs> | null
  /**
   * Filter, which Profissional to fetch.
   */
  where: Prisma.ProfissionalWhereUniqueInput
}

/**
 * Profissional findFirst
 */
export type ProfissionalFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profissional
   */
  select?: Prisma.ProfissionalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profissional
   */
  omit?: Prisma.ProfissionalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfissionalInclude<ExtArgs> | null
  /**
   * Filter, which Profissional to fetch.
   */
  where?: Prisma.ProfissionalWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Profissionals to fetch.
   */
  orderBy?: Prisma.ProfissionalOrderByWithRelationInput | Prisma.ProfissionalOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Profissionals.
   */
  cursor?: Prisma.ProfissionalWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Profissionals from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Profissionals.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Profissionals.
   */
  distinct?: Prisma.ProfissionalScalarFieldEnum | Prisma.ProfissionalScalarFieldEnum[]
}

/**
 * Profissional findFirstOrThrow
 */
export type ProfissionalFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profissional
   */
  select?: Prisma.ProfissionalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profissional
   */
  omit?: Prisma.ProfissionalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfissionalInclude<ExtArgs> | null
  /**
   * Filter, which Profissional to fetch.
   */
  where?: Prisma.ProfissionalWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Profissionals to fetch.
   */
  orderBy?: Prisma.ProfissionalOrderByWithRelationInput | Prisma.ProfissionalOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Profissionals.
   */
  cursor?: Prisma.ProfissionalWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Profissionals from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Profissionals.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Profissionals.
   */
  distinct?: Prisma.ProfissionalScalarFieldEnum | Prisma.ProfissionalScalarFieldEnum[]
}

/**
 * Profissional findMany
 */
export type ProfissionalFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profissional
   */
  select?: Prisma.ProfissionalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profissional
   */
  omit?: Prisma.ProfissionalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfissionalInclude<ExtArgs> | null
  /**
   * Filter, which Profissionals to fetch.
   */
  where?: Prisma.ProfissionalWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Profissionals to fetch.
   */
  orderBy?: Prisma.ProfissionalOrderByWithRelationInput | Prisma.ProfissionalOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Profissionals.
   */
  cursor?: Prisma.ProfissionalWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Profissionals from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Profissionals.
   */
  skip?: number
  distinct?: Prisma.ProfissionalScalarFieldEnum | Prisma.ProfissionalScalarFieldEnum[]
}

/**
 * Profissional create
 */
export type ProfissionalCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profissional
   */
  select?: Prisma.ProfissionalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profissional
   */
  omit?: Prisma.ProfissionalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfissionalInclude<ExtArgs> | null
  /**
   * The data needed to create a Profissional.
   */
  data: Prisma.XOR<Prisma.ProfissionalCreateInput, Prisma.ProfissionalUncheckedCreateInput>
}

/**
 * Profissional createMany
 */
export type ProfissionalCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Profissionals.
   */
  data: Prisma.ProfissionalCreateManyInput | Prisma.ProfissionalCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Profissional createManyAndReturn
 */
export type ProfissionalCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profissional
   */
  select?: Prisma.ProfissionalSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Profissional
   */
  omit?: Prisma.ProfissionalOmit<ExtArgs> | null
  /**
   * The data used to create many Profissionals.
   */
  data: Prisma.ProfissionalCreateManyInput | Prisma.ProfissionalCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfissionalIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Profissional update
 */
export type ProfissionalUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profissional
   */
  select?: Prisma.ProfissionalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profissional
   */
  omit?: Prisma.ProfissionalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfissionalInclude<ExtArgs> | null
  /**
   * The data needed to update a Profissional.
   */
  data: Prisma.XOR<Prisma.ProfissionalUpdateInput, Prisma.ProfissionalUncheckedUpdateInput>
  /**
   * Choose, which Profissional to update.
   */
  where: Prisma.ProfissionalWhereUniqueInput
}

/**
 * Profissional updateMany
 */
export type ProfissionalUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Profissionals.
   */
  data: Prisma.XOR<Prisma.ProfissionalUpdateManyMutationInput, Prisma.ProfissionalUncheckedUpdateManyInput>
  /**
   * Filter which Profissionals to update
   */
  where?: Prisma.ProfissionalWhereInput
  /**
   * Limit how many Profissionals to update.
   */
  limit?: number
}

/**
 * Profissional updateManyAndReturn
 */
export type ProfissionalUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profissional
   */
  select?: Prisma.ProfissionalSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Profissional
   */
  omit?: Prisma.ProfissionalOmit<ExtArgs> | null
  /**
   * The data used to update Profissionals.
   */
  data: Prisma.XOR<Prisma.ProfissionalUpdateManyMutationInput, Prisma.ProfissionalUncheckedUpdateManyInput>
  /**
   * Filter which Profissionals to update
   */
  where?: Prisma.ProfissionalWhereInput
  /**
   * Limit how many Profissionals to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfissionalIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Profissional upsert
 */
export type ProfissionalUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profissional
   */
  select?: Prisma.ProfissionalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profissional
   */
  omit?: Prisma.ProfissionalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfissionalInclude<ExtArgs> | null
  /**
   * The filter to search for the Profissional to update in case it exists.
   */
  where: Prisma.ProfissionalWhereUniqueInput
  /**
   * In case the Profissional found by the `where` argument doesn't exist, create a new Profissional with this data.
   */
  create: Prisma.XOR<Prisma.ProfissionalCreateInput, Prisma.ProfissionalUncheckedCreateInput>
  /**
   * In case the Profissional was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProfissionalUpdateInput, Prisma.ProfissionalUncheckedUpdateInput>
}

/**
 * Profissional delete
 */
export type ProfissionalDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profissional
   */
  select?: Prisma.ProfissionalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profissional
   */
  omit?: Prisma.ProfissionalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfissionalInclude<ExtArgs> | null
  /**
   * Filter which Profissional to delete.
   */
  where: Prisma.ProfissionalWhereUniqueInput
}

/**
 * Profissional deleteMany
 */
export type ProfissionalDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Profissionals to delete
   */
  where?: Prisma.ProfissionalWhereInput
  /**
   * Limit how many Profissionals to delete.
   */
  limit?: number
}

/**
 * Profissional.unidade
 */
export type Profissional$unidadeArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnidadeHospitalar
   */
  select?: Prisma.UnidadeHospitalarSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnidadeHospitalar
   */
  omit?: Prisma.UnidadeHospitalarOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnidadeHospitalarInclude<ExtArgs> | null
  where?: Prisma.UnidadeHospitalarWhereInput
}

/**
 * Profissional.consultas
 */
export type Profissional$consultasArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Consulta
   */
  select?: Prisma.ConsultaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Consulta
   */
  omit?: Prisma.ConsultaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConsultaInclude<ExtArgs> | null
  where?: Prisma.ConsultaWhereInput
  orderBy?: Prisma.ConsultaOrderByWithRelationInput | Prisma.ConsultaOrderByWithRelationInput[]
  cursor?: Prisma.ConsultaWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ConsultaScalarFieldEnum | Prisma.ConsultaScalarFieldEnum[]
}

/**
 * Profissional.prescricoes
 */
export type Profissional$prescricoesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Prescricao
   */
  select?: Prisma.PrescricaoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Prescricao
   */
  omit?: Prisma.PrescricaoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PrescricaoInclude<ExtArgs> | null
  where?: Prisma.PrescricaoWhereInput
  orderBy?: Prisma.PrescricaoOrderByWithRelationInput | Prisma.PrescricaoOrderByWithRelationInput[]
  cursor?: Prisma.PrescricaoWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PrescricaoScalarFieldEnum | Prisma.PrescricaoScalarFieldEnum[]
}

/**
 * Profissional.agendas
 */
export type Profissional$agendasArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agenda
   */
  select?: Prisma.AgendaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Agenda
   */
  omit?: Prisma.AgendaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgendaInclude<ExtArgs> | null
  where?: Prisma.AgendaWhereInput
  orderBy?: Prisma.AgendaOrderByWithRelationInput | Prisma.AgendaOrderByWithRelationInput[]
  cursor?: Prisma.AgendaWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AgendaScalarFieldEnum | Prisma.AgendaScalarFieldEnum[]
}

/**
 * Profissional without action
 */
export type ProfissionalDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profissional
   */
  select?: Prisma.ProfissionalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profissional
   */
  omit?: Prisma.ProfissionalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfissionalInclude<ExtArgs> | null
}
