
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `UnidadeHospitalar` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model UnidadeHospitalar
 * 
 */
export type UnidadeHospitalarModel = runtime.Types.Result.DefaultSelection<Prisma.$UnidadeHospitalarPayload>

export type AggregateUnidadeHospitalar = {
  _count: UnidadeHospitalarCountAggregateOutputType | null
  _min: UnidadeHospitalarMinAggregateOutputType | null
  _max: UnidadeHospitalarMaxAggregateOutputType | null
}

export type UnidadeHospitalarMinAggregateOutputType = {
  id: string | null
  nome: string | null
  tipo: $Enums.TipoUnidade | null
  endereco: string | null
  telefone: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type UnidadeHospitalarMaxAggregateOutputType = {
  id: string | null
  nome: string | null
  tipo: $Enums.TipoUnidade | null
  endereco: string | null
  telefone: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type UnidadeHospitalarCountAggregateOutputType = {
  id: number
  nome: number
  tipo: number
  endereco: number
  telefone: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type UnidadeHospitalarMinAggregateInputType = {
  id?: true
  nome?: true
  tipo?: true
  endereco?: true
  telefone?: true
  createdAt?: true
  updatedAt?: true
}

export type UnidadeHospitalarMaxAggregateInputType = {
  id?: true
  nome?: true
  tipo?: true
  endereco?: true
  telefone?: true
  createdAt?: true
  updatedAt?: true
}

export type UnidadeHospitalarCountAggregateInputType = {
  id?: true
  nome?: true
  tipo?: true
  endereco?: true
  telefone?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type UnidadeHospitalarAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UnidadeHospitalar to aggregate.
   */
  where?: Prisma.UnidadeHospitalarWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UnidadeHospitalars to fetch.
   */
  orderBy?: Prisma.UnidadeHospitalarOrderByWithRelationInput | Prisma.UnidadeHospitalarOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UnidadeHospitalarWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UnidadeHospitalars from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UnidadeHospitalars.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UnidadeHospitalars
  **/
  _count?: true | UnidadeHospitalarCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UnidadeHospitalarMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UnidadeHospitalarMaxAggregateInputType
}

export type GetUnidadeHospitalarAggregateType<T extends UnidadeHospitalarAggregateArgs> = {
      [P in keyof T & keyof AggregateUnidadeHospitalar]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUnidadeHospitalar[P]>
    : Prisma.GetScalarType<T[P], AggregateUnidadeHospitalar[P]>
}




export type UnidadeHospitalarGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UnidadeHospitalarWhereInput
  orderBy?: Prisma.UnidadeHospitalarOrderByWithAggregationInput | Prisma.UnidadeHospitalarOrderByWithAggregationInput[]
  by: Prisma.UnidadeHospitalarScalarFieldEnum[] | Prisma.UnidadeHospitalarScalarFieldEnum
  having?: Prisma.UnidadeHospitalarScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UnidadeHospitalarCountAggregateInputType | true
  _min?: UnidadeHospitalarMinAggregateInputType
  _max?: UnidadeHospitalarMaxAggregateInputType
}

export type UnidadeHospitalarGroupByOutputType = {
  id: string
  nome: string
  tipo: $Enums.TipoUnidade
  endereco: string
  telefone: string
  createdAt: Date
  updatedAt: Date
  _count: UnidadeHospitalarCountAggregateOutputType | null
  _min: UnidadeHospitalarMinAggregateOutputType | null
  _max: UnidadeHospitalarMaxAggregateOutputType | null
}

type GetUnidadeHospitalarGroupByPayload<T extends UnidadeHospitalarGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UnidadeHospitalarGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UnidadeHospitalarGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UnidadeHospitalarGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UnidadeHospitalarGroupByOutputType[P]>
      }
    >
  >



export type UnidadeHospitalarWhereInput = {
  AND?: Prisma.UnidadeHospitalarWhereInput | Prisma.UnidadeHospitalarWhereInput[]
  OR?: Prisma.UnidadeHospitalarWhereInput[]
  NOT?: Prisma.UnidadeHospitalarWhereInput | Prisma.UnidadeHospitalarWhereInput[]
  id?: Prisma.StringFilter<"UnidadeHospitalar"> | string
  nome?: Prisma.StringFilter<"UnidadeHospitalar"> | string
  tipo?: Prisma.EnumTipoUnidadeFilter<"UnidadeHospitalar"> | $Enums.TipoUnidade
  endereco?: Prisma.StringFilter<"UnidadeHospitalar"> | string
  telefone?: Prisma.StringFilter<"UnidadeHospitalar"> | string
  createdAt?: Prisma.DateTimeFilter<"UnidadeHospitalar"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"UnidadeHospitalar"> | Date | string
  leitos?: Prisma.LeitoListRelationFilter
  profissionais?: Prisma.ProfissionalListRelationFilter
}

export type UnidadeHospitalarOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  tipo?: Prisma.SortOrder
  endereco?: Prisma.SortOrder
  telefone?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  leitos?: Prisma.LeitoOrderByRelationAggregateInput
  profissionais?: Prisma.ProfissionalOrderByRelationAggregateInput
}

export type UnidadeHospitalarWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.UnidadeHospitalarWhereInput | Prisma.UnidadeHospitalarWhereInput[]
  OR?: Prisma.UnidadeHospitalarWhereInput[]
  NOT?: Prisma.UnidadeHospitalarWhereInput | Prisma.UnidadeHospitalarWhereInput[]
  nome?: Prisma.StringFilter<"UnidadeHospitalar"> | string
  tipo?: Prisma.EnumTipoUnidadeFilter<"UnidadeHospitalar"> | $Enums.TipoUnidade
  endereco?: Prisma.StringFilter<"UnidadeHospitalar"> | string
  telefone?: Prisma.StringFilter<"UnidadeHospitalar"> | string
  createdAt?: Prisma.DateTimeFilter<"UnidadeHospitalar"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"UnidadeHospitalar"> | Date | string
  leitos?: Prisma.LeitoListRelationFilter
  profissionais?: Prisma.ProfissionalListRelationFilter
}, "id">

export type UnidadeHospitalarOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  tipo?: Prisma.SortOrder
  endereco?: Prisma.SortOrder
  telefone?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.UnidadeHospitalarCountOrderByAggregateInput
  _max?: Prisma.UnidadeHospitalarMaxOrderByAggregateInput
  _min?: Prisma.UnidadeHospitalarMinOrderByAggregateInput
}

export type UnidadeHospitalarScalarWhereWithAggregatesInput = {
  AND?: Prisma.UnidadeHospitalarScalarWhereWithAggregatesInput | Prisma.UnidadeHospitalarScalarWhereWithAggregatesInput[]
  OR?: Prisma.UnidadeHospitalarScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UnidadeHospitalarScalarWhereWithAggregatesInput | Prisma.UnidadeHospitalarScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"UnidadeHospitalar"> | string
  nome?: Prisma.StringWithAggregatesFilter<"UnidadeHospitalar"> | string
  tipo?: Prisma.EnumTipoUnidadeWithAggregatesFilter<"UnidadeHospitalar"> | $Enums.TipoUnidade
  endereco?: Prisma.StringWithAggregatesFilter<"UnidadeHospitalar"> | string
  telefone?: Prisma.StringWithAggregatesFilter<"UnidadeHospitalar"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"UnidadeHospitalar"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"UnidadeHospitalar"> | Date | string
}

export type UnidadeHospitalarCreateInput = {
  id?: string
  nome: string
  tipo: $Enums.TipoUnidade
  endereco: string
  telefone: string
  createdAt?: Date | string
  updatedAt?: Date | string
  leitos?: Prisma.LeitoCreateNestedManyWithoutUnidadeInput
  profissionais?: Prisma.ProfissionalCreateNestedManyWithoutUnidadeInput
}

export type UnidadeHospitalarUncheckedCreateInput = {
  id?: string
  nome: string
  tipo: $Enums.TipoUnidade
  endereco: string
  telefone: string
  createdAt?: Date | string
  updatedAt?: Date | string
  leitos?: Prisma.LeitoUncheckedCreateNestedManyWithoutUnidadeInput
  profissionais?: Prisma.ProfissionalUncheckedCreateNestedManyWithoutUnidadeInput
}

export type UnidadeHospitalarUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  tipo?: Prisma.EnumTipoUnidadeFieldUpdateOperationsInput | $Enums.TipoUnidade
  endereco?: Prisma.StringFieldUpdateOperationsInput | string
  telefone?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  leitos?: Prisma.LeitoUpdateManyWithoutUnidadeNestedInput
  profissionais?: Prisma.ProfissionalUpdateManyWithoutUnidadeNestedInput
}

export type UnidadeHospitalarUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  tipo?: Prisma.EnumTipoUnidadeFieldUpdateOperationsInput | $Enums.TipoUnidade
  endereco?: Prisma.StringFieldUpdateOperationsInput | string
  telefone?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  leitos?: Prisma.LeitoUncheckedUpdateManyWithoutUnidadeNestedInput
  profissionais?: Prisma.ProfissionalUncheckedUpdateManyWithoutUnidadeNestedInput
}

export type UnidadeHospitalarCreateManyInput = {
  id?: string
  nome: string
  tipo: $Enums.TipoUnidade
  endereco: string
  telefone: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type UnidadeHospitalarUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  tipo?: Prisma.EnumTipoUnidadeFieldUpdateOperationsInput | $Enums.TipoUnidade
  endereco?: Prisma.StringFieldUpdateOperationsInput | string
  telefone?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UnidadeHospitalarUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  tipo?: Prisma.EnumTipoUnidadeFieldUpdateOperationsInput | $Enums.TipoUnidade
  endereco?: Prisma.StringFieldUpdateOperationsInput | string
  telefone?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UnidadeHospitalarNullableScalarRelationFilter = {
  is?: Prisma.UnidadeHospitalarWhereInput | null
  isNot?: Prisma.UnidadeHospitalarWhereInput | null
}

export type UnidadeHospitalarCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  tipo?: Prisma.SortOrder
  endereco?: Prisma.SortOrder
  telefone?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UnidadeHospitalarMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  tipo?: Prisma.SortOrder
  endereco?: Prisma.SortOrder
  telefone?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UnidadeHospitalarMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  tipo?: Prisma.SortOrder
  endereco?: Prisma.SortOrder
  telefone?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UnidadeHospitalarScalarRelationFilter = {
  is?: Prisma.UnidadeHospitalarWhereInput
  isNot?: Prisma.UnidadeHospitalarWhereInput
}

export type UnidadeHospitalarCreateNestedOneWithoutProfissionaisInput = {
  create?: Prisma.XOR<Prisma.UnidadeHospitalarCreateWithoutProfissionaisInput, Prisma.UnidadeHospitalarUncheckedCreateWithoutProfissionaisInput>
  connectOrCreate?: Prisma.UnidadeHospitalarCreateOrConnectWithoutProfissionaisInput
  connect?: Prisma.UnidadeHospitalarWhereUniqueInput
}

export type UnidadeHospitalarUpdateOneWithoutProfissionaisNestedInput = {
  create?: Prisma.XOR<Prisma.UnidadeHospitalarCreateWithoutProfissionaisInput, Prisma.UnidadeHospitalarUncheckedCreateWithoutProfissionaisInput>
  connectOrCreate?: Prisma.UnidadeHospitalarCreateOrConnectWithoutProfissionaisInput
  upsert?: Prisma.UnidadeHospitalarUpsertWithoutProfissionaisInput
  disconnect?: Prisma.UnidadeHospitalarWhereInput | boolean
  delete?: Prisma.UnidadeHospitalarWhereInput | boolean
  connect?: Prisma.UnidadeHospitalarWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UnidadeHospitalarUpdateToOneWithWhereWithoutProfissionaisInput, Prisma.UnidadeHospitalarUpdateWithoutProfissionaisInput>, Prisma.UnidadeHospitalarUncheckedUpdateWithoutProfissionaisInput>
}

export type EnumTipoUnidadeFieldUpdateOperationsInput = {
  set?: $Enums.TipoUnidade
}

export type UnidadeHospitalarCreateNestedOneWithoutLeitosInput = {
  create?: Prisma.XOR<Prisma.UnidadeHospitalarCreateWithoutLeitosInput, Prisma.UnidadeHospitalarUncheckedCreateWithoutLeitosInput>
  connectOrCreate?: Prisma.UnidadeHospitalarCreateOrConnectWithoutLeitosInput
  connect?: Prisma.UnidadeHospitalarWhereUniqueInput
}

export type UnidadeHospitalarUpdateOneRequiredWithoutLeitosNestedInput = {
  create?: Prisma.XOR<Prisma.UnidadeHospitalarCreateWithoutLeitosInput, Prisma.UnidadeHospitalarUncheckedCreateWithoutLeitosInput>
  connectOrCreate?: Prisma.UnidadeHospitalarCreateOrConnectWithoutLeitosInput
  upsert?: Prisma.UnidadeHospitalarUpsertWithoutLeitosInput
  connect?: Prisma.UnidadeHospitalarWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UnidadeHospitalarUpdateToOneWithWhereWithoutLeitosInput, Prisma.UnidadeHospitalarUpdateWithoutLeitosInput>, Prisma.UnidadeHospitalarUncheckedUpdateWithoutLeitosInput>
}

export type UnidadeHospitalarCreateWithoutProfissionaisInput = {
  id?: string
  nome: string
  tipo: $Enums.TipoUnidade
  endereco: string
  telefone: string
  createdAt?: Date | string
  updatedAt?: Date | string
  leitos?: Prisma.LeitoCreateNestedManyWithoutUnidadeInput
}

export type UnidadeHospitalarUncheckedCreateWithoutProfissionaisInput = {
  id?: string
  nome: string
  tipo: $Enums.TipoUnidade
  endereco: string
  telefone: string
  createdAt?: Date | string
  updatedAt?: Date | string
  leitos?: Prisma.LeitoUncheckedCreateNestedManyWithoutUnidadeInput
}

export type UnidadeHospitalarCreateOrConnectWithoutProfissionaisInput = {
  where: Prisma.UnidadeHospitalarWhereUniqueInput
  create: Prisma.XOR<Prisma.UnidadeHospitalarCreateWithoutProfissionaisInput, Prisma.UnidadeHospitalarUncheckedCreateWithoutProfissionaisInput>
}

export type UnidadeHospitalarUpsertWithoutProfissionaisInput = {
  update: Prisma.XOR<Prisma.UnidadeHospitalarUpdateWithoutProfissionaisInput, Prisma.UnidadeHospitalarUncheckedUpdateWithoutProfissionaisInput>
  create: Prisma.XOR<Prisma.UnidadeHospitalarCreateWithoutProfissionaisInput, Prisma.UnidadeHospitalarUncheckedCreateWithoutProfissionaisInput>
  where?: Prisma.UnidadeHospitalarWhereInput
}

export type UnidadeHospitalarUpdateToOneWithWhereWithoutProfissionaisInput = {
  where?: Prisma.UnidadeHospitalarWhereInput
  data: Prisma.XOR<Prisma.UnidadeHospitalarUpdateWithoutProfissionaisInput, Prisma.UnidadeHospitalarUncheckedUpdateWithoutProfissionaisInput>
}

export type UnidadeHospitalarUpdateWithoutProfissionaisInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  tipo?: Prisma.EnumTipoUnidadeFieldUpdateOperationsInput | $Enums.TipoUnidade
  endereco?: Prisma.StringFieldUpdateOperationsInput | string
  telefone?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  leitos?: Prisma.LeitoUpdateManyWithoutUnidadeNestedInput
}

export type UnidadeHospitalarUncheckedUpdateWithoutProfissionaisInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  tipo?: Prisma.EnumTipoUnidadeFieldUpdateOperationsInput | $Enums.TipoUnidade
  endereco?: Prisma.StringFieldUpdateOperationsInput | string
  telefone?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  leitos?: Prisma.LeitoUncheckedUpdateManyWithoutUnidadeNestedInput
}

export type UnidadeHospitalarCreateWithoutLeitosInput = {
  id?: string
  nome: string
  tipo: $Enums.TipoUnidade
  endereco: string
  telefone: string
  createdAt?: Date | string
  updatedAt?: Date | string
  profissionais?: Prisma.ProfissionalCreateNestedManyWithoutUnidadeInput
}

export type UnidadeHospitalarUncheckedCreateWithoutLeitosInput = {
  id?: string
  nome: string
  tipo: $Enums.TipoUnidade
  endereco: string
  telefone: string
  createdAt?: Date | string
  updatedAt?: Date | string
  profissionais?: Prisma.ProfissionalUncheckedCreateNestedManyWithoutUnidadeInput
}

export type UnidadeHospitalarCreateOrConnectWithoutLeitosInput = {
  where: Prisma.UnidadeHospitalarWhereUniqueInput
  create: Prisma.XOR<Prisma.UnidadeHospitalarCreateWithoutLeitosInput, Prisma.UnidadeHospitalarUncheckedCreateWithoutLeitosInput>
}

export type UnidadeHospitalarUpsertWithoutLeitosInput = {
  update: Prisma.XOR<Prisma.UnidadeHospitalarUpdateWithoutLeitosInput, Prisma.UnidadeHospitalarUncheckedUpdateWithoutLeitosInput>
  create: Prisma.XOR<Prisma.UnidadeHospitalarCreateWithoutLeitosInput, Prisma.UnidadeHospitalarUncheckedCreateWithoutLeitosInput>
  where?: Prisma.UnidadeHospitalarWhereInput
}

export type UnidadeHospitalarUpdateToOneWithWhereWithoutLeitosInput = {
  where?: Prisma.UnidadeHospitalarWhereInput
  data: Prisma.XOR<Prisma.UnidadeHospitalarUpdateWithoutLeitosInput, Prisma.UnidadeHospitalarUncheckedUpdateWithoutLeitosInput>
}

export type UnidadeHospitalarUpdateWithoutLeitosInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  tipo?: Prisma.EnumTipoUnidadeFieldUpdateOperationsInput | $Enums.TipoUnidade
  endereco?: Prisma.StringFieldUpdateOperationsInput | string
  telefone?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  profissionais?: Prisma.ProfissionalUpdateManyWithoutUnidadeNestedInput
}

export type UnidadeHospitalarUncheckedUpdateWithoutLeitosInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  tipo?: Prisma.EnumTipoUnidadeFieldUpdateOperationsInput | $Enums.TipoUnidade
  endereco?: Prisma.StringFieldUpdateOperationsInput | string
  telefone?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  profissionais?: Prisma.ProfissionalUncheckedUpdateManyWithoutUnidadeNestedInput
}


/**
 * Count Type UnidadeHospitalarCountOutputType
 */

export type UnidadeHospitalarCountOutputType = {
  leitos: number
  profissionais: number
}

export type UnidadeHospitalarCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  leitos?: boolean | UnidadeHospitalarCountOutputTypeCountLeitosArgs
  profissionais?: boolean | UnidadeHospitalarCountOutputTypeCountProfissionaisArgs
}

/**
 * UnidadeHospitalarCountOutputType without action
 */
export type UnidadeHospitalarCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnidadeHospitalarCountOutputType
   */
  select?: Prisma.UnidadeHospitalarCountOutputTypeSelect<ExtArgs> | null
}

/**
 * UnidadeHospitalarCountOutputType without action
 */
export type UnidadeHospitalarCountOutputTypeCountLeitosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LeitoWhereInput
}

/**
 * UnidadeHospitalarCountOutputType without action
 */
export type UnidadeHospitalarCountOutputTypeCountProfissionaisArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProfissionalWhereInput
}


export type UnidadeHospitalarSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nome?: boolean
  tipo?: boolean
  endereco?: boolean
  telefone?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  leitos?: boolean | Prisma.UnidadeHospitalar$leitosArgs<ExtArgs>
  profissionais?: boolean | Prisma.UnidadeHospitalar$profissionaisArgs<ExtArgs>
  _count?: boolean | Prisma.UnidadeHospitalarCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["unidadeHospitalar"]>

export type UnidadeHospitalarSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nome?: boolean
  tipo?: boolean
  endereco?: boolean
  telefone?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["unidadeHospitalar"]>

export type UnidadeHospitalarSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nome?: boolean
  tipo?: boolean
  endereco?: boolean
  telefone?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["unidadeHospitalar"]>

export type UnidadeHospitalarSelectScalar = {
  id?: boolean
  nome?: boolean
  tipo?: boolean
  endereco?: boolean
  telefone?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type UnidadeHospitalarOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "nome" | "tipo" | "endereco" | "telefone" | "createdAt" | "updatedAt", ExtArgs["result"]["unidadeHospitalar"]>
export type UnidadeHospitalarInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  leitos?: boolean | Prisma.UnidadeHospitalar$leitosArgs<ExtArgs>
  profissionais?: boolean | Prisma.UnidadeHospitalar$profissionaisArgs<ExtArgs>
  _count?: boolean | Prisma.UnidadeHospitalarCountOutputTypeDefaultArgs<ExtArgs>
}
export type UnidadeHospitalarIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type UnidadeHospitalarIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $UnidadeHospitalarPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UnidadeHospitalar"
  objects: {
    leitos: Prisma.$LeitoPayload<ExtArgs>[]
    profissionais: Prisma.$ProfissionalPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    nome: string
    tipo: $Enums.TipoUnidade
    endereco: string
    telefone: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["unidadeHospitalar"]>
  composites: {}
}

export type UnidadeHospitalarGetPayload<S extends boolean | null | undefined | UnidadeHospitalarDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UnidadeHospitalarPayload, S>

export type UnidadeHospitalarCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UnidadeHospitalarFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UnidadeHospitalarCountAggregateInputType | true
  }

export interface UnidadeHospitalarDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UnidadeHospitalar'], meta: { name: 'UnidadeHospitalar' } }
  /**
   * Find zero or one UnidadeHospitalar that matches the filter.
   * @param {UnidadeHospitalarFindUniqueArgs} args - Arguments to find a UnidadeHospitalar
   * @example
   * // Get one UnidadeHospitalar
   * const unidadeHospitalar = await prisma.unidadeHospitalar.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UnidadeHospitalarFindUniqueArgs>(args: Prisma.SelectSubset<T, UnidadeHospitalarFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UnidadeHospitalarClient<runtime.Types.Result.GetResult<Prisma.$UnidadeHospitalarPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UnidadeHospitalar that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UnidadeHospitalarFindUniqueOrThrowArgs} args - Arguments to find a UnidadeHospitalar
   * @example
   * // Get one UnidadeHospitalar
   * const unidadeHospitalar = await prisma.unidadeHospitalar.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UnidadeHospitalarFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UnidadeHospitalarFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UnidadeHospitalarClient<runtime.Types.Result.GetResult<Prisma.$UnidadeHospitalarPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UnidadeHospitalar that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnidadeHospitalarFindFirstArgs} args - Arguments to find a UnidadeHospitalar
   * @example
   * // Get one UnidadeHospitalar
   * const unidadeHospitalar = await prisma.unidadeHospitalar.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UnidadeHospitalarFindFirstArgs>(args?: Prisma.SelectSubset<T, UnidadeHospitalarFindFirstArgs<ExtArgs>>): Prisma.Prisma__UnidadeHospitalarClient<runtime.Types.Result.GetResult<Prisma.$UnidadeHospitalarPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UnidadeHospitalar that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnidadeHospitalarFindFirstOrThrowArgs} args - Arguments to find a UnidadeHospitalar
   * @example
   * // Get one UnidadeHospitalar
   * const unidadeHospitalar = await prisma.unidadeHospitalar.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UnidadeHospitalarFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UnidadeHospitalarFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UnidadeHospitalarClient<runtime.Types.Result.GetResult<Prisma.$UnidadeHospitalarPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UnidadeHospitalars that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnidadeHospitalarFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UnidadeHospitalars
   * const unidadeHospitalars = await prisma.unidadeHospitalar.findMany()
   * 
   * // Get first 10 UnidadeHospitalars
   * const unidadeHospitalars = await prisma.unidadeHospitalar.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const unidadeHospitalarWithIdOnly = await prisma.unidadeHospitalar.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UnidadeHospitalarFindManyArgs>(args?: Prisma.SelectSubset<T, UnidadeHospitalarFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UnidadeHospitalarPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UnidadeHospitalar.
   * @param {UnidadeHospitalarCreateArgs} args - Arguments to create a UnidadeHospitalar.
   * @example
   * // Create one UnidadeHospitalar
   * const UnidadeHospitalar = await prisma.unidadeHospitalar.create({
   *   data: {
   *     // ... data to create a UnidadeHospitalar
   *   }
   * })
   * 
   */
  create<T extends UnidadeHospitalarCreateArgs>(args: Prisma.SelectSubset<T, UnidadeHospitalarCreateArgs<ExtArgs>>): Prisma.Prisma__UnidadeHospitalarClient<runtime.Types.Result.GetResult<Prisma.$UnidadeHospitalarPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UnidadeHospitalars.
   * @param {UnidadeHospitalarCreateManyArgs} args - Arguments to create many UnidadeHospitalars.
   * @example
   * // Create many UnidadeHospitalars
   * const unidadeHospitalar = await prisma.unidadeHospitalar.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UnidadeHospitalarCreateManyArgs>(args?: Prisma.SelectSubset<T, UnidadeHospitalarCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UnidadeHospitalars and returns the data saved in the database.
   * @param {UnidadeHospitalarCreateManyAndReturnArgs} args - Arguments to create many UnidadeHospitalars.
   * @example
   * // Create many UnidadeHospitalars
   * const unidadeHospitalar = await prisma.unidadeHospitalar.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UnidadeHospitalars and only return the `id`
   * const unidadeHospitalarWithIdOnly = await prisma.unidadeHospitalar.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UnidadeHospitalarCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UnidadeHospitalarCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UnidadeHospitalarPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UnidadeHospitalar.
   * @param {UnidadeHospitalarDeleteArgs} args - Arguments to delete one UnidadeHospitalar.
   * @example
   * // Delete one UnidadeHospitalar
   * const UnidadeHospitalar = await prisma.unidadeHospitalar.delete({
   *   where: {
   *     // ... filter to delete one UnidadeHospitalar
   *   }
   * })
   * 
   */
  delete<T extends UnidadeHospitalarDeleteArgs>(args: Prisma.SelectSubset<T, UnidadeHospitalarDeleteArgs<ExtArgs>>): Prisma.Prisma__UnidadeHospitalarClient<runtime.Types.Result.GetResult<Prisma.$UnidadeHospitalarPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UnidadeHospitalar.
   * @param {UnidadeHospitalarUpdateArgs} args - Arguments to update one UnidadeHospitalar.
   * @example
   * // Update one UnidadeHospitalar
   * const unidadeHospitalar = await prisma.unidadeHospitalar.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UnidadeHospitalarUpdateArgs>(args: Prisma.SelectSubset<T, UnidadeHospitalarUpdateArgs<ExtArgs>>): Prisma.Prisma__UnidadeHospitalarClient<runtime.Types.Result.GetResult<Prisma.$UnidadeHospitalarPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UnidadeHospitalars.
   * @param {UnidadeHospitalarDeleteManyArgs} args - Arguments to filter UnidadeHospitalars to delete.
   * @example
   * // Delete a few UnidadeHospitalars
   * const { count } = await prisma.unidadeHospitalar.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UnidadeHospitalarDeleteManyArgs>(args?: Prisma.SelectSubset<T, UnidadeHospitalarDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UnidadeHospitalars.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnidadeHospitalarUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UnidadeHospitalars
   * const unidadeHospitalar = await prisma.unidadeHospitalar.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UnidadeHospitalarUpdateManyArgs>(args: Prisma.SelectSubset<T, UnidadeHospitalarUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UnidadeHospitalars and returns the data updated in the database.
   * @param {UnidadeHospitalarUpdateManyAndReturnArgs} args - Arguments to update many UnidadeHospitalars.
   * @example
   * // Update many UnidadeHospitalars
   * const unidadeHospitalar = await prisma.unidadeHospitalar.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UnidadeHospitalars and only return the `id`
   * const unidadeHospitalarWithIdOnly = await prisma.unidadeHospitalar.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UnidadeHospitalarUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UnidadeHospitalarUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UnidadeHospitalarPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UnidadeHospitalar.
   * @param {UnidadeHospitalarUpsertArgs} args - Arguments to update or create a UnidadeHospitalar.
   * @example
   * // Update or create a UnidadeHospitalar
   * const unidadeHospitalar = await prisma.unidadeHospitalar.upsert({
   *   create: {
   *     // ... data to create a UnidadeHospitalar
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UnidadeHospitalar we want to update
   *   }
   * })
   */
  upsert<T extends UnidadeHospitalarUpsertArgs>(args: Prisma.SelectSubset<T, UnidadeHospitalarUpsertArgs<ExtArgs>>): Prisma.Prisma__UnidadeHospitalarClient<runtime.Types.Result.GetResult<Prisma.$UnidadeHospitalarPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UnidadeHospitalars.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnidadeHospitalarCountArgs} args - Arguments to filter UnidadeHospitalars to count.
   * @example
   * // Count the number of UnidadeHospitalars
   * const count = await prisma.unidadeHospitalar.count({
   *   where: {
   *     // ... the filter for the UnidadeHospitalars we want to count
   *   }
   * })
  **/
  count<T extends UnidadeHospitalarCountArgs>(
    args?: Prisma.Subset<T, UnidadeHospitalarCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UnidadeHospitalarCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UnidadeHospitalar.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnidadeHospitalarAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UnidadeHospitalarAggregateArgs>(args: Prisma.Subset<T, UnidadeHospitalarAggregateArgs>): Prisma.PrismaPromise<GetUnidadeHospitalarAggregateType<T>>

  /**
   * Group by UnidadeHospitalar.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnidadeHospitalarGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UnidadeHospitalarGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UnidadeHospitalarGroupByArgs['orderBy'] }
      : { orderBy?: UnidadeHospitalarGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UnidadeHospitalarGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUnidadeHospitalarGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UnidadeHospitalar model
 */
readonly fields: UnidadeHospitalarFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UnidadeHospitalar.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UnidadeHospitalarClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  leitos<T extends Prisma.UnidadeHospitalar$leitosArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UnidadeHospitalar$leitosArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LeitoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  profissionais<T extends Prisma.UnidadeHospitalar$profissionaisArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UnidadeHospitalar$profissionaisArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProfissionalPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UnidadeHospitalar model
 */
export interface UnidadeHospitalarFieldRefs {
  readonly id: Prisma.FieldRef<"UnidadeHospitalar", 'String'>
  readonly nome: Prisma.FieldRef<"UnidadeHospitalar", 'String'>
  readonly tipo: Prisma.FieldRef<"UnidadeHospitalar", 'TipoUnidade'>
  readonly endereco: Prisma.FieldRef<"UnidadeHospitalar", 'String'>
  readonly telefone: Prisma.FieldRef<"UnidadeHospitalar", 'String'>
  readonly createdAt: Prisma.FieldRef<"UnidadeHospitalar", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"UnidadeHospitalar", 'DateTime'>
}
    

// Custom InputTypes
/**
 * UnidadeHospitalar findUnique
 */
export type UnidadeHospitalarFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnidadeHospitalar
   */
  select?: Prisma.UnidadeHospitalarSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnidadeHospitalar
   */
  omit?: Prisma.UnidadeHospitalarOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnidadeHospitalarInclude<ExtArgs> | null
  /**
   * Filter, which UnidadeHospitalar to fetch.
   */
  where: Prisma.UnidadeHospitalarWhereUniqueInput
}

/**
 * UnidadeHospitalar findUniqueOrThrow
 */
export type UnidadeHospitalarFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnidadeHospitalar
   */
  select?: Prisma.UnidadeHospitalarSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnidadeHospitalar
   */
  omit?: Prisma.UnidadeHospitalarOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnidadeHospitalarInclude<ExtArgs> | null
  /**
   * Filter, which UnidadeHospitalar to fetch.
   */
  where: Prisma.UnidadeHospitalarWhereUniqueInput
}

/**
 * UnidadeHospitalar findFirst
 */
export type UnidadeHospitalarFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnidadeHospitalar
   */
  select?: Prisma.UnidadeHospitalarSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnidadeHospitalar
   */
  omit?: Prisma.UnidadeHospitalarOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnidadeHospitalarInclude<ExtArgs> | null
  /**
   * Filter, which UnidadeHospitalar to fetch.
   */
  where?: Prisma.UnidadeHospitalarWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UnidadeHospitalars to fetch.
   */
  orderBy?: Prisma.UnidadeHospitalarOrderByWithRelationInput | Prisma.UnidadeHospitalarOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UnidadeHospitalars.
   */
  cursor?: Prisma.UnidadeHospitalarWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UnidadeHospitalars from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UnidadeHospitalars.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UnidadeHospitalars.
   */
  distinct?: Prisma.UnidadeHospitalarScalarFieldEnum | Prisma.UnidadeHospitalarScalarFieldEnum[]
}

/**
 * UnidadeHospitalar findFirstOrThrow
 */
export type UnidadeHospitalarFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnidadeHospitalar
   */
  select?: Prisma.UnidadeHospitalarSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnidadeHospitalar
   */
  omit?: Prisma.UnidadeHospitalarOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnidadeHospitalarInclude<ExtArgs> | null
  /**
   * Filter, which UnidadeHospitalar to fetch.
   */
  where?: Prisma.UnidadeHospitalarWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UnidadeHospitalars to fetch.
   */
  orderBy?: Prisma.UnidadeHospitalarOrderByWithRelationInput | Prisma.UnidadeHospitalarOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UnidadeHospitalars.
   */
  cursor?: Prisma.UnidadeHospitalarWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UnidadeHospitalars from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UnidadeHospitalars.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UnidadeHospitalars.
   */
  distinct?: Prisma.UnidadeHospitalarScalarFieldEnum | Prisma.UnidadeHospitalarScalarFieldEnum[]
}

/**
 * UnidadeHospitalar findMany
 */
export type UnidadeHospitalarFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnidadeHospitalar
   */
  select?: Prisma.UnidadeHospitalarSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnidadeHospitalar
   */
  omit?: Prisma.UnidadeHospitalarOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnidadeHospitalarInclude<ExtArgs> | null
  /**
   * Filter, which UnidadeHospitalars to fetch.
   */
  where?: Prisma.UnidadeHospitalarWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UnidadeHospitalars to fetch.
   */
  orderBy?: Prisma.UnidadeHospitalarOrderByWithRelationInput | Prisma.UnidadeHospitalarOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UnidadeHospitalars.
   */
  cursor?: Prisma.UnidadeHospitalarWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UnidadeHospitalars from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UnidadeHospitalars.
   */
  skip?: number
  distinct?: Prisma.UnidadeHospitalarScalarFieldEnum | Prisma.UnidadeHospitalarScalarFieldEnum[]
}

/**
 * UnidadeHospitalar create
 */
export type UnidadeHospitalarCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnidadeHospitalar
   */
  select?: Prisma.UnidadeHospitalarSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnidadeHospitalar
   */
  omit?: Prisma.UnidadeHospitalarOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnidadeHospitalarInclude<ExtArgs> | null
  /**
   * The data needed to create a UnidadeHospitalar.
   */
  data: Prisma.XOR<Prisma.UnidadeHospitalarCreateInput, Prisma.UnidadeHospitalarUncheckedCreateInput>
}

/**
 * UnidadeHospitalar createMany
 */
export type UnidadeHospitalarCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UnidadeHospitalars.
   */
  data: Prisma.UnidadeHospitalarCreateManyInput | Prisma.UnidadeHospitalarCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * UnidadeHospitalar createManyAndReturn
 */
export type UnidadeHospitalarCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnidadeHospitalar
   */
  select?: Prisma.UnidadeHospitalarSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UnidadeHospitalar
   */
  omit?: Prisma.UnidadeHospitalarOmit<ExtArgs> | null
  /**
   * The data used to create many UnidadeHospitalars.
   */
  data: Prisma.UnidadeHospitalarCreateManyInput | Prisma.UnidadeHospitalarCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * UnidadeHospitalar update
 */
export type UnidadeHospitalarUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnidadeHospitalar
   */
  select?: Prisma.UnidadeHospitalarSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnidadeHospitalar
   */
  omit?: Prisma.UnidadeHospitalarOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnidadeHospitalarInclude<ExtArgs> | null
  /**
   * The data needed to update a UnidadeHospitalar.
   */
  data: Prisma.XOR<Prisma.UnidadeHospitalarUpdateInput, Prisma.UnidadeHospitalarUncheckedUpdateInput>
  /**
   * Choose, which UnidadeHospitalar to update.
   */
  where: Prisma.UnidadeHospitalarWhereUniqueInput
}

/**
 * UnidadeHospitalar updateMany
 */
export type UnidadeHospitalarUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UnidadeHospitalars.
   */
  data: Prisma.XOR<Prisma.UnidadeHospitalarUpdateManyMutationInput, Prisma.UnidadeHospitalarUncheckedUpdateManyInput>
  /**
   * Filter which UnidadeHospitalars to update
   */
  where?: Prisma.UnidadeHospitalarWhereInput
  /**
   * Limit how many UnidadeHospitalars to update.
   */
  limit?: number
}

/**
 * UnidadeHospitalar updateManyAndReturn
 */
export type UnidadeHospitalarUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnidadeHospitalar
   */
  select?: Prisma.UnidadeHospitalarSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UnidadeHospitalar
   */
  omit?: Prisma.UnidadeHospitalarOmit<ExtArgs> | null
  /**
   * The data used to update UnidadeHospitalars.
   */
  data: Prisma.XOR<Prisma.UnidadeHospitalarUpdateManyMutationInput, Prisma.UnidadeHospitalarUncheckedUpdateManyInput>
  /**
   * Filter which UnidadeHospitalars to update
   */
  where?: Prisma.UnidadeHospitalarWhereInput
  /**
   * Limit how many UnidadeHospitalars to update.
   */
  limit?: number
}

/**
 * UnidadeHospitalar upsert
 */
export type UnidadeHospitalarUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnidadeHospitalar
   */
  select?: Prisma.UnidadeHospitalarSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnidadeHospitalar
   */
  omit?: Prisma.UnidadeHospitalarOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnidadeHospitalarInclude<ExtArgs> | null
  /**
   * The filter to search for the UnidadeHospitalar to update in case it exists.
   */
  where: Prisma.UnidadeHospitalarWhereUniqueInput
  /**
   * In case the UnidadeHospitalar found by the `where` argument doesn't exist, create a new UnidadeHospitalar with this data.
   */
  create: Prisma.XOR<Prisma.UnidadeHospitalarCreateInput, Prisma.UnidadeHospitalarUncheckedCreateInput>
  /**
   * In case the UnidadeHospitalar was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UnidadeHospitalarUpdateInput, Prisma.UnidadeHospitalarUncheckedUpdateInput>
}

/**
 * UnidadeHospitalar delete
 */
export type UnidadeHospitalarDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnidadeHospitalar
   */
  select?: Prisma.UnidadeHospitalarSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnidadeHospitalar
   */
  omit?: Prisma.UnidadeHospitalarOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnidadeHospitalarInclude<ExtArgs> | null
  /**
   * Filter which UnidadeHospitalar to delete.
   */
  where: Prisma.UnidadeHospitalarWhereUniqueInput
}

/**
 * UnidadeHospitalar deleteMany
 */
export type UnidadeHospitalarDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UnidadeHospitalars to delete
   */
  where?: Prisma.UnidadeHospitalarWhereInput
  /**
   * Limit how many UnidadeHospitalars to delete.
   */
  limit?: number
}

/**
 * UnidadeHospitalar.leitos
 */
export type UnidadeHospitalar$leitosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Leito
   */
  select?: Prisma.LeitoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Leito
   */
  omit?: Prisma.LeitoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeitoInclude<ExtArgs> | null
  where?: Prisma.LeitoWhereInput
  orderBy?: Prisma.LeitoOrderByWithRelationInput | Prisma.LeitoOrderByWithRelationInput[]
  cursor?: Prisma.LeitoWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.LeitoScalarFieldEnum | Prisma.LeitoScalarFieldEnum[]
}

/**
 * UnidadeHospitalar.profissionais
 */
export type UnidadeHospitalar$profissionaisArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profissional
   */
  select?: Prisma.ProfissionalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profissional
   */
  omit?: Prisma.ProfissionalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfissionalInclude<ExtArgs> | null
  where?: Prisma.ProfissionalWhereInput
  orderBy?: Prisma.ProfissionalOrderByWithRelationInput | Prisma.ProfissionalOrderByWithRelationInput[]
  cursor?: Prisma.ProfissionalWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProfissionalScalarFieldEnum | Prisma.ProfissionalScalarFieldEnum[]
}

/**
 * UnidadeHospitalar without action
 */
export type UnidadeHospitalarDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnidadeHospitalar
   */
  select?: Prisma.UnidadeHospitalarSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnidadeHospitalar
   */
  omit?: Prisma.UnidadeHospitalarOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnidadeHospitalarInclude<ExtArgs> | null
}
