
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.ts'
export type * from './prismaNamespace.ts'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Usuario: 'Usuario',
  Paciente: 'Paciente',
  Profissional: 'Profissional',
  Agenda: 'Agenda',
  Consulta: 'Consulta',
  Prontuario: 'Prontuario',
  Exame: 'Exame',
  Prescricao: 'Prescricao',
  Notificacao: 'Notificacao',
  UnidadeHospitalar: 'UnidadeHospitalar',
  Leito: 'Leito',
  AuditLog: 'AuditLog'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UsuarioScalarFieldEnum = {
  id: 'id',
  email: 'email',
  senhaHash: 'senhaHash',
  perfil: 'perfil',
  ativo: 'ativo',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UsuarioScalarFieldEnum = (typeof UsuarioScalarFieldEnum)[keyof typeof UsuarioScalarFieldEnum]


export const PacienteScalarFieldEnum = {
  id: 'id',
  usuarioId: 'usuarioId',
  nome: 'nome',
  cpf: 'cpf',
  dataNasc: 'dataNasc',
  telefone: 'telefone',
  endereco: 'endereco',
  sexo: 'sexo',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PacienteScalarFieldEnum = (typeof PacienteScalarFieldEnum)[keyof typeof PacienteScalarFieldEnum]


export const ProfissionalScalarFieldEnum = {
  id: 'id',
  usuarioId: 'usuarioId',
  nome: 'nome',
  registroConselho: 'registroConselho',
  especialidade: 'especialidade',
  tipo: 'tipo',
  unidadeId: 'unidadeId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ProfissionalScalarFieldEnum = (typeof ProfissionalScalarFieldEnum)[keyof typeof ProfissionalScalarFieldEnum]


export const AgendaScalarFieldEnum = {
  id: 'id',
  profissionalId: 'profissionalId',
  diaSemana: 'diaSemana',
  horaInicio: 'horaInicio',
  horaFim: 'horaFim',
  ativo: 'ativo',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AgendaScalarFieldEnum = (typeof AgendaScalarFieldEnum)[keyof typeof AgendaScalarFieldEnum]


export const ConsultaScalarFieldEnum = {
  id: 'id',
  pacienteId: 'pacienteId',
  profissionalId: 'profissionalId',
  dataHora: 'dataHora',
  status: 'status',
  tipo: 'tipo',
  observacoes: 'observacoes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ConsultaScalarFieldEnum = (typeof ConsultaScalarFieldEnum)[keyof typeof ConsultaScalarFieldEnum]


export const ProntuarioScalarFieldEnum = {
  id: 'id',
  pacienteId: 'pacienteId',
  consultaId: 'consultaId',
  descricao: 'descricao',
  diagnostico: 'diagnostico',
  data: 'data',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ProntuarioScalarFieldEnum = (typeof ProntuarioScalarFieldEnum)[keyof typeof ProntuarioScalarFieldEnum]


export const ExameScalarFieldEnum = {
  id: 'id',
  consultaId: 'consultaId',
  tipo: 'tipo',
  resultado: 'resultado',
  status: 'status',
  dataSolicitacao: 'dataSolicitacao',
  dataResultado: 'dataResultado',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ExameScalarFieldEnum = (typeof ExameScalarFieldEnum)[keyof typeof ExameScalarFieldEnum]


export const PrescricaoScalarFieldEnum = {
  id: 'id',
  consultaId: 'consultaId',
  profissionalId: 'profissionalId',
  medicamento: 'medicamento',
  dosagem: 'dosagem',
  instrucoes: 'instrucoes',
  dataEmissao: 'dataEmissao',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PrescricaoScalarFieldEnum = (typeof PrescricaoScalarFieldEnum)[keyof typeof PrescricaoScalarFieldEnum]


export const NotificacaoScalarFieldEnum = {
  id: 'id',
  pacienteId: 'pacienteId',
  titulo: 'titulo',
  mensagem: 'mensagem',
  lida: 'lida',
  tipo: 'tipo',
  createdAt: 'createdAt'
} as const

export type NotificacaoScalarFieldEnum = (typeof NotificacaoScalarFieldEnum)[keyof typeof NotificacaoScalarFieldEnum]


export const UnidadeHospitalarScalarFieldEnum = {
  id: 'id',
  nome: 'nome',
  tipo: 'tipo',
  endereco: 'endereco',
  telefone: 'telefone',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UnidadeHospitalarScalarFieldEnum = (typeof UnidadeHospitalarScalarFieldEnum)[keyof typeof UnidadeHospitalarScalarFieldEnum]


export const LeitoScalarFieldEnum = {
  id: 'id',
  unidadeId: 'unidadeId',
  numero: 'numero',
  tipo: 'tipo',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type LeitoScalarFieldEnum = (typeof LeitoScalarFieldEnum)[keyof typeof LeitoScalarFieldEnum]


export const AuditLogScalarFieldEnum = {
  id: 'id',
  usuarioId: 'usuarioId',
  acao: 'acao',
  entidade: 'entidade',
  entidadeId: 'entidadeId',
  detalhes: 'detalhes',
  ip: 'ip',
  createdAt: 'createdAt'
} as const

export type AuditLogScalarFieldEnum = (typeof AuditLogScalarFieldEnum)[keyof typeof AuditLogScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]

