
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.ts'
export { Prisma }
export * as $Enums from './enums.ts'
export * from './enums.ts';
/**
 * Model Usuario
 * 
 */
export type Usuario = Prisma.UsuarioModel
/**
 * Model Paciente
 * 
 */
export type Paciente = Prisma.PacienteModel
/**
 * Model Profissional
 * 
 */
export type Profissional = Prisma.ProfissionalModel
/**
 * Model Agenda
 * 
 */
export type Agenda = Prisma.AgendaModel
/**
 * Model Consulta
 * 
 */
export type Consulta = Prisma.ConsultaModel
/**
 * Model Prontuario
 * 
 */
export type Prontuario = Prisma.ProntuarioModel
/**
 * Model Exame
 * 
 */
export type Exame = Prisma.ExameModel
/**
 * Model Prescricao
 * 
 */
export type Prescricao = Prisma.PrescricaoModel
/**
 * Model Notificacao
 * 
 */
export type Notificacao = Prisma.NotificacaoModel
/**
 * Model UnidadeHospitalar
 * 
 */
export type UnidadeHospitalar = Prisma.UnidadeHospitalarModel
/**
 * Model Leito
 * 
 */
export type Leito = Prisma.LeitoModel
/**
 * Model AuditLog
 * 
 */
export type AuditLog = Prisma.AuditLogModel
