
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Perfil = {
  PACIENTE: 'PACIENTE',
  PROFISSIONAL: 'PROFISSIONAL',
  ADMIN: 'ADMIN'
} as const

export type Perfil = (typeof Perfil)[keyof typeof Perfil]


export const TipoProfissional = {
  MEDICO: 'MEDICO',
  ENFERMEIRO: 'ENFERMEIRO',
  TECNICO: 'TECNICO'
} as const

export type TipoProfissional = (typeof TipoProfissional)[keyof typeof TipoProfissional]


export const StatusConsulta = {
  AGENDADA: 'AGENDADA',
  REALIZADA: 'REALIZADA',
  CANCELADA: 'CANCELADA'
} as const

export type StatusConsulta = (typeof StatusConsulta)[keyof typeof StatusConsulta]


export const TipoConsulta = {
  PRESENCIAL: 'PRESENCIAL',
  ONLINE: 'ONLINE'
} as const

export type TipoConsulta = (typeof TipoConsulta)[keyof typeof TipoConsulta]


export const StatusExame = {
  SOLICITADO: 'SOLICITADO',
  EM_ANALISE: 'EM_ANALISE',
  RESULTADO_DISPONIVEL: 'RESULTADO_DISPONIVEL'
} as const

export type StatusExame = (typeof StatusExame)[keyof typeof StatusExame]


export const TipoUnidade = {
  HOSPITAL: 'HOSPITAL',
  CLINICA: 'CLINICA',
  LABORATORIO: 'LABORATORIO',
  HOME_CARE: 'HOME_CARE'
} as const

export type TipoUnidade = (typeof TipoUnidade)[keyof typeof TipoUnidade]


export const StatusLeito = {
  LIVRE: 'LIVRE',
  OCUPADO: 'OCUPADO',
  MANUTENCAO: 'MANUTENCAO'
} as const

export type StatusLeito = (typeof StatusLeito)[keyof typeof StatusLeito]


export const DiaSemana = {
  SEGUNDA: 'SEGUNDA',
  TERCA: 'TERCA',
  QUARTA: 'QUARTA',
  QUINTA: 'QUINTA',
  SEXTA: 'SEXTA',
  SABADO: 'SABADO',
  DOMINGO: 'DOMINGO'
} as const

export type DiaSemana = (typeof DiaSemana)[keyof typeof DiaSemana]
