
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/Usuario.ts'
export type * from './models/Paciente.ts'
export type * from './models/Profissional.ts'
export type * from './models/Agenda.ts'
export type * from './models/Consulta.ts'
export type * from './models/Prontuario.ts'
export type * from './models/Exame.ts'
export type * from './models/Prescricao.ts'
export type * from './models/Notificacao.ts'
export type * from './models/UnidadeHospitalar.ts'
export type * from './models/Leito.ts'
export type * from './models/AuditLog.ts'
export type * from './commonInputTypes.ts'